tailwindlabs/headlessui

- packages/@headlessui-react/README.md
- packages/@headlessui-vue/README.md
We'll want to create demos for this stuff too soon. I think unfortunately we are going to outgrow this "giant readme" format pretty quickly (or maybe not, maybe need to go full GameFAQs on this). When we build a proper website we can probably just add demos there so we don't have to wrestle with CodeSandbox, but sandboxes are probably still the best bet for now. Hoping to do that tomorrow.
> docs: Document React Menu, tweak Transition and Vue docs to be consistent

- packages/@headlessui-react/README.md
The react documentation around the `Menu` component's interaction with the `Transition` component could use some improvement, so here is my attempt at improving it.
> Improve documentation for Menu transitions

- packages/@headlessui-react/README.md
> fix "Transition" link href in @headlessui-react readme

- .github/dependabot.yml
Dependabot will check for npm updates each working day (Monday trough Friday).
It will label any pull requests it makes with the `dependencies` label.
I think it's a good idea to use a bot to check for updates.
> Use Dependabot to check for npm updates

- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- make sure the Button is focused when the Menu closes (React)
- make sure the Button is focused when the Menu closes (Vue)
- make sure the Button is focused when the Listbox closes (React)
- make sure the Button is focused when the Listbox closes (Vue)
> fix button focus management

- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- make sure the Menu.Button can be disabled (React)
- make sure the MenuButton can be disabled (Vue)
- make sure the Listbox.Button can be disabled (React)
- make sure the ListboxButton can be disabled (Vue)
Fixes: #48
> Allow disabling the Menu/Listbox button

- packages/@headlessui-vue/README.md
Hello!
💁‍♀️ This PR makes a small correction in the Vue documentation for the `Switch` component.
Super small fix, but looks like the docs for React made their way over to Vue 🎉
> docs: Vue component names not dot-separated

- packages/@headlessui-react/README.md
- packages/@headlessui-react/pages/transitions/component-examples/modal.tsx
- packages/@headlessui-react/src/components/transitions/transition.test.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
> Add Transition events

- package.json
- packages/@headlessui-react/package.json
- packages/@headlessui-react/pages/listbox/multiple-elements.tsx
- packages/@headlessui-react/pages/menu/multiple-elements.tsx
- packages/@headlessui-react/playground-utils/resolve-all-examples.ts
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-vue/examples/src/App.vue
- packages/@headlessui-vue/examples/src/components/listbox/multiple-elements.vue
- packages/@headlessui-vue/examples/src/components/menu/multiple-elements.vue
- packages/@headlessui-vue/examples/src/routes.json
- packages/@headlessui-vue/package.json
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
- scripts/watch.sh
- yarn.lock
> fix: outside click refocus bug

- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
The default displayName for a react context is Context so in the react devtools we get
This can make it difficult to navigate the react devtools when there are a lot of contexts in play. This PR adds a displayName to the all contexts in the react portion of HeadlessUI meaning we end up with
Which is easier to understand at a glance and makes navigating around easier as we can find them in the search.
https://reactjs.org/docs/context.html#contextdisplayname
> Add displayName to all contexts in react

- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/utils/bugs.ts
And if we are in a disabled fieldset, double check that we are not in
the first legend. Because in that case we are visually outside of the
fieldset and according to the spec those elements should **not** be
considered disabled.
Fixes: #194
> apply disabled fix when inside a disabled fieldset

- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
> trigger "outside click" behaviour on mousedown

- packages/@headlessui-react/README.md
- packages/@headlessui-vue/README.md
A discord member states that the current examples in the readme file don't look good at the moment.
I think it is useful to have a nice example here to increase the enjoyment of headlessui.
However, the switch should not look like the one in TailwindUI since this is a paid collection.
Thus, I changed the style a little in order to look okay for a first starting point.
> Added new examples for switch components (React, Vue)

- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/utils/render.ts
When using the `forwardRef`, utility we loose the information like `Component.name`, to fix this I added the `name` to the result of the `forwardRef`. That said, this causes build errors in certain scenario's (see #246).
This PR will fix that by applying `displayName` instead.
> fix object assign name

- CHANGELOG.md
- packages/@headlessui-react/src/types.ts
> Fix unique symbol error

- CHANGELOG.md
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/utils/dom.ts
- add small dom utility to resolve the dom node from a ref
- use dom() to resolve underlying DOM node
Closes: #21
> fix ref element

- CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-react/src/utils/focus-management.ts
We have `outside click` behaviour implemented. Whenever the target
element is focusable we make sure that the newly clicked/focused element
stays focused. If it is not a focusable element we will make sure that
the Menu/Listbox button is re-focused so that screenreader users don't
get confused.
This is all fine, but it turns out that when you have a button with a
span, and you click on the span, then the event.target will be that
span. The span itself is not focusable of course, but the button will
get the focus. This results in the Menu/Listbox button being re-focused
which is incorrect.
For this we will introduce a FocusableMode on the `isFocusableElement`,
we will have a `Strict` mode, which means the actual element should be
focusable. And a `Loose` mode, which means that the actual …
> Fix refocus button bug

- CHANGELOG.md
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/types.ts
- packages/@headlessui-react/src/utils/render.ts
- packages/@headlessui-react/src/utils/resolve-prop-value.ts
Every component that accepts a className should be able to pass in a
function. This function will retrieve the render prop arg for this
component. The function should resolve to a string in the end.
This makes the API a bit nicer if you just need to change the classNames
based on some internal state.
E.g.:
```jsx
// Before
<Menu.Button as={Fragment}>
{({ open }) => (
<button className={open ? 'font-bold' : 'font-normal'}>
Hello
</button>
)}
</Menu.Button>
// After
<Menu.Button className={({ open }) => open ? 'font-bold' : 'font-normal'}>
Hello
</Menu.Button>
```
> class name functions

- packages/@headlessui-vue/package.json
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/test-utils/interactions.test.ts
- yarn.lock
- bump Vue
- ensure we reference the vite.config.js
- fix event name casing
> Vue breaking change

- CHANGELOG.md
- packages/@headlessui-react/src/types.ts
- packages/@headlessui-vue/package.json
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/test-utils/interactions.test.ts
- yarn.lock
- fix unique symbol error (#248)
- Vue breaking change (#279)
> backfill fixes

- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
When the RadioGroup uses raw strings or numbers everything is fine. But once we use objects, we have to ensure that we are comparing the actual raw objects (not the objects wrapped in Proxies).
> Ensure we compare raw values

- packages/@headlessui-vue/src/utils/render.test.ts
- packages/@headlessui-vue/src/utils/render.ts
We didn't take functional components into account, therefore we would
receive errors because a Transition component is a functional component
in production and we didn't take that into account.
> Fix validation for Vue render function

- packages/@headlessui-react/src/components/description/description.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/label/label.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/README.md
- packages/@headlessui-react/src/components/switch/switch.test.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-vue/src/components/description/description.ts
- packages/@headlessui-vue/src/components/label/label.ts
- packages/@headlessui-vue/src/components/switch/README.md
- packages/@headlessui-vue/src/components/switch/switch.test.tsx
- packages/@headlessui-vue/src/components/switch/switch.ts
- improve internal Label component
- improve internal Description component
- provide the name prop to Description & Label providers
- implement the useLabels and useDescriptions in the Switch components
> Use internal label and descriptions

- packages/@headlessui-vue/src/components/description/description.test.ts
- packages/@headlessui-vue/src/components/description/description.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/label/label.test.ts
- packages/@headlessui-vue/src/components/label/label.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
I was on a walk, and I realised that in Vue you can just call
provide(Symbol, context), which means that a hook like `useLabels` can
just provide context...
This simplifies a lot!
> Skip the Provider component and simplify context

- CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.test.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-vue/examples/src/components/dialog/dialog.vue
- packages/@headlessui-vue/src/components/transitions/transition.test.ts
- packages/@headlessui-vue/src/components/transitions/transition.ts
- packages/@headlessui-vue/src/index.test.ts
- rename Transition to TransitionRoot
- alias Transition.Root to Transition
> Improve transition naming

- CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-focus-trap.ts
- packages/@headlessui-vue/src/hooks/use-focus-trap.ts
Once you are using Tab and Shift+Tab it does the scrolling.
Fixes: #345
> Enable NoScroll feature for the initial useFocusTrap hook

- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- make search case insensitive for the listbox
- make search case insensitive for the menu
Fixes: #381
> Improve search

- CHANGELOG.md
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/test-utils/vue-testing-library.ts
Also did some general cleanup which in turn fixed an issue where the
RadioGroup is unreachable when a value is used that doesn't exist in the
list of options.
Fixes: #378
> add `disabled` prop to RadioGroup and RadioGroup Option

- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
Regarding Vue implementation
RadioGroup modelValue is set to
```
modelValue: { type: [Object, String, Number, Boolean] },
```
But RadioGroupOption value is set to
```
value: { type: [Object, String] },
```
So this is just a simple tweak to RadioGroupOption value types to match modelValue allowed types for RadioGroup to stop prop types warning when using Number or Boolean
> Match RadioGroupOption types to RadioGroup in radio-group.ts

- .github/workflows/main.yml
- Use `actions/setup-node@v2`
- Use latest stable Node version (v14)
> chore(CI): update main workflow

- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/test-utils/vue-testing-library.ts
- re-export the `screen` utility for quick debugging purposes
- stop event propagation when clicking inside a Dialog
> fix dialog event propagation

- CHANGELOG.md
- packages/@headlessui-react/pages/dialog/dialog.tsx
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
- Make sure that `Escape` only closes the top most Dialog
This is a weird bug honestly, if you have 3 nested Dialogs, press `Escape` then it will close the top 2 Dialogs. If you have 5 nested Dialogs, press `Escape` again, the top 2 Dialogs are closed.
The code is now cleaner anyway, because it used to listen to a global window event, instead of scoping it to the Dialog itself.
> improve dialog escape

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/hooks/use-focus-trap.ts
- packages/@headlessui-react/src/hooks/use-id.ts
- packages/@headlessui-react/src/hooks/use-server-handoff-complete.ts
- delay initialization of Dialog
- add hook to deal with server handoff
- use server handoff complete hook
Fixes: #470
Fixes: #450
> Improve dialog and server handoff

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/hooks/use-focus-trap.ts
- packages/@headlessui-react/src/hooks/use-is-mounted.ts
- packages/@headlessui-react/src/hooks/use-window-event.ts
- packages/@headlessui-react/src/internal/dom-containers.ts
- packages/@headlessui-react/src/internal/stack-context.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
This PR will fix a few things. Mainly we incorrectly assumed that having a Portal inside a Dialog that this also meant that we have to disable certain features. While this is true for nesting Dialogs and nested Menu components, this is not true if you just use a Portal for rendering specific things.
This PR simplifies and corrects that behaviour. We also added dedicated tests that verify that nested Dialogs work as expected.
> Fix incorrect nested Dialogs behaviour

- CHANGELOG.md
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/transitions/transition.ts
- packages/@headlessui-vue/src/internal/open-closed.ts
When you are using the implicit variants of the components, for example
when you are using a Transition component inside a Menu component then
it might look weird in Vue.
The Vue code could look like this:
```
<Menu>
<TransitionRoot>
<MenuItems>...</MenuItems>
</TransitionRoot>
<Menu>
```
However, `TransitionRoot` doesn't make much sense here because it sits
in the middle of 2 components, and it is also not controlled by an
explicit `show` prop.
This commit will allows you to use a `TransitionChild` instead (in fact,
both work).
We basically now do a few things, when you are using a TransitionChild:
- Do we have a parent `TransitionRoot`? Yes -> Use it
- Do we have an open closed state? Yes -> Render a TransitionRoot in
between behind the scenes.
- Throw the error we were throwing before!
> Ensure that you can use Transition Child components in more scenario's

- packages/@headlessui-react/pages/dialog/dialog.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/components/transitions/utils/transition.test.ts
- packages/@headlessui-react/src/components/transitions/utils/transition.ts
- packages/@headlessui-vue/examples/src/components/dialog/dialog.vue
- packages/@headlessui-vue/src/components/transitions/transition.ts
- packages/@headlessui-vue/src/components/transitions/utils/transition.test.ts
- packages/@headlessui-vue/src/components/transitions/utils/transition.ts
This PR will allow you to add an additional `entered` prop with a bunch of classes. This prop contains all the classes that you want to make sure that exist when the transitions are done.
E.g.:
```js
<Transition
enter="duration-300 transition-opacity"
enterFrom="opacity-0"
enterTo="opacity-75"
entered="opacity-75"
>
<div className="..."></div>
</Transition>
```
If we don't have this then the `opacity-75` would be gone after it is done transitioning. This will result in a full opaque background.
**Can't we solve this already:**
Yes, there are some situations where it is doable to solve these kind of problems. For example you can transition from `opacity-0` to `opacity-100` and keep a `bg-opacity-75` always applied. But this doesn't work for other utilities.
**Can't you keep the classes …
> Add `entered` prop to Transition components

- CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/examples/src/components/listbox/listbox.vue
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/utils/render.ts
In some places we were destructuring data from the incoming `props`. But this means that we also loose some reactivity along the way. This PR fixes that.
We also improved the `disabled` prop. It was failing because of 2 reasons:
1. Because of the reactivity issue, we lost "updates" to this prop.
2. We always had a `tabindex: -1`, but that is now conditionally applied based on the incoming `disabled` prop.
Fixes: #508 
Fixes: #509 
Fixes: #483
> Improve Vue reactivity & `disabled` prop

- CHANGELOG.md
- packages/@headlessui-vue/src/components/listbox/listbox.ts
This makes the ListboxOption value type consistent with the Listbox modelValue type, which I think makes sense. I ran into an issue with this using a number for the ListboxOption value.
> Make Listbox types consistent

- CHANGELOG.md
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
```
<Switch
v-model="enable"
:class="[
...classButton,
'relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500',
]"
>
...
```
```
node_modules/@headlessui/vue/dist/components/switch/switch.d.ts:45:5
45     class?: string | Function | undefined;
~~~~~
The expected type comes from property 'class' which is declared here on type 'Partial<{ as: string; modelValue: boolean; }> & Omit<Readonly<{ as: string; modelValue: boolean; } & { class?: string | Function | undefined; className?: string | Function | undefined; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "as" | "modelValue"> & Omit<...> & Record<...>'
```
Fixes …
> Remove explicit class prop

- packages/@headlessui-react/package.json
- packages/@headlessui-react/tsdx.config.js
In order to enable tree-shaking, we need to specify `sideEffects: true`,
unfortunately, after experiments, it turned out not to be enough and I had to enable `preserveModules`, which webpack seems to be able to use to properly remove unused code, that part was Inspired by https://github.com/formium/tsdx/issues/276
I first noticed that headless-ui is not being tree-shaked in lighthouse:
After adding the changes in this PR the packages is no longer showing up as unused:
I also ran @next/bundle-analyzer
Before:
After:
Also, before / after results from Chrome:
> Support tree-shaking

- CHANGELOG.md
- packages/@headlessui-react/src/components/disclosure/disclosure.test.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-vue/src/components/disclosure/disclosure.test.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.ts
If you do it this way, then the `Disclosure.Button` will function as a
`close` button.
This will make it consistent with the `Popover.Button` inside the
`Popover.Panel` funcitonality.
> Add ability to use `Disclosure.Button` inside a `Disclosure.Panel`

- CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
By default the `Listbox` will have an orientation of `vertical`. When
you pass the `horizontal` prop to the `Listbox` component then the
`aria-orientation` will be set to `horizontal`.
Additionally, we swap the previous/next keys:
- Vertical: ArrowUp/ArrowDown
- Horizontal: ArrowLeft/ArrowRight
> Add `aria-orientation` to the Listbox component

- packages/@headlessui-react/src/components/disclosure/disclosure.test.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/src/components/disclosure/disclosure.test.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.ts
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
In addition to the `Popover.Button` inside a `Popover.Panel` and a `Disclosure.Button` inside a `Disclosure.Panel`, we will now expose a `close` function in the render prop. This will give you a bit more control over how you can close the `Disclosure` and `Popover`.
The `close` function is exposed on the following components:
- `Popover` 
- `Popover.Panel` & `PopoverPanel`
- `Disclosure`
- `Disclosure.Panel` & `DisclosurePanel`
When you call the `close` function with no arguments, then we will restore the focus to the `Popover.Button` or `Disclosure.Button` for accessibility purposes.
You can also passthrough an actual element, or a ref to focus that element instead.
> Expose close functionality

- CHANGELOG.md
- packages/@headlessui-react/pages/tabs/tabs-with-pure-tailwind.tsx
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/index.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/index.test.ts
- Change Tabs API (React)
- Change Tabs API (Vue)
> Change tabs api

- CHANGELOG.md
- packages/@headlessui-react/src/components/disclosure/disclosure.test.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/switch/switch.test.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/hooks/use-resolve-button-type.ts
- packages/@headlessui-react/src/hooks/use-sync-refs.ts
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.test.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/components/switch/switch.test.tsx
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/hooks/use-resolve-button-type.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
We naively put `type: button` on certain components because the default component is a `button`. However, when somebody uses the `as` prop with a different component like `div`, then adding a type of button results in weird/incorrect behaviour.
This PR will check what the actual rendered DOM element is, and if it is a button without a type, only then will we apply a type of button.
Fixes: #619
> Only add `type=button` for real buttons

- CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/components/transitions/transition.ts
Original PR: #679 
Added an improvement and implemented it for the `Tabs` component as well.
> Add Vue emit types

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
We've "fixed" an issue when we had nested Dialogs ([#430](https://github.com/tailwindlabs/headlessui/pull/430)).
The `escape` would not close the correct Dialog. The issue here was with
the logic to know whether we were the last Dialog or not. The issue was
_not_ how we implemented the `close` functionality.
To make things easier, we moved the global window event to a scoped div
(the Dialog itself). While that fixed the nested Dialog issue, it
introduced this bug where `escape` would not close if you click on a
non-focusable element like a span in the Dialog.
Since that PR we did a bunch of improvements on how the underlying
"stacking" system worked.
This PR reverts to the "global" window event listener so that we can
still catch all of the `escape` keydown events.
Fixes: #524
Fixes: #693
> Fix broken `escape` key behaviour

- CHANGELOG.md
- packages/@headlessui-react/src/components/focus-trap/focus-trap.test.tsx
- packages/@headlessui-react/src/hooks/use-focus-trap.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.test.ts
- packages/@headlessui-vue/src/hooks/use-focus-trap.ts
Currently the FocusTrap will throw an error when there are no focusable elements found. While this error is still important, we will now use `console.warn` instead of actually throwing an error. You can think of it as a progressive enhancement.
However, if you have this warning, there is a good chance hat there is still _something_ wrong in the code. Having a focusable element is important for screenreaders and other assistive technology.
That said, we have some ideas how we can ensure that the `console.warn` goes away even if you don't have focusable elements while keeping the whole `Dialog` component accessible. This is a bigger issue to work on, and will be added in the future. But for now, the warning approach is a good first step.
If you were bitten by this issue, please double check …
> Warn instead of error

- CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/src/components/popover/popover.ts
We usually prevent the default behaviour and stop the propagation when pressing escape, but they were missing for the `Popover` component.
Fixes: #779
> Ensure we stop the event from propagating

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
> Allow to click on elements inside a Dialog Overlay

- CHANGELOG.md
- packages/@headlessui-react/src/components/portal/portal.tsx
When using NextJS, it happens that between page transitions the portal
root gets removed form the DOM. We will check the DOM when the `target`
updates, and if it doesn't exist anymore, then we will re-insert it in
the DOM.
> Ensure portal root exists in the DOM

- CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR will allow you to control the `Tabs` state using the `selectedIndex` prop.
The `defaultIndex` still exist and will still be the defaultIndex if no `selectedIndex` prop was provided.
Started this PR from #909 with a few improvements and Vue implementation.
Thanks @ChiefORZ for your initial work!
Closes: #909
> Allow `Tabs` to be controllable

- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR is a rebased version of #986
Closes: #986
> Fix slice => splice typo in Vue Tabs component

- CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
This PR will ensure that whenever we are performing focus actions on DOM nodes, that those DOM nodes are in the correct order. This is important so that when you want to `focusIn(listOfDOMNodes, Focus.Next)` that you are actually focusing the next item in the DOM, and not the next item in the list.
This is currently fixed in a spot where we are performing the actions, in a perfect world the list is already correctly sorted. But there are a few other issues I want to fix that should solve this as well. But in the meantime this is good place to have this logic.
Fixes: #1015
> Ensure correct DOM node order when performing focus actions

- CHANGELOG.md
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/examples/src/components/tabs/tabs.vue
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
We just made 2 new releases:
- [@headlessui/react@v1.4.2](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v1.4.2)
- [@headlessui/vue@v1.4.2](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Fvue%40v1.4.2)
Diffs:
- [`@headlessui/react@v1.4.1`...`@headlessui/react@v1.4.2`](https://github.com/tailwindlabs/headlessui/compare/@headlessui/react@v1.4.1...@headlessui/react@v1.4.2)
- [`@headlessui/vue@v1.4.1`...`@headlessui/vue@v1.4.2`](https://github.com/tailwindlabs/headlessui/compare/@headlessui/vue@v1.4.1...@headlessui/vue@v1.4.2)
Next diffs (unreleased):
- [`@headlessui/react@v1.4.2`...`HEAD`](https://github.com/tailwindlabs/headlessui/compare/@headlessui/react@v1.4.2...HEAD)
- [`@headlessui/vue@v1.4.2`...`HEAD`](https://github.com/tailwind …
> Next release

- CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
This PR will ensure that the order of `Menu.Item`, `Listbox.Option` and `RadioGroup.Option` is correct even if you re-rendered some items conditionally essentially re-ordering them.
This is both applied to the React and Vue versions.
Fixes: #994
> Ensure correct order when conditionally rendering `Menu.Item`, `Listbox.Option` and `RadioGroup.Option`

- CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
This PR improves the tests for the controlled Tabs (Thanks @RyogaK!). 
It also includes a fix for the buggy behaviour in the React component.
Closes: #1049
> Improve controlled Tabs behaviour

- CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
This PR will make some improvements to the typeahead logic.
This ensures that if you have 4 items:
- Alice
- Bob
- Charlie
- Bob
And you search for `b`, then you jump to the first `Bob`, but if yuo
search again for `b` then we used to go to the very first `Bob` because
we always searched from the top. Now we will search from the active item
and onwards. Which means that we will now jump to the second `Bob`.
Closes: #1046
> Improve typeahead search logic

- packages/@headlessui-vue/package.json
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/description/description.test.ts
- packages/@headlessui-vue/src/components/description/description.ts
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/src/components/label/label.test.ts
- packages/@headlessui-vue/src/components/label/label.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/components/transitions/transition.ts
- packages/@headlessui-vue/vercel.json
- packages/playground-vue/src/components/menu/menu.vue
- yarn.lock
This updates the minimum Vue version to 3.2 and moves all the explicit definitions of `render()` to a function returned by `setup()`.
> Update minimum Vue to 3.2

- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.ts
When you add elements between `Combobox.Options` and `Combobox.Option` then we will mark them using `role: none` if they don't have a `role` already.
This is similar behaviour to the `Menu` component and we probably want this behaviour for the `Listbox` itself.
> Ignore non-option roles

- scripts/build.sh
The Headless UI docs require some bumps in packages because it currently
can't handle es2020 features like `??`. This temporary workaround should
fix this in the mean time.
> Temporarily target es2019 instead of es2020

- CHANGELOG.md
- package.json
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-vue/src/components/combobox/combobox.test.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
- packages/@headlessui-vue/src/utils/dom.ts
- packages/playground-vue/src/components/combobox/combobox-with-pure-tailwind.vue
- packages/playground-vue/src/components/combobox/command-palette-with-groups.vue
- packages/playground-vue/src/components/combobox/command-palette.vue
- packages/playground-vue/src/routes.json
- scripts/lint.sh
> Fix Combobox issues

- CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
This PR ensures that if you have multiple items like:
- Alice
- Bob
- Charlie
- Bob
And you type `b`, then it should jump to the first `bob`, when you wait a bit and type `b` again, then we should go to the second `bob`, so far so good.
The issue is if you type `bob` or to be clear `b`, `o`, `b`, then it will jump to the first bob for `b`, to the second bob for `o` and to the first bob again for `b`.
This PR fixes that by making sure that you stay on the same bob while you are searching. Once the search time is over, then we will continue from that point onwards.
Fixes: #1090
> Ensure typeahead stays on same item if it still matches

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
If you use `<Combobox.Options static />` it means that you are in
control of rendering and in that case we also bubble the `Escape`
because you are in control of it.
However, if you do something like this:
```js
{filteredList.length > 0 && (
<Combobox.Options static>
...
</Combobox.Options>
)}
```
Then whenever the `filteredList` is empty, the Combobox.Options are not
rendered at all which means that we can't look at the `static` prop. To
fix this, we also bubble the `Escape` event if we don't have a
`Combobox.Options` at all so that the above example works as expected.
> Bubble Escape event even if `Combobox.Options` is not rendered at all

- CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/playground-vue/src/components/combobox/combobox-with-pure-tailwind.vue
This PR will ensure that the `ComboboxInput` syncs correctly in Vue.
It will also remove the incorrectly passed `displayValue` from the DOM element.
> Ensure `ComboboxInput` syncs correctly

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
Right now when you press arrow up/down/etc… and change the active item we wait for two rAF call backs. This has the affect of waiting after two full paints have finished. This results in, for the react version of the Combobox, a period of 1 frame where the active item has changed and re-rendered but the scroll hasn't happened yet.
Now, it is common to have to wait 2 rAF frames for the DOM to have updated in React because of a Chrome (and possibly Safari) bug with animations. However, in this case we're not waiting for animations to start, just scrolling. As far as I know the DOM *should* be updated by the end of the first cal to rAF but perhaps we should check if the element exists and schedule another one if it doesn't?
I'd also be curious to see if this behavior is a problem in React 18 …
> Fix off-by-one frame issue causing flicker

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
This PR will fix an issue that the current active item could be invisible (scrolled out of the viewport).
This mainly happens if you add a bunch of items before the active one so that the active one gets pushed down and eventually becomes invisible.
To fix this, we will also make sure to trigger the effect if the position of the active item changes.
> Trigger scrollIntoView effect when position changes

- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
This PR adds a private demo mode that is not subject to SemVer and should not be used.
> Add private demo mode

- .github/workflows/main.yml
- .github/workflows/release-insiders.yml
This will allow you to cancel older running actions for the current PR /
branch. This saves you some resources, but more importantly hopefully
frees up some spots in the queue a bit faster.
Saw this on the Node.js repo: https://github.com/nodejs/node/pull/42017
> Improve concurrency of GitHub Actions

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR will make sure that in Vue the input also syncs correctly when the combobox closes. Whether it be via Escape or outside click.
We also added a test for React just to verify the behaviour and to prevent future regressions.
Fixes: #1136
> Make sure that the input syncs when the combobox closes

- CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
The issue is that `onInput` fires on every keystroke, and we also
handled `onChange` which is triggered on blur in Vue.
This means that the moment we blur, we also called the `handleChange`
code to re-open the combobox because we want to open the combobox if
something changes when the user starts typing.
To fix this, we will splitup the logic so that it will only open the
combobox on input but not on change.
Fixes: #1147
> Ensure that you can close the combobox initially

- packages/@headlessui-react/src/components/transitions/transition.tsx
This PR provides some improvements to the Transition component.
> Transition improvements

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/description/description.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/label/label.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/hooks/use-sync-refs.ts
- packages/@headlessui-react/src/utils/render.ts
- packages/playground-react/pages/menu/menu-with-framer-motion.tsx
- packages/playground-react/pages/menu/menu.tsx
This PR will ensure that you can add the `ref` prop to all the components we expose.
Fixes: #273
Fixes: #664
> Forward the `ref` to all components

- CHANGELOG.md
- packages/@headlessui-vue/src/hooks/use-focus-trap.ts
Initially I thought that our open/closed internal state was conflicting between the Tab and Dialog. But that isn't the case at all.
The issue is in the focus trap currently we are collecting the `restoreElement` even if the focus trap is not enabled. When we unmount we try to restore it.
The problem is the moment you unmount you want to restore but only if the focus trap was enabled.
Another issue is that the dialog state will be `closed` before we get to the `onUmount` hook. So there is probably a cleaner way to fix this, but this does the trick as well where we only record the restoreElement the moment the focus trap gets enabled.
Fixes: #1100
> Fix Dialog usage in Tabs

- CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
This PR will ensure that when you use a Popover Button inside a Popover Panel and the button is used as a link that the link gets invoked correctly.
Fixes: #1152
> Ensure links are triggered inside `Popover Panel` components

- CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/playground-react/pages/tabs/tabs-with-pure-tailwind.tsx
This PR will improve the SSR of the Tabs component so that the panel will be rendered on the server as well.
Fixes: #1086
> Improve SSR for `Tab` component

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/playground-vue/src/components/listbox/listbox.vue
This PR is a continuation of #1058.
This will make sure that the scroll into view only happens if the active item/option gets activated automatically (e.g.: active when opened) or when it gets activated via the keyboard.
If the item/option gets activated via the mouse then we don't want to scroll into view because this feels a bit janky and fights against your scrollwheel.
Closes: #1058
Fixes: #769
> Fix `hover` scroll

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
We already fixed a bug in the past where the order of DOM nodes wasn't stored in the correct order when performing operations (e.g.: using your keyboard to go to the next option).
We fixed this by ensuring that when we register/unregister an option/item, that we sorted the list properly. This worked fine, until we introduced the Combobox components. This is because items in a Combobox are continuously filtered and because of that moved around.
Moving a DOM node to a new position _doesn't_ require a full unmount/remount. This means that the sort gets messed up and the order is wrong when moving around again.
To fix this, we will always perform a sort when performing actions. This could have performance drawbacks, but the alternative is to re-sort when the component gets updated. The bad …
> Guarantee DOM sort order when performing actions

- CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.tsx
I think I figured it out! (I hope)
Basically the transition component's show defaulted to `true` — which is fine. However, we also have an initial render check. This means that the transition doesn't run on first render. But if you trigger a re-render of children without a change in the show state it'll run the enter transition.
This means that:
1. If an item is already visible
2. The enter from is `opacity-0`
Then the transition starts and assumes that the element is invisible. This causes the weird animation flicker where it goes from visible to quickly not visible to visible again. The solution is to store the previous show state and only transition if it is actually different.
> Fix React `<Transition>` flicker issue

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
We used to use `pointerdown`, but some older devices with iOS 12 didn't
have support for that. Instead we used `mousedown`. But now it turns out
that some devices only properly use `pointerdown` and not the `mousedown` event.
Instead, we will listen to both, but make sure to only handle the event
once.
Fixes: #1173
> Improve outside click support

- CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.tsx
When a Transition happens we should only care about the `appear` prop and the `show` prop, regardless of how many times the Transition component gets re-rendered.
We already fixed the part about the multiple re-renders for the `show` prop (see: #1118), but we didn't take the `appear` prop into account.
Fixes: #1060
Fixes: #714
> Ensure that `appear` works regardless of multiple rerenders

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR will make sure that when you reset the value from the Combobox from the outside world (e.g.: state reset) that the input also correctly syncs.
Currently we only sync it if we have a string value or a `displayValue` but now we will also reset to nothing by default.
Fixes: #1177
> Reset Combobox Input when the value gets reset

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
We had various ordering issues, and now we properly sort all the notes
which is awesome. However, there is this case where we still use the
`activeOptionIndex` / `activeItemIndex` from _before_ the sort happens.
Now we will ensure that this is properly adjusted when performing the
sort of the items.
In addition, we will also properly adjust these values when
`registering` and `unregistering` items, not only when performing
actions.
Fixes: #1170
> Adjust active {item,option} index

- CHANGELOG.md
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/hooks/use-focus-trap.ts
The code for React already worked, let's update the Vue code to make it similar which properly restores focus. The bad sign is that we already had tests for this that passed... Let's investigate in setting up tests in a more real environment like Puppeteer or Playwright soon...
Fixes: #844
> Fix re-focusing element after close

- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR will fix when the Tab gets activated. We want it to get activated when you focus it via the keyboard and when you click it. But we also want the click to be completed (mouseup) before activating.
But by default on a button, the `focus` event gets fired before the `click` event. This means that the Tab gets activated to early.
This doesn't happen on Safari, but it does happen on Chrome and other browsers.
This PR will fix that behaviour, and only enable it if the click is complete (mouseup).
Fixes: #845
> Only activate the `Tab` on mouseup

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
This PR is a continuation of #869. It fixes an issue where a click on a removed element will close the Dialog. In this case, we will ignore "outside clicks" on removed elements.
This is a rebased version and also an implementation for Vue.
Closes: #869
> Ignore "outside click" on removed elements

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.test.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/internal/visually-hidden.tsx
- packages/@headlessui-react/src/utils/form.test.ts
- packages/@headlessui-react/src/utils/form.ts
- packages/@headlessui-react/src/utils/render.ts
- packages/@headlessui-react/tsconfig.json
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.test.tsx
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/internal/visually-hidden.ts
- packages/@headlessui-vue/src/utils/form.test.ts
- packages/@headlessui-vue/src/utils/form.ts
- packages/@headlessui-vue/src/utils/render.ts
- packages/@headlessui-vue/tsconfig.json
- packages/playground-react/pages/combinations/form.tsx
- packages/playground-react/tsconfig.json
This PR will add `<form>` compatibility.
We have a few form element related components:
- Combobox
- Listbox
- RadioGroup
- Switch
The issue is that you manually have to wire these components to form input if
you want them to be included when you submit your form.
This PR will make that a bit easier for you. On the component listed above, you
can now add a `name` prop, once you do that a hidden input field will be
rendered with the selected value.
---
If your data (for example the `value` of your `Listbox.Option`) is an object, then we will make sure to properly encode it. Here is an example:
```js
// Assuming we have a `name` of `person`
let value = ['Alice', 'Bob', 'Charlie']
```
Results in:
```html
<input type="hidden" name="person[]" value="Alice" />
<input type="hidden" …
```
> Add `<form>` compatibility

- CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
In the Vue version of the combobox the input is synced when the combobox state changes. This is done because closing the combobox needs to reflect the current selected value. For example, pressing the `Escape` key after searching should revert to what the value was before the user started searching.
However, doing this on *open* is problematic:
1. Typing in the input field will open the combobox if it's not open already.
2. Opening the combobox causes the internal state to change.
3. This state change causes the input to be synced.
All three of these steps happen in the same render cycle. This causes the value that would've been written by the `input` event to be lost because the value is synced with the old value that is currently in state. This manifested as the first character causing …
> Don’t drop initial character when searching in Combobox

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/hooks/use-event-listener.ts
- packages/@headlessui-react/src/hooks/use-focus-trap.ts
- packages/@headlessui-react/src/hooks/use-inert-others.ts
- packages/@headlessui-react/src/hooks/use-owner.ts
- packages/@headlessui-react/src/hooks/use-sync-refs.ts
- packages/@headlessui-react/src/hooks/use-tree-walker.ts
- packages/@headlessui-react/src/hooks/use-window-event.ts
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-react/src/utils/owner.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/components/portal/portal.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/hooks/use-event-listener.ts
- packages/@headlessui-vue/src/hooks/use-focus-trap.ts
- packages/@headlessui-vue/src/hooks/use-inert-others.ts
- packages/@headlessui-vue/src/hooks/use-tree-walker.ts
- packages/@headlessui-vue/src/hooks/use-window-event.ts
- packages/@headlessui-vue/src/utils/dom.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
- packages/@headlessui-vue/src/utils/owner.ts
We are currently relying on `window` and `document`, but those are not always the correct instances. When you are in an iframe or opened a new window, there is a different owner. You can get this owner by using `node.ownerDocument`
In this PR we will use the correct `ownerDocument`. In addition, we will also use the correct `window` which can be found via `el.ownerDocument.defaultView`
Fixes: #966
> Use `ownerDocument` instead of `document`

- CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/components/transitions/transition.ts
We used to expose a custom `el` when we used a `setup()` and `render()`
function. But due to some refactors we got now only have a `setup()` and
no more `el`. This causes some problems if people relied on the exposed
`el`.
In this PR will make sure to re-expose the `el` that we used to expose.
The only issue is, now that we manually expose a list, we have to
re-expose the `$el` internal as well.
Fixes: #1222
> Re-expose `el`

- CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/internal/focus-sentinel.tsx
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/internal/focus-sentinel.ts
- packages/playground-react/pages/combinations/tabs-in-dialog.tsx
- packages/playground-vue/src/components/combinations/tabs-in-dialog.vue
- packages/playground-vue/src/routes.json
When you render `Tabs` inside a `Dialog` then you will receive a warning like this: `There are no focusable elements inside the <FocusTrap />`
This is because the `Dialog` uses a `FocusTrap`, and the selected `Tab` registers itself in a next tick so it is not immediately in the DOM.
This PR fixes that so that they all play well together.
Fixes: #771
> Ensure focus trap, Tabs and Dialog play well together

- .github/CONTRIBUTING.md
This is just a minor documentation fix that I noticed while reading through the .github/CONTRIBUTING.md file
> Fix typo in .github/CONTRIBUTING.md

- CHANGELOG.md
- packages/@headlessui-react/package.json
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/portal/portal.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
- packages/playground-react/pages/combobox/multi-select.tsx
- packages/playground-react/pages/listbox/multi-select.tsx
- packages/playground-vue/src/components/combobox/multi-select.vue
- packages/playground-vue/src/components/listbox/multi-select.vue
- packages/playground-vue/src/routes.json
- yarn.lock
This PR will add `multiple` values support for both the `Listbox` and `Combobox` components.
You can enable multiple value support by providing an array of items instead of a single value. When the `value` is an array, we automatically switch to multiple value mode.
This has a few implications:
- Underlying aria attributes will be a bit different, but you don't have to worry about this.
- When you are in multiple value mode, then the Listbox/Combobox will stay open when activating items.
- This is to prevent that you have to re-open every time you make a change.
- When you are in multiple value mode, then activating an option will function as a "toggle". So that it is possible to "unselect" a value.
- The value passed to the `v-model` in Vue, and the `onChange` in React will now be an …
> Add `multi` value support for Listbox & Combobox

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR improves upon this PR: #1181
In that PR we ignored syncing when your value was set to `undefined`, that means that if you "reset" your value to `undefined` that the old value was still present in the Input. To fix this, we will always sync (unless we don't have an input field).
This means that your `displayValue` should always return something. It could happen that you have to write this:
*(React example)*
```js
<Combobox.Input displayValue={person => person?.name} />
```
This would have resulted in `"undefined"` in the input, so we will also make sure that `null` and `undefined` values are converted to an empty string (`''`). It's important that we use `?? ''` and not `|| ''`, otherwise values like `0` would be converted to an empty string as well.
> Improve Combobox Input value

- CHANGELOG.md
- package.json
- scripts/build.sh
- scripts/lint.sh
- scripts/resolve-files.js
- scripts/rewrite-imports.js
- scripts/test.sh
- scripts/watch.sh
- yarn.lock
Instead of bundling everything into a single ESM file, we generate every single file as ESM. This is what we did in 1.4.x as well. This in turn should fix the tree-shaking that was broken.
Closes: #1238
Before:
After:
> Fix Tree-shaking support

- CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/src/components/popover/popover.ts
This PR will stop the propagation of `click` events on the Popover Button that is not inside the Popover Panel. We usually have this behaviour for keyboard events and clicks but probably missed this one.
Fixes: #1260
> Stop propagation on the Popover Button

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/hooks/use-focus-trap.ts
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/hooks/use-focus-trap.ts
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
- packages/playground-react/package.json
- packages/playground-react/pages/dialog/dialog.tsx
- packages/playground-vue/package.json
- packages/playground-vue/src/components/dialog/dialog.vue
- yarn.lock
This PR fixes an issue where the outside click behaviour was triggered if you clicked on 3rd party provided components that were portalled to the body.
From a DOM perspective this bug made sense because the 3rd party components are rendered **outside** of the current Dialog and therefore it closes.
This PR should fix that behaviour and it should be possible to interact with 3rd party libraries now.
You can play with it here:
- React: https://headlessui-react-git-fix-third-party-interactions-tailwindlabs.vercel.app/dialog/dialog
- Vue: https://headlessui-vue-git-fix-third-party-interactions-tailwindlabs.vercel.app/dialog/dialog 
Fixes: #432
> Fix incorrect closing while interacting with third party libraries in `Dialog` component

- CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/hooks/use-focus-trap.ts
If you are passing a Ref to a component, you don't get the underlying
DOM node even if you put it on the element manually. The ref will be a
ref to the _component_.
This means that the initialFocusRef can be a DOM element or a Vue
component instance. Resolving it guarantees us to resolve to an
HTMLElement or null but not a component.
> Resolve `initialFocusRef` correctly

- CHANGELOG.md
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
When using a `Dialog`, if a user tabs into an input or textarea element, the default browser behavior of selecting the text is not occurring. Instead the cursor is sent to the end of the input.
This PR resolves this by selecting the text if the element is able to select the text. 
resolves https://github.com/tailwindlabs/headlessui/issues/1271
> Mimic browser select on focus when navigating via `Tab`

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
- packages/playground-vue/src/components/combobox/multi-select.vue
This PR ensures that the first non-disabled `Combobox.Option` will be the active one if no other active option exists.
This should improve the general UX of the `Combobox` component, because now you can search and immediately press <kbd>Enter</kbd> to choose that option instead of searching, pressing <kbd>ArrowUp</kbd> and then pressing <kbd>Enter</kbd>.
Some rules that apply:
- If you have an active option already, that one should stay the active option as long as it can.
- If no active option exists, but a `Combobox.Option` registers itself and _is_ selected, then the first selected option will become the active one.
- If you mosue out, then no active option should exist.
- This will prevent weird jumps/scrolls if you leave the last option with your mouse and it jumps up to make the …
> Ensure that there is always an active option in the `Combobox`

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
If the `activeOptionIndex` is set to `null`, then we default to the very first non-disabled option. This data is _not_ stored in state because if you as the user go to a specific option, then start searching then we will maintain the active option. This means that we have to **update** the `activeOptionIndex` when options are moving around.
While making the first option the active one, we can't store that in state directly otherwise the very first option becomes the active one. If we then inject combobox options _before_ the current one then all of a sudden your active option would jump around a bit.
We don't want this jumping to happen, we want the very first option to be the one that's active no matter which option it is.
Since this is not stored in state, our keydown handler was a bit …
> Fix required double `ArrowDown` requirement

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/keyboard.ts
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/keyboard.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
This PR adds a `nullable` prop to the `Combobox` component which is defaulted to `false`.
If this prop is provided, and you clear the text in the input value, then the `Combobox` option will
be cleared as well. We will do that by calling your `onChange` with `null` in React, or setting the
`v-model` to `null` in Vue.
This feature allows you to "clear" a Combobox value once it is set, whereas otherwise this isn't
possible unless you provide a custom "Unset" `Combobox.Option` or a button to reset the value.
> Implement `nullable` mode on `Combobox` in single value mode

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-react/src/hooks/use-transition.ts
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/src/index.test.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
This PR adds 2 new components:
- `Dialog.Backdrop` (React), `DialogPanel` (Vue)
- `Dialog.Panel` (React), `DialogPanel` (Vue)
The `Dialog.Backdrop` will replace the `Dialog.Overlay` in a backwards compatible way, because the `Dialog.Overlay` will still be available.
If you have a `Dialog` with a lot of content, then you want to scroll the `Dialog`, however in a lot of usage implementations the `Dialog.Overlay` gets in the way, and you will only be able to scroll with your mouse while it's over the panel itself (the typical white area in the center of your screen). You usually can't scroll the overlay (the gray area) so that is not good.
In addition, the scrollbar is typically hidden by the `Dialog.Overlay`, so if your users use the scrollbar itself, they can either not reach it because …
> Add `Dialog.Backdrop` and `Dialog.Panel` components

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/playground-react/pages/combobox/multi-select.tsx
- packages/playground-react/pages/listbox/multi-select.tsx
- packages/playground-vue/src/components/combobox/multi-select.vue
- packages/playground-vue/src/components/listbox/multi-select.vue
This PR requires you to explicitly set the `multiple` prop on the `Listbox` & `Combobox` components if you want `multi-value` support.
This is required if you want to set the value to a **tuple** in `single-value` mode, which was not possible before the `multiple` prop was introduced, because then it resulted in `multi-value` mode instead of `single-value` mode.
---
> **NOTE:** If you are using the `insiders` build AND you are using multiple values, then this will be a breaking change for you. Add the `multiple` prop to your `Listbox` and `Combobox` components that require multi value support and you should be good to go!
> Add explicit `multiple` prop

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/src/components/dialog/dialog.ts
This PR will make sure that the `open` prop of the `Dialog` container has precedence over the open/closed state that's shared internally. This is safe to do because the `open` value internally will already be properly updated with the OpenClosed state if the incoming `open` value was `undefined`.
This fixes a bug where it could happen that a Dialog immediately pops up in a Disclosure Panel even if the `Dialog` has an `open` value of `false`.
Fixes: #1308
> Prefer incoming `open` prop over OpenClosed state

- README.md
- packages/@headlessui-react/README.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/transitions/transition.test.tsx
- packages/@headlessui-vue/README.md
- packages/@headlessui-vue/src/components/popover/popover.test.ts
This removes install instructions for `yarn` just to simplify the READMEs.
There are other tools apart from `yarn`, everyone that uses something else then the default `npm`
will know how to use that tool in particular.
This makes the install instructions a bit more concise instead of adding instructions for all the
tools like `yarn`, `pnpm`, ...
> General cleanup of README files

- CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
Due to the return of the Fragment (for form compatibility) the
attributes will now be pass onto this Fragment instead of the underlying
DOM node. To fix this, we disable the `inheritAttrs` magic, and
passthrough the attributes to the correct component.
Fixes: #1369
> Manually passthrough `attrs` for `Combobox`, `Listbox` and `TabsGroup` component

- CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
This PR fixes hydration related issues with the `Tab` component.
> Fix hydration issue with `Tab` component

- CHANGELOG.md
- packages/@headlessui-vue/src/components/transitions/transition.ts
- packages/playground-vue/package.json
- packages/playground-vue/src/components/dialog/slide-over.vue
- packages/playground-vue/src/routes.json
- yarn.lock
This PR fixes an issue with enter transitions in the Vue `Transition` component. Now the enter
transition will only work after the `show` value has changed OR if the `appear` prop has been
passed.
> Fix enter transitions in Vue

- CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
This PR will ensure that the `DialogPanel` in Vue correctly exposes its ref.
Fixes: https://github.com/tailwindlabs/headlessui/discussions/1401
> Ensure `DialogPanel` exposes its ref

- CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/src/components/popover/popover.ts
This PR removes some unnecessary code that has been handled a different way and by doing that fixes a React 18 compatibility issue where the `Popover` would immediately close if you click anywhere inside of the `Popover.Panel`.
The reason for this is that we used the cleanup function of a `useEffect` to set the `panel` to `null`. In React 18, this will be executed twice therefore the `Panel` gets set to `null` while it didn't have to do that yet.
Fixes: #1407
> Fix closing of `Popover.Panel` in React 18

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/src/components/dialog/dialog.ts
Some external libraries only use `event.preventDefault()` and not `event.stopPropagation()`. This means that the Dialog can still receive an `Escape` keydown event which closes the Dialog.
We can also think about the `Escape` behaviour inside the modal as the "default behaviour" once the Dialog is open. Therefore, we can also check the `event.defaultPrevented` and ignore this event when this is the case.
> Ignore `Escape` when event got prevented in `Dialog` component

- CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
- packages/playground-react/pages/popover/popover.tsx
- packages/playground-vue/src/components/popover/popover.vue
This PR will simplify the `Popover` component by using the same strategy we applied in the
`FocusTrap` component.
This uses sentinel DOM nodes instead of `keydown` event interception and manually trying to focus
the next element. This improves a bunch of subtle bugs because now the browser will handle all of
the Tab related logic. This means that it fixes the following bugs for free:
Fixes: #1215
Fixes: #1140
Fixes: #467
> Simplify `Popover` Tab logic by using sentinel nodes instead of keydown event interception

- CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/src/components/popover/popover.ts
This PR ensures that the popover panel doesn't close if you click on a non-focusable item inside the
popover panel.
This happens if one of the parent items contains a focusable element. For example when using a
Popover inside a Tab component, the `Tab.Panel` has a `tabIndex={0}`. The click even then bubbles and
the `Tab.Panel` now has the focus. Since the focus is "outside" of the `Popover`, the `Popover` now
closes.
This also happens in Gatsby applications where the root Gatsby app has a `tabIndex={-1}` for
accessibility purposes.
Fixes: #1437
> Ensure the `Popover.Panel` is clickable without closing the `Popover`

- packages/playground-react/pages/_app.tsx
- packages/playground-react/pages/_document.tsx
A small <Head> fix for Next.js playground. Supresses the `Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://rsms.me/inter/inter.css")` warning
> Next playground <Head> fix

- CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/src/components/dialog/dialog.ts
The idea is as follow: 
If you currently have a scrollbar, and you open a Dialog then we enable a "Scroll lock" so that you can't scroll in the background behind the modal. We can achieve this by adding a `overflow: hidden;` to the `html`.
The issue is that by doing this, we lose the scrollbar and therefore the page will jump to right because now there is a bit more room.
To account for this, we set a `padding-right` on the `html` of the scrollbarWidth in pixels. This counteracts the visual jump you would see.
The issue with this approach is that there could *still* be a scrollbar once we add the `overflow: hidden`. This can happen if you use new css features like the `scrollbar-gutter: stable;`.
To take this into account, we will measure the scrollbar again after we set the `overflow: …
> Improve "Scroll lock" scrollbar width for `Dialog` component

- scripts/rewrite-imports.js
This PR provides a fix where we only rewrote `import x from './abc'` to `import x from './abc.js'`.
But we also have to do that for standalone `import './abc'` to `import './abc.js'`.
> internal: ensure standalone imports and exports are rewritten as well

- CHANGELOG.md
- packages/@headlessui-vue/src/components/portal/portal.test.ts
- packages/@headlessui-vue/src/components/portal/portal.ts
They will at least not error now. Ideally we would SSR render the content inside the portal but that will be for another day.
Fixes #1429
> Don’t throw when SSR rendering internal portals in Vue

- CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
We "required" the prop to calculate the `ownerDocument`. But if you don't provide a ref, then we
will use the `Popover.Button` to calculate it. If that's not defined, then we can fallback to the
default `document`.
Fixes: #1430
> Make the `ref` optional in the `Popover` component

- README.md
Make this line just a little easier to copy paste.
> Remove fullstop from install instructions

- CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.tsx
This PR will ensure that the `ref` is forwarded to the `Transition.Child` component.
Fixes: #1472
> Ensure the `ref` is forwarded on the `Transition.Child` component

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR allows you to override the `type` on the `Combobox.Input`, we still default it to `text`.
Closes: #1469
> Allow to override the `type` on the `Combobox.Input`

- CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
This PR fixes an issue where the `Popover.Panel` isn't closed correctly if you are using the `focus` prop. This is because the idea behind the `focus` flag is that when the `Popover.Panel` opens the focus is moved inside the `Popover.Panel`. If the focus is moved outside of the `Popover.Panel` then the `Popover.Panel` will close again.
The issue with this is that the moment you click the `Popover.Button` when the `Popover` is open the
the following happens:
1. Focus is moved to the `Popover.Button`.
2. `Popover` will close due to the above.
3. The click event happens on then `Popover.Button`.
4. Which opens the `Popover` again.
This means that you can't close is anymore via click. This PR fixes that issue.
Fixes: #1342
> Ensure the the `<Popover.Panel focus>` closes correctly

- CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/hooks/use-transition.ts
This PR will fix an issue where the `onStop` callback internally is never called if the DOM node
becomes hidden.
This happens when you use the `Transition` component in combination with the `Dialog` component.
When the `Dialog` becomes "hidden", then we unmount everything, however transitions don't seem to
run, end or cancel on hidden DOM nodes. This causes an issue where "hidden" DOM nodes had a pending
transition.
This pending transition prevented `<Transition.Child>` and `<Transition>` components higher up the
tree from unmounting. This in turn resulted in the `Dialog` not completely unmounting properly.
Fixes: https://github.com/tailwindlabs/headlessui/issues/1417
Fixes: https://github.com/tailwindlabs/tailwindui-issues/issues/1215
> Ensure the Transition stops once DOM Nodes are hidden

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
When you press `Escape` in the `Combobox.Input` component then you want 2 things to happen:
- If the combobox is open, then the combobox should close, but the event should not propagate
further. This is to prevent parent Dialog components from closing for example.
- If the combobox is closed, then the event should propagate just like with a normal input.
We only called `event.preventDefault()` and not `event.stopPropagation()`, however a recent bug fix for the Dialog component also checks for `event.defaultPrevented`.
This PR ensures that `Escape` only has special meaning when the Combobox is open, otherwise it is a normal event just like other events.
Fixes: #1506
> Ensure `Escape` propagates correctly in `Combobox` component

- CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This code existed before we had the option to make the first option the
"active" one.
This also contains a bug in the React code where pressing "ArrowDown" in
a closed Combobox opens the combobox and goes to the second item instead
of the first option.
> Remove leftover code in Combobox component

- CHANGELOG.md
- packages/@headlessui-react/src/utils/render.ts
This PR fixes an issue where event handlers with an arity > 1 receives `undefined` as the second
argument instead of the required argument.
One of those examples is the `onDragEnd` handler, it receives an event and `PanInfo` but before this
fix this was always undefined.
Fixes: #1513
> Fix event handlers with arity > 1

- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/hooks/use-transition.ts
We had an issue where an open Dialog got hidden by css didn't properly unmount because the Transition never "finished". We fixed this by checking if the node was hidden by using `getBoundingClientRect`.
Today I learned that just *reading* those values (aka call `node.getBoundingClientRect()`) it for whatever reason completely stops the transition. This causes the enter transitions to completely stop working.
Instead, we move this code so that we only check the existence of the Node when we try to transition out because this means that the Node is definitely there, just have to check its bounding rect.
Fixes: #1503
> Fix transition `enter` bug

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/hooks/use-flags.ts
The `useEvent` is 1 tick too late (due to the update of the callback
happening in useEffect). This isn't a problem for event listeners, but
it is for functions that need to run "now".
We can change the `useLatestValue` hook to do something like:
```diff
export function useLatestValue<T>(value: T) {
let cache = useRef(value)
-   useIsoMorphicEffect(() => {
-     cache.current = value
-   }, [value])
+   cache.current = value
return cache
}
```
But then we are mutating our refs in render which isn't ideal.
Fixes: https://github.com/tailwindlabs/headlessui/pull/1522
> Fix render prop data in `RadioGroup` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/utils/transition.ts
Due to bubbling, the `Transition` component also "finished" when you had
children that uses `transition-colors` for example.
This commit ensures that we only care about transition events related to
the actual DOM node that we defined the transitions on...
Fixes: #1517
> Fix incorrect transitionend/transitioncancel events for the Transition component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.test.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/components/portal/portal.test.ts
- packages/@headlessui-vue/src/components/portal/portal.ts
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
- packages/playground-react/package.json
- packages/playground-react/pages/combinations/tabs-in-dialog.tsx
- packages/playground-react/pages/dialog/dialog.tsx
- packages/playground-react/pages/dialog/scrollable-dialog.tsx
- yarn.lock
This PR improves the outside click behaviour that caused a bunch of problems in various areas. The code is also way simpler so hopefully it stays that way 🤞 
Fixes: #1490
Fixes: https://github.com/tailwindlabs/tailwindui-issues/issues/1216
> Improve outside click of `Dialog` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
When a page has a component like `<Menu>` and and `<iframe>` on the page you could click inside the iframe. These click events are not delivered to the `Window` that contains the iframe so menus, dialogs, etc will not close. However, when clicking or focusing anything inside the iframe the Window receives the `blur` event and `document.activeElement` changes to the iframe itself. We can use this to detect a click or change in focus targeted at an iframe. We're also sure to scope this so if you have an iframe _inside_ your Menu, Listbox, etc… that it doesn't close.
Fixes #707
> Detect outside clicks from within `<iframe>` elements

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
This PR fixes an issue with our Dialog components in Vue and server side rendering.
Right now, we will only render the Dialog component on the client and not on the server.
Once we figure out the correct way of server side rendering the Dialog then we can revisit this
behaviour. But for now, this at least fixes incorrect SSR and hydration issues where closing the
Dialog looks like it is still there even though that's the static SSR version of the Dialog.
Fixes: https://github.com/tailwindlabs/tailwindui-issues/issues/1223
> Only render the `Dialog` on the client

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR is a continuation of #1572 with some improvements while keeping the original author in the
commit.
Closes: #1572
> Improve Combobox input cursor position

- .github/workflows/main.yml
- package.json
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- yarn.lock
This PR fixes an issue where using your arrow keys on the Tab component could scroll the page, this
is obviously not something that we want.
`event.preventDefault()` to the rescue!
> Fix scrolling issue in `Tab` component when using arrow keys

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/utils/dom.ts
It seems like there is a bug trying to get the dom element from a Vue component. I got this problem trying to use a custom button to open a Menu.
Here's a reproduction of the issue: https://stackblitz.com/edit/vitejs-vite-rgp3jk?file=src/App.vue
I reproduced the error in the `playground-vue` as well to test my fix.
What I saw debugging the problem in my app is that `ref.value` is actually a Proxy. That's why doing `'$el' in ref.value` returns false, but doing `ref.value.$el` actually works. I guess it has to do with the way that Vue references component instances, but I think this should be a safe refactor.
Possibly related to https://github.com/vuejs/core/issues/6137
> Fix getting Vue dom elements

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR fixes an issue where `cmd+backspace` didn't work properly in the Combobox component when
using the `nullable` mode.
Fixes: #1612
> Ensure `CMD`+`Backspace` works in nullable mode for `Combobox` component

- packages/@headlessui-tailwindcss/CHANGELOG.md
- packages/@headlessui-tailwindcss/jest.config.cjs
- packages/@headlessui-tailwindcss/jest.setup.js
- packages/@headlessui-tailwindcss/src/index.test.ts
- packages/@headlessui-tailwindcss/src/index.ts
This PR fixes the bracket order in the `not` variants for `@headlessui/tailwindcss`.
Also setup some tests to verify that the correct css is being generated.
> Fix bracket order of `not` variants

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-react/src/internal/stack-context.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/src/internal/stack-context.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
Right now we use the `click` event for "outside" clicks to close the dialog. However, this is a problem in two situations:
1. If a user opens a dialog during the mousedown or mouseup events the dialog will end up closing because the dialog will get mounted in the DOM before the click event is delivered. This causes it to see the click event as an outside click and fires its close event.
2. If you started a click inside the dialog (e.g. when selecting text) and it ended outside the dialog the click event is delivered _outside_ which we saw as an outside click when it shouldn't be considered as such.
We can fix both of these with a small tweak to `useOutsideClick`:
- Record the element that's clicked in the `mousedown` capture phase
- If we _don't_ have a recorded element then that means …
> Adjust outside click handling

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
> Resync input when display value changes

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR fixes an issue where the `Tabs` component behaves incorrectly if it is used in a controlled way. If you are controlling the `Tabs`, then clicking on the tabs should fire the `onChange`/`@change` but it should not actually switch tabs, you are in charge of that.
Fixes: #1509
> Ensure controlled `Tabs` don't change automagically

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
In React we weren't using the current `show` state to determine the initial "visibility" of transitions which meant that an mounted but hidden Transition + a mounted but hidden `Dialog` causes the document scroll lock to be applied when it shouldn't be because it's not being shown.
Just something we missed ¯\\\_(ツ)\_/¯ 
Fixes #1676
> Don't scroll lock when a Transition + Dialog is mounted but hidden

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-document-event.ts
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/hooks/use-document-event.ts
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
- packages/playground-vue/src/components/dialog/dialog.vue
This PR fixes an issue where the outside click wasn't working properly for Safari on iOS when using
the Vue version of Headless UI
Fixes: #1707
> Improve outside click on Safari iOS

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/utils/render.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/utils/render.ts
This will ensure that an actual event is passed before checking the
`event.defaultPrevented`.
For React, we also have to make sure that we are not dealing with a
SyntehticEvent.
Thanks @Mookiepiece!
Closes: #1711
> Improve event handler merging

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.test.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/playground-react/pages/_app.tsx
This PR fixes an issue where the page is scrolled down before opening a Dialog. 
This is because we tried to focus the first focusable element within the dialog before any
transition happens or whatsoever, this means that technically the dialog is still at the very bottom
of the page (because we render it at the end of the `document.body` via a Portal). 
Focusing the element causes the browser to scroll the page down.
With the `queueMicroTask` we can delay that just enough to let the browser do its job.
Fixes: #1708
> Fix incorrect scrolling to the bottom when opening a `Dialog`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
This PR fixes an issue where the `by` comparison wasn't correctly used in the Listbox and Combobox
components when using `multiple` mode.
Fixes an issue reported by @thoresuenert in https://github.com/tailwindlabs/headlessui/discussions/1682#discussioncomment-3221242
> Ensure `by` comparison is used in `multiple` mode

- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
> Don’t overwrite `element.focus` on popover panels

- scripts/build.sh
- scripts/rewrite-imports.js
This PR improves the compatibility of the `NodeNext` module resolution in TypeScript 4.7.
We already rewrote the imports to include the `.js` file, but we only did this for generated `.js`
files and not for generated `.d.ts` files.
Ideally we don't have to do this rewrite on build files at all, and that is possible if we add the
`.js` files to the actual source files. However this has some (annoying) issues:
- We then have to make sure that all tooling (Next.js, Jest, ...) works with `.js` files.
- We will introduce _a lot_ of changes, and this will cause annoying merge conflicts.
- We will have to make sure that we always think about adding the `.js` file extension in the imports.
Instead, for now, rewriting imports on `.d.ts` files as we already do with `.js` file should do the trick, …
> Improve TypeScript 4.7 `NodeNext` compatibility

- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.test.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/hooks/use-controllable.ts
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.test.tsx
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/hooks/use-controllable.ts
- packages/playground-react/pages/combinations/form.tsx
This PR allows our form related components (Switch, RadioGroup, Listbox and Combobox) to be both controlled and uncontrolled (new).
This has the benefit that you don't have to do any wiring yourself if you just want to choose values from a know list and use the good old `<form>` element to submit your values.
Add a `name` prop to those components (more info: Listbox example https://headlessui.com/react/listbox#using-with-html-forms) and you should be good to go!
> Make form components uncontrollable

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
On mobile this gives a bit of annoying results where after choosing an option, the keyboard is shown again because the input is focused again.
Fixes: #1555
> Improve `Combobox` re-opening keyboard issue on mobile

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
Currently to use the `close` function within a `button` I need to invoke a new function:
```tsx
<button onClick={() => close}>...</button>
```
It would be nice to be able to just call the close function directly from the `onClick` of an element so that we are not invoking this new function every time we call the component:
```tsx
<button onClick={close}>...</button>
```
---
The reason for this is that the types for `close` and `onClick` do not quite line up. The `button` requires an `MouseEventHandler` type from `React`
This PR allows for that type to be added to the `close` function so that the example above will be valid.
> fix: adds the MouseEventHandler type to close in Popover

- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
Instead of React.Fragment use Fragment since it is already imported by name and it fixes an issue with Vite3+React+new JXS transform, see https://github.com/tailwindlabs/headlessui/issues/1733
> fixes tailwindlabs/headlessui#1733

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
This PR fixes an issue where the `Disclosure.Panel` is not properly linked to the `Disclosure.Button` anymore when using the `static` prop.
Fixes: #1747
> Ensure `Disclosure.Panel` is properly linked

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR improves the UX when using multiple value mode for the `Combobox` component. Now when
pressing `<Tab>` the active item won't be selected/unselected and you have to explicitly select it
via `<Enter>` or clicking/tapping.
Fixes: #1628
> Only select the active option when using "singular" mode

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/types.ts
- packages/playground-react/pages/combobox/multi-select.tsx
The `Combobox` types weren't super well defined and the were especially confusing in combination with the `nullable` and `multiple` props.
Now given the `multiple` and/or `nullable` props we ensure that the types for the `value`, `defaultValue`, `onChange`, `by`, render prop, ... are all correct.
You will also be able to easily tell which type to use instead of inferring it by doing something like this:
```ts
<Combobox<ExplicitTypeHere>
value={...}
onChange={...}
...
>
...
</Combobox>
```
Fixes: #1702
> Improve the types of the `Combobox` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.test.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/hooks/use-transition.ts
- packages/@headlessui-react/src/test-utils/execute-timeline.ts
This PR should fix a handful of issues where `leave` transitions weren't properly cleaning up
the DOM resulting in sometimes UI pages that feel "stuck", especially if you are using a `Dialog`
component that is technically still open now due to incorrect unmounting.
A lot of the `Dialog` components use `fixed inset-0` which renders a div for the backdrop but since
that is sometimes still there and sitting on top of all other content, this results in the stuck
pages.
This PR should improve that, and therefore also fix some open issues:
Fixes: #1557
Fixes: #1638
Fixes: #1364
Closes: #1585 (this is a big, but incomplete rewrite of the `Transition` component; We can pick this up later if needed)
> Fix `Transition` component's incorrect cleanup and order of events

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/utils/transition.ts
This PR will further improve a bug that happens at random on my machine, but can reproduce it when I
slowdown my CPU tremendously (or join a Zoom call...).
Fixes: #1557 (hopefully)
> Ensure enter transitions work when using `unmount={false}`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
> Allow the by prop (as a string) to handle null values

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
I should've checked these too…
> Fix nullable by prop for combobox and radio group

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.test.tsx
- packages/@headlessui-react/src/utils/render.ts
When a higher-level component (like `Transition`) provides a `ref` to its child component, then it will override the `ref` that was potentially already on the child.
This will make sure that these are merged together correctly.
Fixes: #985
> Fix `ref` stealing from children

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
This PR will expose the current `value` via the render prop / slot, which will be useful when using
uncontrolled components.
> Expose the `value` from the `Combobox` and `Listbox` components render prop

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/utils/disposables.ts
- packages/@headlessui-react/src/utils/platform.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/utils/disposables.ts
- packages/@headlessui-vue/src/utils/platform.ts
- packages/playground-react/pages/dialog/scrollable-page-with-dialog.tsx
- packages/playground-vue/src/components/dialog/dialog.vue
This PR improves the scroll lock on iOS devices.
Fixes: #949
> Improve `scroll lock` on iOS

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
The `forceRerender` is necessary when the `Tab` is rendered but the `Panel` isn't rendered yet (or vice versa) so that we can apply the correct attributes to link them together (e.g.: `aria-controls`).
However, if you are using a render prop, the contents is technically a bit different and it seems like we are calling the `forceRerender` while React is already updating which means that it has to update again, and again, and again.
Scheduling the `forceRerender` for the next frame allows React to complete the update and then we can `forceRerender` outside of the already going on update.
> Fix maximum call stack size exceeded error on `Tab` component when using `as={Fragment}`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.ts
This isn't super ideal, but just preventing the default behavior on the
entire document while `touchmove`-ing isn't ideal either because then
you can't scroll inside the dialog or on the backdrop if your dialog
panel is larger than the viewport.
Again, this is not 100% correct, but it is better because you will be
able to scroll the dialog, and not the body.
Fixes: #1831
> Improve iOS scroll locking

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
What it says on the tin. This should work already for `<button>` but does not because of a react bug.
> Add `<fieldset disabled>` check to radio group options in React

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
This ensures that whenever you insert or delete tabs before the current
tab, that the current tab stays active with the proper panel.
To do this we had to start rendering the non-visible panels as well, but
we used the `Hidden` component already which is position fixed and
completely hidden so this should not break layouts where using flexbox
or grid.
Fixes: #1834
> Ensure `Tab` order stays consistent, and the currently active `Tab` stays active

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
Ensure `Combobox.Label` is properly linked with `Combobox.Input` and `Combobox.Button`, even when rendered after these components.
We do require an additional render, but now it happens automatically for you, before that you _had_ to make a change yourself in order to trigger a re-render and "fixing" the missing link.
Fixes: #1836
> Ensure `Combobox.Label` is properly linked when rendered after `Combobox.Button` and `Combobox.Input` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
This was necessary to ensure the `Panel` and the `Tab` were properly
connected with eachother because it could happen that the `Tab` renders
but the corresponding `Panel` is not the active one which means that it
didn't have a DOM node and no `id` attached.
Whenever new `Tab` became active, it rerendered but the `Panel` wasn't
available yet, after that the `Panel` rendered and an `id` was available
but the actual `Tab` was already rendered so there was no link between
them.
We then forced a re-render because now the `Panel` does have a DOM node
ref attached and the `aria-labelledby` could be filled in.
However, in #1837 we fixed an issue where the order of `Tab` elements
with their corresponding `Panel` elements weren't always correct. To fix
this we ensured that the `Panel` always …
> Remove `forceRerender` from `Tab` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR fixes an issue where `static` Tab Panels didn't take the `static` prop into account when
rendering the "hidden" panel (to guarantee tab order and matching tab panels).
Fixes: #1323
> Ensure we handle the `static` prop in `Tab.Panel` components correctly

- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
When the combobox box is given a v-model ref that is `undefined` we do not call `displayValue` and can end up displaying the string `undefined`. This is actually a bug in Vue itself (https://github.com/vuejs/core/issues/5032) but we can work around this by passing a dummy ref that has a defined value. This allows `immediate` to work as expected.
Fixes #1861
> Fix use of `undefined` and `displayValue` in Combobox

- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
This PR improves the detection of being inside a `Portal`/`Teleport`, by checking some heuristics.
Fixes: #1839
> Improve `Portal` detection for `Popover` components

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/utils/render.ts
This PR fixes an issue where if you render no children at all (probably user error because all our components require at least some form of child) the component crashes with an error. This PR ensures that `children` are always an error so that the issue should not occur anymore.
That said, if you just render something like:
```
<Menu></Menu>
```
It won't crash anymore, but it will also not work as expected since the `MenuButton`, `MenuItems` and `MenuItem` components are missing.
Fixes: #1884
> Fix crash when `children` are `undefined`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.ts
The "change on focus" was an incorrect implementation detail that made
it a bit easier but this causes a problem as seen in #1858.
If you want to conditionally check if you want to change the tab or note
(e.g. by using `window.confirm`) then the focus is lost while the popup
is shown. Regardless of your choice, the browser will re-focus the Tab
therefore asking you *again* what you want to do.
This fixes that by only activating the tab if needed while using arrow
keys or when you click the tab (not when it is focused).
Fixes: #1858
> Fix `Tab` incorrectly activating on `focus` event

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
This PR fixes a crash when using `as={Fragment}` on the `Popover.Button` component.
When you use `as={Fragment}` an unmount and remount can happen. This means that the `ref` gets called with `null` for the unmount and `HTMLButtonElement` for the mount.
This keeps toggling which results in an infinite loop and eventually a Maximum callback size exceeded issue.
This ensures that we only set the button if we have a button.
Fixes: #1888
> Fix `<Popover.Button as={Fragment} />` crash

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
This PR exposes a `close` function for the `Menu` and `Menu.Item` components so that you can
manually close it in case the automatic closing isn't working (due to 3rd party tools implementing
`e.preventDefault()`)
---
Longer version:
The `Menu` will already automatically close if you invoke the `Menu.Item` (which is typically an `a` or a `button`). However you have control over this, so if you add an explicit `onClick={e => e.preventDefault()}` then we respect that and don't execute the default behavior, ergo closing the menu.
The problem occurs when you are using another component like the Inertia `Link` component, that does have this `e.preventDefault()` built-in to guarantee SPA-like page transitions without refreshing the browser. Because of this, the menu will never close (unless you …
> Expose `close` function for `Menu` and `Menu.Item` components

- .github/workflows/main.yml
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/hooks/use-controllable.ts
- packages/@headlessui-react/src/test-utils/suppress-console-logs.ts
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
We currently don't handle changes to/from `undefined`. However this is _okay_. If you specify a value of `undefined` you're saying you want an uncontrolled component. This follows React's own conventions for inputs for example.
We'll warn when changing between a controlled and uncontrolled component as this can be considered an implementation error.
Fixes #1177
> Warn when changing `Combobox` between controlled and uncontrolled

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
This PR is a rebased continuation of #1913 which also added the same fix for the Vue implementation.
Closes: #1913
> Fix `useOutsideClick`, add improvements for ShadowDOM

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/utils/render.ts
This is essentially how the internal implementation of `<component>` works. This works even for element VNodes.
The old implementation wasn't _wrong_ but this normally lets Vue defer rendering of the slot (or even allow it to skip it in some cases). Given that we're calling the slot function ourselves that's not really the case. However, there's a potential future perf optimization where we only do this when `as="template"` (which we still still need because we have to flatten the VNode list for error checking)
Fixes #1892
> Pass default slot instead of raw children to components

- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
While trying to create a custom `RadioChipGroup` component based upon Headless UI’s `RadioGroup`, I’ve noticed that `defaultValue` can’t be set to `T` as it clashes with `defaultValue` as defined by React.
This PR aims to resolve that problem by explicitly omitting `defaultValue` from the inherited props.
> fix(RadioGroup): defaultValue type definition

- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.ts
Related issue: https://github.com/tailwindlabs/headlessui/issues/1849
> fix: the order of compositionend events varies by browser

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/package.json
- packages/@headlessui-react/src/index.ts
- yarn.lock
This should improve the error messages when using Headless UI in a Next.js 13+ repo instead of getting a cryptic error message that `createContext` doesn't exist.
> Add `client-only` to mark everything as client components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.test.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.test.tsx
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/playground-react/pages/combinations/form.tsx
- packages/playground-vue/src/components/combinations/form.vue
This PR fixes an issue where the form-like components (`Listbox`, `Switch`, `RadioGroup` and `Combobox`) didn't reset its value to the `defaultValue` when the parent `<form>` received a `reset` event.
This PR also includes some refactoring for those components so that the change itself was a bit easier to apply.
Fixes: #1950
> Reset form-like components when the parent `<form>` resets

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/popover/popover.ts
This PR fixes an issue where the `Popover` component would crash if the `window` received focus. This happened becaues we are checking based on the `event.target` if it is still within the `Popover.Panel` or not using the `node.contains(event.target)` method. However, that doesn't support `window` as a value.
Fixes: #2018
> Ensure Popover doesn't crash when `focus` is going to `window`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
While testing with a normal input, the Home and End keys don't do
anything on their own, so therefore using them to go to the first or
last item respectively is still a good solution.
However, shift+home and shift+end will do _something_, it will select
the text in the input.
Fixes: #2022
> Ensure `shift+home` and `shift+end` works as expected in the `Combobox.Input` component

- packages/@headlessui-tailwindcss/CHANGELOG.md
- packages/@headlessui-tailwindcss/package.json
- yarn.lock
This PR should fix an issue where the insiders build was used inside the `dependencies` section of
your `package.json`. We have a `peerDependency` for it (so that your installed version wins).
We moved the `tailwindcss` dependency to `devDependencies` so that we can still use it in our own
tests.
Fixes: #2039
> Move `tailwindcss` to `devDependencies`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/transitions/transition.test.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/playground-react/pages/combobox/combobox-with-pure-tailwind.tsx
- packages/playground-vue/src/components/combobox/combobox-with-pure-tailwind.vue
This PR improves the syncing of the `Combobox.Input` value.
Syncing of the input should happen when the value changes internally or externally
I also got rid of the manually dispatching of the change event if the value changes from internally.
I think the correct mental model is:
- That the `Combobox.Input` value should change if the selected value changes from the outside (props) or from the inside.
- Note: It should _not_ do that if you are currently typing (once you choose a new value it will re-sync, once you reset (escape / outside click) it will also sync again).
- The `onChange`/`onInput` of the `Combobox.Input` itself should only be called if you as the user type something. Not when the value is "synced" based on the selected value.
The manual dispatching of events tried to solve …
> Improve syncing of the `Combobox.Input` value

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
This PR fixes a crash where using `multiple` mode in the `Listbox` or `Combobox` component resulted
in a crash. Normally even if nothing is selected an empty array should be used for the value: `[]`.
However, these components can be used as uncontrolled components where the `value` is not passed at
all. This PR fixes that.
Fixes: #2057
> Fix crash when using `multiple` mode without `value` prop (uncontrolled) for `Listbox` and `Combobox` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.tsx
This only happens on the server when `show=true` and `appear=true`. This will guarantee that the `class` is already set to the correct value before the transition happens.
It worked before if you moved your classes from `enterFrom` to `className` because that prop was SSR'd.
Fixes: #2012
> Apply `enter` and `enterFrom` classes in SSR for `Transition` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/description/description.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/label/label.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/description/description.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.ts
- packages/@headlessui-vue/src/components/label/label.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR allows you to pass your own `id` to every component (where it makes sense).
Added @mgcrea  as a co-author because this is sort of a continuation of their PR: #2020 
Fixes: #2048
> Allow passing in your own `id` prop

- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
This PR adds `null` as a valid TypeScript type for the `Listbox` and `Combobox` components. This was
already the case for the React version.
Fixes: #2063
> Add `null` as a valid type for Listbox and Combobox in Vue

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR improves the SSR for Vue so that the first `Tab` and `TabPanel` are rendered on the server. If a custom `defaultIndex` is provided, then that will be used instead.
Fixes: #1479
> Improve SSR for Tabs in Vue

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/utils/transition.test.ts
- packages/@headlessui-react/src/components/transitions/utils/transition.ts
- packages/@headlessui-react/src/hooks/use-transition.ts
This PR fixes an odd issue where the `transitioncancel` event was fired on Android devices and the `transitionend` event was never fired. Therefore the `Transition` component was never "done", which in turn means that the `Dialog` never unmounted because the internal `OpenClosed` state didn't change yet.
Removing the `transitioncancel` event handling altogether fixes this issue. This ensure that it now works on Android and still works on Safari, Chrome, iOS Safari, ...
The good part is that we didn't really do anything with the `transitioncancel` event anyway, we just removed all the active listeners.
Fixes: #2032
> Fix `Dialog` unmounting problem due to incorrect `transitioncancel` event in the `Transition` component on Android

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
Fixes #2078
cc @RobinMalfait I remember you doing something with shadow roots at one point. I've done a bunch of testing and this looks like it works in all scenarios. Gonna merge this is all tests pass but figure I'd tag you for visibility.
It properly handles:
- Open shadow roots
- Closed shadow roots
- Clicks from shadow roots inside the panel (keeps dialog open)
- Clicks from shadow roots outside the panel (closes the dialog)
> Allow clicks inside dialog panel when target is inside shadow root

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
It regressed in the sense that it now uses `displayValue` for the
`defaultValue` as well, but if nothing is passed it would crash.
Right now, it makes sure to only run the displayValue value on the
actual value and the actual default value if they are not undefined.
Note: if your displayValue is implemented like `(value) => value.name`,
and your `value` is passed as `null`, it will still crash (as expected)
because then you are in charge of rendering something else than null. If
we would "fix" this, then no value can be rendered instead of `null`.
Fixes: #2084
> Fix regression where `displayValue` crashes

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR should simplify the calculation of the `displayValue`, regardless of whether it is used in
the same or a different render tree.
The idea is that the `displayValue` (the text that should be shown in the `Combobox.Input`) is
always calculated, but only applied when it is safe to apply. These rules are:
- When a user is **not** typing in the input field, it is safe to update the input value based on the selected option(s).
- The value can be updated when:
- The `value` is set from outside of the component.
- The `value` is set when the user uses their keyboard (confirm via enter or space).
- The `value` is set when the user clicks on a value to select it.
- The value will be reset to the current selected option(s), when:
- The user is _not_ typing (otherwise you will loose your …
> Fix `displayValue` syncing when `Combobox.Input` is unmounted and re-mounted in different trees

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/utils/disposables.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/utils/disposables.ts
This PR further improves scroll locking on iOS.
Instead of using the "simple" hack with the `position: fixed;` implemented in #1830 we now went back to the `touchmove` implementation we used before.
The `position: fixed;` causes some annoying issues. For starters, on iOS you will now get a strange gap (due to safe areas). Some applications also saw "blank" screens based on how the page was implemented.
We also saw some issues internally, where clicking on a link that changes the scroll position on the "main" page from within the Dialog didn't work properly.
Think about something along the lines of:
```html
<a href="#interesting-link-on-the-current-page">Interesting link on the page</a>
```
This doesn't work becauase the page is now fixed, and there is nothing to scroll...
Instead, we now …
> Improve scroll locking on iOS

- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
This PR improves the `aria-haspopup` attribute, which should now contain the corresponding role instead of just true or false. The `aria-haspopup="true"` is considered a `menu` now.
Context: https://w3c.github.io/aria/#aria-haspopup
Fixes: #2099
> Update `aria-haspopup` to use the correct role as the value instead of a boolean

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/tabs/tabs.ssr.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/hooks/use-id.ts
- packages/@headlessui-react/src/hooks/use-iso-morphic-effect.ts
- packages/@headlessui-react/src/hooks/use-server-handoff-complete.ts
- packages/@headlessui-react/src/utils/env.ts
- packages/@headlessui-react/src/utils/owner.ts
- packages/@headlessui-react/src/utils/ssr.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ssr.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/hooks/use-document-event.ts
- packages/@headlessui-vue/src/hooks/use-event-listener.ts
- packages/@headlessui-vue/src/hooks/use-window-event.ts
- packages/@headlessui-vue/src/utils/env.ts
- packages/@headlessui-vue/src/utils/owner.ts
- packages/@headlessui-vue/src/utils/ssr.ts
We currently use unique IDs to figure out what tabs should be visible. This works fine in React 18 but not in React 17 where `useId` doesn't exist. We have our own `useId` hook but it doesn't work with SSR because React internals don't provide necessary information across the client and server to determine a stable ID. (Technically the client _can_ but the server cannot). The best fix for this is really to upgrade to React 18 and all these problems disappear.
So we've tweaked our setup a bit to work better with React 17 SSR. The main problems here are:
1. Testing this is very difficult hence some of the changes I've had to make.
2. It is not possible to make this work with Strict Mode in React. Unfortunately, due to the double render of child components, counters held in context of parent …
> Fix SSR tab rendering on React 17

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/hooks/use-tracked-pointer.ts
- packages/@headlessui-vue/src/utils/render.ts
This PR fixes an issue where `disabled="false"` was incorrectly forwarded to the underlying DOM
node, which could break some projects if some CSS sets `[disabled] { }` because this also matches
`disabled="false"`
Fixes: #2134
> Ensure `disabled="false"` is not incorrectly passed to the underlying DOM Node

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR fixes a bug where if you are using your arrow keys after you re-ordered the tabs that the next/previous tab is the incorrect one. This PR ensures that the previous / next values are the correct ones instead of the "old" values before the order change happened.
Fixes: #2131
> Fix arrow key handling in `Tab` (after DOM order changes)

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
This PR fixes a false positive warning when using multiple `<Popover.Button>` components. This warning should only happen when you use multipel `<Popover.Button>` components **outside** of the `<Popover.Panel>`, but it also got logged when you used multiple `<Popover.Button>` components **inside** the `<Popover.Panel>` component.
This last bit is allowed, and it is a quick short hand to make closing the `<Popover>` a bit easier: https://headlessui.com/react/popover#closing-popovers-manually
Fixes: #2143
> Fix false positive warning about using multiple `<Popover.Button>` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
This PR fixes an issue where using your `tab` key went to the incorrect element if your `Popover.Panel` doesn't contain any focusable elements.
We made the assumption that the `Popover.Panel` always had at least 1 focusable element, but that's not always the case. This PR makes sure that you can go to the next/previous elements correctly.
Fixes: #2112
> Fix `Tab` key with non focusable elements in `Popover.Panel`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
This PR fixes a false positive in the `Popover.Button` warning in React 17 due to the suboptimal `useId` hook implementation we have as a fallback for the real `useId` hook.
It replaces the `useId` result with a symbol just for tracking the `Popover.Button`. This value doesn't change over time (whereas the `useId` value is patched after the first render, resulting in incorrect values).
Fixes: #2154
> Fix false positive warning when using `<Popover.Button />` in React 17

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/portal/portal.tsx
This PR fixes a crash when calling `removeChild` with a value other than a `Node`.
Fixes: #2151
> Fix `failed to removeChild on Node` bug

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.ssr.test.tsx
- packages/@headlessui-react/src/components/transitions/transition.ssr.test.tsx
- packages/@headlessui-react/src/test-utils/ssr.tsx
- packages/@headlessui-react/src/utils/render.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.ssr.test.ts
- packages/@headlessui-vue/src/components/transitions/transition.ssr.test.ts
- packages/@headlessui-vue/src/components/transitions/transition.ts
- packages/@headlessui-vue/src/test-utils/ssr.ts
Fixes #2167
@RobinMalfait does this feel like the right fix?
> Don’t overwrite classes during SSR when rendering fragments

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR improves the Combobox because there are some differences compared to the Listbox that we didn't properly account for.
Big thanks to @afercia for providing us with a wonderful issue report that talks about the differences.
Edit (24/01/2023): Going to merge this PR with partial fixes but not _everything_. This PR will fix the following items:
- Add the missing `aria-autocomplete` attributes
- Remove the unnecessary `aria-activedescendant` on the `Combobox.Options` (it is only required on the `Combobox.Input`) 
- Implement a fix to improve Safari & VoiceOver combination, where opening the Combobox doesn't always trigger VoiceOver properly. This PR will that.
For the `aria-selected` prop it is a bit confusing to apply it based on the `visual` state only which means that there is no …
> Improve `Combobox` accessibility

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
This PR fixes a crash when the `FocusTrap` is blurred and the `relatedTarget` is _not_ and `HTMLElement`.
I was assuming that this was always an `HTMLElement` or `null` but that's not the case. Just using `e.relatedTarget` shows that `dataset` is not always available.
Fixes: #2196
> Fix crash when reading `headlessuiFocusGuard` of `relatedTarget` in the `FocusTrap` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.test.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.test.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
This PR fixes an issue where the focus was not trapped inside the `Dialog` if there was only 1 focusable element. This was because we skipped the current active element and that resulted in no focusable elements and the `tab` just continued to the next focusable element that it found.
Fixes: #2166
> Fix `FocusTrap` in `Dialog` when there is only 1 focusable element

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR ensures that underflowing or overflowing the `selectedIndex` always wraps around so that we
don't end up in a situation where the `selectedIndex` maps to _nothing_.
Fixes: #2211
> Improve `Tabs` wrapping around when controlling the component and overflowing the `selectedIndex`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR adds the ability to override the `tabIndex` of the `Tab.Panel`.
Right now the `Tab.Panel` will always be focusable this allows assistive technology to know that the moment you press <kbd>tab</kbd> that you are in a `tabpanel` container.
However, it can be that your `Tab.Panel` only consists of focusable elements (like links, buttons, ...), which means that you have to <kbd>tab</kbd> twice to get to the first focusable element. Sometimes you don't want this behaviour and just want to go straight to the first item, even if this means that we potentially skip elements (like paragraphs, images, ...).
- Keep the current implementation, this will require you to <kbd>tab</kbd> twice. But assistive technology will still know the proper boundaries.
- Automatically focus the first focusable …
> Allow setting `tabIndex` on the `Tab.Panel`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.ts
We added better support for shadow roots being valid containers for the `Dialog` component in #2079. This means that if you have a 3rd party (or 1st party) tool that uses the shadow DOM, then the `Dialog` used to close when interacting with those items.
This was solved by @thecrypticace in the #2079 PR.
But I found that there is a bug here with one of these:
- Clicks from shadow roots inside the panel (keeps dialog open)
- Clicks from shadow roots outside the panel (closes the dialog)
There is an issue with the Grammarly extension that injects a shadow root component inside the `Dialog.Panel`. Yet, clicking on it closes the `Dialog`. This issue occurs on Campsite for example (by @brianlovin).
I can make it work by _always_ allowing shadow roots with (before checking all the allowed …
> Fix `shadow-root` bug closing `Dialog` containers

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.ssr.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/test-utils/ssr.tsx
- packages/@headlessui-react/src/utils/stable-collection.tsx
Here I've reworked the tab and panel counting mechanism to:
1. Use `Symbol()` when internals aren't available (only in SSR and prod builds where double rendering does not happen)
2. Use a generated key based on the position of the Tab in the React Virtual DOM tree when internals are available. (In dev builds whether or not Strict Mode is enabled)
The reason for this is that React’s double rendering in strict mode in development makes SSR + hydration **impossible** without reaching into internals. We reference the current fiber, walk up the tree of fibers, use the position of each fiber in its list of siblings to generate the key, and then use that as a "stable" reference. It is unfortunate that we have to do this at all but React doesn't give us the ability to do this using public API. …
> Fix SSR tab hydration when using Strict Mode in development

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/disclosure/disclosure.test.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/utils/start-transition.ts
This PR fixes an issue where you get an error when using the `Disclosure` component:
```
This Suspense boundary received an update before it finished hydrating
```
This is an annoying error because as far as I can tell it doesn't break anything really. But, let's
get rid of the error by wrapping the state change that happens at render (it happens in a `ref={(el) => setPanelElement(el)}`) using a `startTransition`.
Note: this is only available in React 18, so in React < 18 we will use a no-op fallback.
Fixes: #2233
> Fix "This `Suspense` boundary received an update before it finished hydrating" error in the `Disclosure` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/description/description.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/label/label.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/hooks/use-event.ts
- packages/@headlessui-react/src/hooks/use-id.ts
- packages/@headlessui-react/src/internal/focus-sentinel.tsx
- packages/@headlessui-react/src/internal/open-closed.tsx
- packages/@headlessui-react/src/internal/portal-force-root.tsx
- packages/@headlessui-react/src/internal/stack-context.tsx
- packages/@headlessui-react/src/utils/start-transition.ts
We use named imports, but we have to import `React` itself as well for JSX because it compiles to `React.createElement`. We could get rid of our own JSX and use it directly, or we can use this `import * as React from 'react'` syntax.
This fixes an issue for people using `allowSyntheticDefaultImports: false` in TypeScript.
Fixes: #2117
> Use the `import * as React from 'react'` pattern

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
This PR will fix a crash:
```
TypeError: Cannot read properties of null (reading 'isSelected')
```
This is becuase:
Initially when the `dataRef` is created, then the `current` value is going to be `null`. We didn't properly encode this in the types. Now that we do, it exposed some places where this was used incorrectly (because we assumed it was always defined).
Fixes: #2253
> Ensure we handle `null` dataRef values correctly

- packages/@headlessui-react/src/components/transitions/transition.test.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/transitions/transition.test.ts
- packages/@headlessui-vue/src/components/transitions/transition.ts
> Don’t fire `afterLeave` event more than once for a given transition

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
This PR fixes a misplacement of the `aria-multiselectable` aria attribute.
I couldn't find evidence why we originally put it on the `[role="combobox"]` element, but I think this was because we started from the `Listbox` component as a starting point.
I also couldn't find evidence why we _should_ put it on the `[role="combobox"]` itself. Looking at the best practices they mention the `aria-multiselectable` attribute, and that it should be used in combination with some `role`s, such as the `listbox` role. https://w3c.github.io/aria/#aria-multiselectable
Testing it in the browser with VoiceOver: This does indeed improve the information that you get from VO. Luckily all other functionality is exactly the same.
Fixes: #2270
> Move `aria-multiselectable` to `[role=listbox]` in the `Combobox` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/utils/platform.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/utils/platform.ts
This PR ensures that you can re-use your keyboard navigation on desktop after using the mouse.
Except on mobile devices (ideally devices using a virtual keyboard), so that the virtual keyboard won't be triggered every single time we re-focus that input field.
Fixes: #2268
> Re-focus `Combobox.Input` when a `Combobox.Option` is selected

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR fixes an issue where unmounting the active `Combobox.Option` results in strange keyboard behaviour.
Unmounting of the active option can happen when you are in a multi-select Combobox, and you filter out all the selected values. This means that the moment you press "Enter" on an active item, it becomes the selected item and therefore will be filtered out.
Fixes: #2269
> Ensure we reset the `activeOptionIndex` if the active option is unmounted

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/hooks/use-flags.ts
- packages/@headlessui-react/src/internal/open-closed.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/components/transitions/transition.ts
- packages/@headlessui-vue/src/internal/open-closed.ts
- packages/@headlessui-vue/src/test-utils/vue-testing-library.ts
This PR improves when certain cleanup parts of the `Dialog` component happen.
The Dialog is a complex component. Once the Dialog is active it does a number of things:
- Ensure all other elements on the page are marked as inert
- Setup outside click behaviour
- Setup <kbd>Escape</kbd> to close
- Focuses the first focusable element in the Dialog
- Traps focus in the Dialog
- Ensures you can't scroll the background / interact with it
- …
When you wrap the Dialog in a Transition, then the `open` state is controlled by the Transition component. This means that all of the steps above will only be "reverted" the moment the Transition component is fully done transitioning out.
This can cause some problems in SPA environments where clicking on a link goes to a new page, but the Transition/Dialog …
> Start cleanup phase of the `Dialog` component when going into the `Closing` state

- packages/@headlessui-react/src/components/transitions/transition.test.tsx
There is a test in transition.test.tsx in line 105 which already covers using the `as` tag to change the underlying dom tag to an anchor tag. Therefore, in this test we can test whether a span tag is correctly rendered for example.
> Optimize the as prop test within transition component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
This PR fixes a regression in the React version where nested popovers don't work anymore.
The issue was the check to know whether we are in a `Popover.Panel` or not. We also have to check if
we are in the _correct_ panel (this part is important for nested `Popover`s, and was removed). 
Added a test to make sure this won't regress anymore. Also added the same test to the Vue version to
protect against regressions there as well.
Fixes: #2285
Fixes: #2292
> Fix nested `Popover` components not opening

- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-react/src/utils/disposables.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
- packages/@headlessui-vue/src/utils/disposables.ts
This PR fixes an odd bug where blurring the input field would call the `@change` event on the `ComboboxInput`, this ins turn sets the `query.value` and therefore a list of data would be (incorrectly) filtered again because we expected `query.value === ''`.
Internally we set the `onChange` to a handler that just re-emitted the `change` event, but Vue already does that for you.
Fixes: #2171
> Fix `change` event incorrectly getting called on `blur`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
This PR fixes an issue with the `Dialog` component where it doesn't properly closes and therefore doesn't properly cleans up the scroll locking, focus trapping, ...
We already had the `IntersectionObserver` in place for this. But this didn't always trigger properly. For example if the `Dialog` itself didn't have a proper size, but it's content did.
We could update the `root` of the intersection observer to a different element but it becomes hard to know which element to use exactly. Just using the `parentElement` of the Dialog seemed enough, but performing some tests broke other components.
Instead, let's use a `ResizeObserver` (see browser support: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#browser_compatibility) which gets properly trigger when a Dialog becomes …
> Fix `Dialog` cleanup when the `Dialog` becomes hidden

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/utils/transition.ts
- packages/@headlessui-react/src/utils/disposables.ts
- packages/@headlessui-vue/src/utils/disposables.ts
This PR fixes an issue where the `Transition` component causes sub-components (like a `Dialog`) to get "stuck" because it nevers finishes transitioning. 
This can happen if there is nothing to transition at all (e.g.: `display: block;` -> `display: none;`). 
If this happens then the `transitionend` event is never fired and therefore it's waiting for nothing and gets stuck.
Fixes: #2114
> Ensure `Transition` component completes if nothing is transitioning

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
This PR fixes an issue where the `FocusTrap` is not properly handled for allowed root containers (like 3rd party containers).
When using the `FocusTrap` component inside of the `Dialog`, then only the `Dialog` was considered one of the containers. However, we should keep all the allowed containers into account just like how we handle them for outside click and escape behaviour.
Fixes: #2312
> Allow root containers from the `Dialog` component in the `FocusTrap` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/internal/hidden.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-react/src/types.ts
- packages/@headlessui-react/src/use-sync-external-store-shim/useSyncExternalStoreShimClient.ts
- packages/@headlessui-react/src/use-sync-external-store-shim/useSyncExternalStoreShimServer.ts
- packages/@headlessui-react/src/utils/render.test.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/transitions/transition.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
- packages/@headlessui-vue/src/test-utils/vue-testing-library.ts
Recently we improved the correctness of our TypeScript types. However, some of them started catching the actual bugs we initially intended. For example a `Listbox.Button` has an internal `type PropsWeControl = 'disabled'`. This is a union of types that we fully control in Headless UI and you can't override them at all. We always intended to let TypeScript "fail" when you pass any of those but this wasn't always the case. Now it is.
In fact, that's also what we started seeing in recent issues (#2315, #2327). If you look at the actual code in some of the linked issues then you can see that a `disabled` prop is passed to a `Listbox.Button`, but **at runtime** it didn't work as expected, that's where TypeScript now correctly helps us!
But this PR fixes a few things that now also show up. For …
> Fix `XYZPropsWeControl` and cleanup internal TypeScript types

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
This PR fixes an incorrect warning that complained about using multiple `Popover.Button` components. However this is valid inside the `Popover.Panel` itself, just not the `Popover`.
Also added a few tests to make sure we don't regress on this again.
This popped up again because we were checking the `panelId` to make sure that we are in the correct `Popover.Panel`. However, the `panelId` is set when the `Popover.Panel` is rendered and it is registered in a `useEffect`. This is all fine-ish, however this causes a "delay" in the value being ready. 
Combine this with wrapping the `Panel` inside a `Transition` component and the delay causes even more issues. 
To fix this, we reset the `PopoverPanelContext` with a `null` value. That way the `Popover` itself will always reset it. This means that …
> Fix invalid warning when using multiple `Popover.Button` components inside a `Popover.Panel`

- .github/workflows/main.yml
- .github/workflows/release-insiders.yml
This PR should "fix" some of the flakey tests on CI.
Some tests are relying on timing specific tests and are using JSDOM where not everything is implemented (like transition events), if the server (GitHub Actions) is a bit busy, then this can result in flakey tests.
One day we will switch to tests in a real browser, but in the meantime this should be enough.
> Retry tests in CI 3 times before failing

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/tsconfig.json
- packages/playground-react/pages/dialog/dialog.tsx
- packages/playground-vue/src/components/dialog/dialog.vue
This PR fixes an issue in Safari where the focus is not properly restored to the element that originally opened the `Dialog` component.
This is because Safari doesn't "focus", the button when you click on it. We were relying on this (because we used the `document.activeElement`).
Now we will keep track of "focused" items (even when you click them), and use that as a restoreable element.
Fixes: #1643
> Fix restore focus to buttons in Safari, when `Dialog` component closes

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
This PR fixes an issue where some hooks and event listeners still "fire" when the component is already unmounted. This happens beacuse the order of `onUnmounted` is important here. Hoisted the `mounted` state and used it to know whether to enable the hooks or not.
Requires: #2326
Fixes: #2218
> Ensure hooks in the `FocusTrap` component only apply when mounted

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-tailwindcss/package.json
- packages/@headlessui-tailwindcss/src/index.test.ts
- packages/@headlessui-tailwindcss/src/index.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/utils/focus-management.ts
- packages/playground-react/components/button.tsx
- packages/playground-react/package.json
- packages/playground-react/pages/combinations/form.tsx
- packages/playground-react/pages/combinations/tabs-in-dialog.tsx
- packages/playground-react/pages/combobox/combobox-with-pure-tailwind.tsx
- packages/playground-react/pages/dialog/dialog-focus-issue.tsx
- packages/playground-react/pages/dialog/dialog-with-shadow-children.tsx
- packages/playground-react/pages/dialog/dialog.tsx
- packages/playground-react/pages/menu/menu-with-framer-motion.tsx
- packages/playground-react/pages/menu/menu-with-popper.tsx
- packages/playground-react/pages/menu/menu-with-transition-and-popper.tsx
- packages/playground-react/pages/menu/menu-with-transition.tsx
- packages/playground-react/pages/menu/menu.tsx
- packages/playground-react/pages/menu/multiple-elements.tsx
- packages/playground-react/pages/transitions/component-examples/modal.tsx
- packages/playground-react/pages/transitions/component-examples/peek-a-boo.tsx
- packages/playground-vue/src/components/Button.vue
- packages/playground-vue/src/components/dialog/dialog.vue
- yarn.lock
This PR fixes the annoying issue that focus styles show up even if you used the mouse. 
Right now the issue exists whenever we call `element.focus()` that the `element` will show the focus related styles. Unfortunately this is something the browser does (even if you did this call in a `click` handler). There is also no API yet to control this behaviour. There is an experimental API that can be found here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#browser_compatibility
So what are the solutions here?
For starters, you could immediately blur the active element when something receives focus. This would hide the focus ring (because the element won't have focus anymore) but it will degrade the usability of your application. Imagine you are filling out a big form, you …
> Fix focus styles showing up when using the mouse

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-flags.ts
This PR fixes a React warning:
```
Can't perform a React state update on an unmounted component.
```
This happened because we are calling `setState` when the component was already unmounted which
results in a no-op and a small/annoying warning. Luckily we don't have any subscriptions so there
were no memory leaks.
Fixes: #2373
> Fix "Can't perform a React state update on an unmounted component." when using the `Transition` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/utils/document-ready.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/src/utils/document-ready.ts
This PR fixes an issue where some event listeners in the `FocusTrap` component were added prematurely and could crash. This PR ensures that the document itself is ready before trying to attach these events.
If the events are added a little bit later it's not a super big deal.
---
Lazy loading event listeners. See: https://github.com/tailwindlabs/headlessui/pull/2387#issuecomment-1478293818
> Add `FocusTrap` event listeners once document has loaded

- packages/@headlessui-tailwindcss/package.json
Fixes #2381. Also added ESM import paths since I noticed they were also missing.
> Add ESM and `types` paths to `package.json` for TailwindCSS plugin

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.ssr.test.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-vue/src/components/transitions/transition.ssr.test.ts
- packages/@headlessui-vue/src/components/transitions/transition.ts
Fixes #2167
@RobinMalfait Does this seem right to you or is there something else I should look at? I'll port this to Vue once confirmed.
> Fix `className` hydration for `<Transition appear>`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
If you use the default `Combobox` component then it defaults to `Fragment`. This also means that if you provide an additional prop that it would be forwarded to the `Fragment` but that won't work.
You do get a runtime error, but the types aren't 100% clear on what's going on. In fact, they make it very confusing because it will use the last "fallback" in all the `Combobox` definitions which marks the value as "multiple".
Concretely, this means:
```ts
let [value, setValue] = useState('Tom Cook')
<Combobox
value={value}
onChange={setValue}
placeholder="Hello!"
/>
```
Starts complaining about the `value` and `onChange` not handling the
`multiple` case correctly. But it should complain about the `placeholder`.
Switching the order _does_ solve this, but it is not the cleanest solution.
Maybe …
> Improve `Combobox` types to improve false positives

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/utils/render.test.tsx
- packages/@headlessui-react/src/utils/render.ts
> Merge `className` correctly when it’s a function

- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/transitions/transition.ts
> Don't scroll lock when transition isn't showing

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/popover/popover.ts
This PR fixes a memory leak in the `Popover` component for the Vue version.
The `handleFocus` was defined in the `render` function instead of the `setup` function. The `useTabDirection` call was also used inside the `render` function which resulted in a lot of event handlers being creating every single render.
Moving it to the `setup` function itself solves this issue.
> Fix memory leak in `Popover` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
This PR adds demo mode to the `Menu` and `Popover` components.
> [internal] add demo mode to `Menu` and `Popover` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/hooks/use-on-unmount.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
Currently, the tab focus is wrong when navigating on a `Tab` containing a `Dialog` component. 
[Screencast from 04-26-2023 04:22:32 PM.webm](https://user-images.githubusercontent.com/35242329/234532495-b43652d6-d1ef-4844-a3d1-a83958b94c53.webm)
[Screencast from 04-26-2023 04:23:58 PM.webm](https://user-images.githubusercontent.com/35242329/234532996-96f65814-8710-410b-832b-2e3fb15516f0.webm)
Fixes https://github.com/tailwindlabs/headlessui/issues/2406
> Ensure `FocusTrap` is only active when the given `enabled` value is `true`

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR fixes an issue where the exposed `activeIndex` value is out of sync with reality even though the `activeOption` itself contains the correct state.
Fixes: #2447
> Ensure the exposed `activeIndex` is up to date for the `Combobox` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/package.json
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/package.json
I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 
Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.
⚠️ this PR focuses solely on fixing "🐛 Used fallback condition" problem but the "👺 Masquerading as ESM" and "⚠️ ESM (dynamic import only)" remain here. You can check the reported errors for …
> move `types` condition to the front

- jest/create-jest-config.cjs
- jest/polyfills.ts
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/hooks/use-text-value.ts
- packages/@headlessui-react/src/utils/get-text-value.test.ts
- packages/@headlessui-react/src/utils/get-text-value.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/hooks/use-text-value.ts
- packages/@headlessui-vue/src/utils/get-text-value.test.ts
- packages/@headlessui-vue/src/utils/get-text-value.ts
This PR improves the control over the "text value" of a `Menu.Item` or `Listbox.Option`.
When a `Menu` or a `Listbox` is in an open state, then you can just start typing to search for a specific item. It uses a simple algorithm where it looks at the beginning of the option and if it matches your search or not. If you are on an option and you re-type the same thing, then it will jump to the next option that matches.
Concretely, let's look at this setup:
```js
<Listbox>
<Listbox.Button>Country</Listbox.Button>
<Listbox.Options>
<Listbox.Option value="us">United States of America</Listbox.Option>
<Listbox.Option value="ca">Canada</Listbox.Option>
<Listbox.Option value="be">Belgium</Listbox.Option>
<Listbox.Option value="by">Belarus</Listbox.Option>
</Listbox.Options>
</Listbox>
```
If you …
> Improve control over `Menu` and `Listbox` options while searching

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
The blur event only fires on the window. Not the document.
Fixes #2484
> Handle clicks inside iframes

- packages/@headlessui-react/src/hooks/use-outside-click.ts
> Ignore disconnected elements for outside clicks

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR will ensure that the caret is always in a consistent location once the input value is synced with the selected option. We will _not_ do this while the user is typing because changing the position while typing will result in odd results.
Safari already kept the caret at the end, Chrome put the caret at the end but once you synced the value once the caret was in front of the text.
We will also only change the caret position if the position / selection didn't change in the meantime. For example, if you have code like this:
```js
<Combobox.Input onFocus={e => e.target.select()} />
```
This will select all the text in the input field, if we just move the caret position without keeping this into account then we would undo this behaviour which is something we don't want to do.
Fixes: …
> Ensure the caret is in a consistent position when syncing the `Combobox.Input` value

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
This PR improves the outside click behaviour when using our components in combination with 3rd party libraries. It also improves the outside click behaviour on touch devices.
We already use some logic to try and capture the target element outside of the main `click` listener. We do this by listening to a `mousedown` on the `document` while using the `capture` phase (instead of the bubble phase). Some 3rd party tools already use en `event.preventDefault()` in these scenarios.
To try and solve this, we will also listen for `pointerdown` events to capture the target element instead of only relying on the `mousedown` event. We can't just switch to `pointerdown` alone because those events aren't available on older versions of iOS for example.
Another small improvement is to also listen for …
> Improve "outside click" behaviour in combination with 3rd party libraries

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
We had an issue #2409 where typing using an IME (Input Method Editor, E.g.: Japanese — Romaji) already submitted characters while the user was still composing the characters together.
1. Type `wa`
2. Expected result: `わ`
3. Actual result: `wあ` (where `あ` is the character `a`)
This was solved by not triggering change events at all until the `compositionend` event was triggered. This worked fine for this use case. However this also meant that only at the end of your typing session (when you press `enter`/`space`) the actual value was submitted.
Fast forward to today, we received a new issue #2575 where this behaviour completely broke on Android devices. Android _always_ use the IME APIs for handling input... if we think about our solution form above, it also means that while you are typing …
> Ensure IME works on Android devices

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.ts
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/menu/menu.ts
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
This PR improves the calculation of the `aria-expanded` attribute.
You shouldn't be able to open a Listbox/Menu/Combobox/... when the component is in a disabled state, however if you open it, and then disable it then it is still in an open state. Therefore the `aria-expanded` should still be present.
This is also how other libraries behave.
It is also how the native `<select>` behaves. You can open it, disable it programmatically and then you are still able to make a selection.
This seems enough evidence that this change is an improvement without being a breaking change.
Fixes: #2602
> Calculate `aria-expanded` purely based on the open/closed state

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/components/switch/switch.test.tsx
- packages/@headlessui-react/src/utils/form.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/components/switch/switch.test.tsx
- packages/@headlessui-vue/src/utils/form.ts
This PR further improves the form compatibility by using `form.requestSubmit()` when a submit-like button wasn't found in the first place. We still want the other code, otherwise potential `e.preventDefault()` inside the `onClick` of the actual submit button wouldn't be called.
It's only if we can't find a submit button that we want to try the `form.requestSubmit()` way.
We can't use the `form.submit()` function, because then the `form` will be submitted _without_ going through `onSubmit` listeners on the `form` itself.
Fixes: #2611
> Submit form on `Enter` even if no submit-like button was found

- packages/@headlessui-tailwindcss/src/index.ts
This is useful for using browser-default focus styles, but disabling them when the focus visible state is not active, i.e. `ui-not-focus-visible:outline-none`
I have also moved the `focus-visible` variant out of the state loop
> Add `not-focus-visible` variant to Tailwind plugin

- packages/@headlessui-react/src/utils/form.ts
- packages/@headlessui-vue/src/utils/form.ts
This PR fixes an issue where the `attemptSubmit` should ignore the passed in element as a potential submit target.
When you pass in an element to the `attemptSubmit` that has a `type="submit"`, then the `attemptSubmit` will just click this element instead of submitting the form.
We want to skip the current one and fallback to `form.requestSubmit()` instead.
fixes: #2482
> Allow `type="submit"` on `Switch` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
Previously, when:
1. Using either `<Listbox multiple>` or `<Combobox multiple>`; AND
2. Having a default value set (e.g. `defaultValue={['bob']}`); AND
3. The component was uncontrolled; AND
4. It was in a `<form>` element; AND
5. The user clicked the `reset` button
We would incorrectly push the array default value as an entry to the internal value array instead of replacing it. This fixes that problem.
Additionally, while working on this, we discovered that both uncontrolled `<Listbox multiple>` and `<Combobox multiple>` did not output form elements in Vue because they were incorrectly determined to be controlled. This PR fixes this as well.
Fixes #2603
> Use correct value when resetting `<Listbox multiple>` and `<Combobox multiple>`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/hooks/use-root-containers.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/hooks/use-root-containers.ts
This PR improves the rendered DOM structure for `Popover` components.
Some of our components auto close when you click outside of them, the `Popover` component is one of them. However, there are a few exceptions to this rule:
- If you render a notification on top of them and click on the `×` to close the notification then we don't want to close the currently open `Popover`.
- If you render a 3rd party library inside of the `Popover.Panel` component, and the 3rd party component happens to render in its own `Portal` component and you interact with that component then we don't want it to close either.
If the components are using our `Portal` component, then everything is fine, but if they are not using ours, then we have to make some assumptions. Right now, we assume that your applications …
> Render `<MainTreeNode />` indicators in `Popover.Group` only

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/document-overflow/handle-ios-locking.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/hooks/document-overflow/handle-ios-locking.ts
- packages/@headlessui-vue/src/utils/disposables.ts
This PR improves the `Dialog` opening/closing behavior on iOS if you enabled `scroll-behavior: smooth;`
For iOS workaround related purposes we have to capture the scroll position and offset the margin top with that amount and then `scrollTo(0,0,)` to prevent all kinds of funny UI jumps.
However, if you have `scroll-behavior: smooth` enabled on your `html`, then offseting the margin-top and later `scrollTo(0,0)` would be handled in a smooth way, which means that the actual position would be off.
To solve this, we disable smooth scrolling entirely in order to make the position of the Dialog correct. This shouldn't be a problem in practice since the page itself isn't suppose to scroll anyway.
Once the Dialog closes we reset it such that everything else keeps working as expected in a (smooth) …
> Disable smooth scrolling when opening/closing `Dialog` components on iOS

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.ts
Right now we assume that the `Tab` components are rendered when calculating the active index. But this isn't always the case if we are lazy loading the tab components.
If no tabs are available, then calculating the next index would result in `-1` which is incorrect because then nothing is selected. Instead, we keep the currently selected index (typically `0`) and once the `tab` gets loaded it will be the active one automatically.
Fixes: #2596
Fixes: #2640
> Don't assume `<Tab />` components are available when setting the next index

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/disclosure/disclosure.srr.test.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.ts
- packages/@headlessui-vue/src/test-utils/ssr.ts
- packages/playground-vue/src/components/tabs/simple-tabs.vue
This PR improves the SSR of the `Disclosure` component in a Vue js application.
When you don't pass in a custom ID, a fresh ID would be generated as the `default` logic for the `id` prop. However, this doesn't play nicely with Vue / Nuxt SSR. Restructuring the code and updating the ID on the client if an ID is passed solves the SSR issue.
We also added SSR related tests to show that SSR and Hydrating is working as expected.
---
~~This is still a WIP, because in Nuxt.js there is something happening that's a bit odd. The ID for the `button` and the `panel` are correct, and the `aria-controls` on the button points to the ID of the `panel` which is all fine.~~
~~The moment it is hydrated and you look at the devtools then the IDs do _not_ line up anymore and they are different.~~
~~To make …
> Improve SSR of the `Disclosure` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR fixes an odd issue in the `Combobox` where it incorrectly focuses the `Combobox.Input`.
We have some code that ensures that the selection range of the `Combobox.Input` is correct when syncing values to the input field. However, calling `setSelectionRange` _will_ actually focus the `input` DOM element if it is not focused yet.
This PR will only try to set the selection range if the input is the focused element.
Fixes: #2653
> Fix incorrectly focused `Combobox.Input` component on page load

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-react/src/components/transitions/utils/transition.test.ts
- packages/@headlessui-react/src/components/transitions/utils/transition.ts
- packages/@headlessui-react/src/hooks/use-transition.ts
- packages/@headlessui-react/src/utils/class-names.ts
- packages/playground-react/package.json
- packages/playground-react/pages/transitions/appear.tsx
- packages/playground-react/pages/transitions/react-hot-toast.tsx
- yarn.lock
This PR fixes the `appear` prop not working on the `Transition` component. This ensures that it works even when the `enter` and `enterFrom` classes are pre-rendered on the server using SSR.
This contains a combination of multiple bugs working as one big bug:
- In the `Transition` component, the `unmount={true}` should be the default. However, omitting the prop didn't result in a `true` value in some checks. This is solved in this PR.
- When server side rendering and `appear` is set to `true`, we will ensure that the classes are server side rendered, and once it hydrates the animation kicks in.
- In addition, once SSR/Hydration is over, we don't want React to diff and apply changes to the `className` prop anymore. We are directly mutating the DOM when a transition is happening.
- Another …
> Ensure `appear` works using the `Transition` component (even when used with SSR)

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/transitions/utils/transition.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
This PR fixes a bug where clearing out the value of the `Combobox.Input` didn't always reset the value properly.
We will now make sure to:
1. Ensure that pressing escape when in `nullable` mode goes back to the previous option
2. Ensure that pressing escape when in `nullable` mode, after the input has been cleared doesn't go to any option
3. Ensure that the `onChange` (React) or `@update:modelValue` (Vue) is being called with `null` when a reset happens (this is important for you to reset a potential `query` value for filtering purposes)
4. Ensure that all kinds of "clearing the input" works, not only when working with <kbd>escape</kbd>/<kbd>delete</kbd>. This now also works with <kbd>ctrl/cmd</kbd>+<kbd>x</kbd>
One gotcha is that typically you reset the `query` for filtering in the …
> Improve resetting values when using the `nullable` prop on the `Combobox` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-server-handoff-complete.ts
- packages/playground-react/pages/suspense/portal.tsx
This is a redo of #2633 but with a more targeted fix for just React 18+
Previously, when dealing with SSR, we had a hook that would basically force a re-render of all components on page load. This also used some global state so we didn't unnecessarily cause re-renders for components that were mounting after the page had already loaded.
However, because `<Suspense>` delays hydration this is no longer a viable solution. I've implemented a targeted fix by (mis)using the `useSyncExternalStore` API. You can provide a `getServerSnapshot` callback that only runs on the server AND in the browser but only _when hydrating_. This gives us just enough info to know when hydration is happening.
I've slotted that into our `useServerHandoffComplete()` hook to handle the `<Suspense>` case. I'm also using …
> Fix hydration of components inside `<Suspense>`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This is a small change to the `<Tab>` component that disables scrolling when focusing a tab button. While we want to focus the tab button, I don't think we want the default browser scroll-into-view behavior, as it creates weird issues like what you see in https://github.com/tailwindlabs/tailwindui-issues/issues/1467. Here's a screen recording of that issue:
https://github.com/tailwindlabs/headlessui/assets/882133/14ea227c-5618-478b-b754-56a1c797545f
I think it's better to just preserve the existing scroll position than to try and have the browser scroll the tab button into focus. Here's what that looks like:
https://github.com/tailwindlabs/headlessui/assets/882133/1584949c-f187-4a32-a503-95c145761972
> Prevent scrolling when focusing a tab

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
Closes: #2671 
Removed click event on mobile that was fired before onTouchEnd causing a the onClose function to fire twice.
> fix: double onClose on mobile dialog outClick

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
In the `<Dialog>` component if you had a simple dialog with just a panel but no title — and it defaulted to open on initial render — clicking inside the dialog would close it.
Basically, clicking the `<p>` tag inside this component would close the dialog:
```js
export default function MyDialog() {
const [isOpen, setIsOpen] = useState(true)
return (
<Dialog
open={isOpen}
onClose={() => setIsOpen(false)}
>
<Dialog.Panel>
<p>
My content
</p>
</Dialog.Panel>
</Dialog>
)
}
```
While being open on initial render isn't super common this can pop up if you're conditionally mounting the dialog by doing something like `isOpen && (<Dialog>…</Dialog>)`. 
The current implementation reads refs on render to determine the "root" container that contains the dialog. However, this didn't work for initial …
> Lazily resolve default containers in `<Dialog>`

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/portal/portal.test.ts
- packages/@headlessui-vue/src/components/portal/portal.ts
We now defer mounting portal content by one tick in Vue to ensure it matches during SSR hydration
> Fix Portal SSR hydration mismatches

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/internal/hidden.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.ts
- packages/@headlessui-vue/src/internal/hidden.ts
This PR fixes an issue where the hidden `TabPanel` components are focusable in the accessibility tree and the VoiceOver cursor can access them.
Adding the `aria-hidden="true"` fixes this issue.
Fixes: #2688
> Ensure hidden `TabPanel` components are hidden from the accessibility tree

- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
Our `<Dialog>` component in React and Vue unconditionally sets the role to `dialog`. However, there are situations when a role of `alertdialog` would be more appropriate. This PR allows the user to choose between the two and will fallback to `dialog` if passed a role that is invalid or otherwise not suitable for use by the `<Dialog>` component.
The `alertdialog` role can be used when:
- The message or action being presented is important enough that it **needs** to interrupt the user's workflow; AND
- The dialog requires user interaction, confirmation, acknowledgement, etc…
For example, a confirmation dialog when deleting a user would be a suitable use case for `role="alertdialog"`.
Take a look at [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alertdial …
> Add support for `role="alertdialog"` to `<Dialog>` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/test-utils/interactions.ts
This PR fixes an issue where on mobile Android the `Combobox` was not closing when pressing "Next"
on the keyboard.
This is because the "Next" button blurs the current input, but we weren't handling that properly.
This PR fixes that by also closing the `Combobox` if the `Combobox.Input` is blurred.
Fixes: #2672
> Ensure blurring the `Combobox.Input` component closes the `Combobox`

- .github/workflows/main.yml
- .github/workflows/prepare-release.yml
- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
- package.json
- scripts/package-path.js
- scripts/release-channel.js
- scripts/release-notes.js
This PR adds the `prepare-release` and `release` workflows similar to our other repositories.
This will allow us to:
1. Make a tag locally
2. Push the tag
Once the tag is pushed, a draft GitHub release will be created for this tag. It will also populate
the release notes with the contents from the `CHANGELOG.md` file for the current pacakge / tag.
When the GitHub release is published, another workflow (`release`) will be executed and it will
publish the version to npm.
> Improve release workflow

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/popover/popover.ts
- packages/@headlessui-vue/src/hooks/use-resolve-button-type.ts
- packages/@headlessui-vue/src/utils/dom.ts
We were previously checking for an HTMLElement directly but now will "pierce" the component tree if a Vue Component is used as a child of `<PopoverButton>` with `as="template"`.
This resulted in us thinking the button didn't exist and clicks on it were considered outside which would close and then re-open the popover since the button being clicked was wired up to toggle it.
Basically, this didn't work before but now does:
```vue
<template>
<Popover>
<PopoverButton as="template">
<ButtonWrapper>Not Working</ButtonWrapper>
</PopoverButton>
<PopoverPanel>
<div>my content</div>
</PopoverPanel>
</Popover>
</template>
```
where `ButtonWrapper` is just:
```vue
<template>
<button type="button">
<slot />
</button>
</template>
```
Since we pierce the component tree we're now able to get at the …
> Allow `<button>` to be in nested components in `<PopoverButton>`

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/utils/render.ts
In some cases if we used our own ref (we do this in `<TransitionRoot>` for instance) and rendered slot children we would wipe out  user-specified refs. This could be easily reproduced when adding a ref on a component that was an immediate child of a `<TransitionRoot>` with `as="template"`.
So, now, we set a flag when calling `cloneVNode` to merge our refs and any user-specified refs thus preserving own own refs _and_ any user-specified template refs.
Fixes #2710
> Don't overwrite user-defined template refs when rendering

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/utils/active-element-history.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/focus-trap/focus-trap.ts
- packages/@headlessui-vue/src/utils/active-element-history.ts
- packages/playground-react/pages/combobox/combobox-open-on-focus.tsx
- packages/playground-vue/src/components/combobox/combobox-open-on-focus.vue
Maintainers note:
This PR introduces a new `immediate` prop on the `<Combobox />` component to open the `<Combobox />` immediately once the `<Combobox.Input />` receives focus.
It does handle edge cases where focus is moved into the `<Combobox.Input />` without opening the `<Combobox />` again. These edge cases are:
- Clicking the `<Combobox.Button />` to close the `<Combobox />` will move focus into the `<Combobox.Input />` this will not open the `<Combobox />` again.
- Clicking on a `<Combobox.Option />` will temporarely move focus to the `<Combobox.Option />`, then focus is moved back into the `<Combobox.Input />`. This will not open the `<Combobox />` again.
Another edge case that is important to mention:
- When a `<Combobox />` is open, the first `<Combobox.Option />` is selected. …
> Add `immediate` prop to `<Combobox />` for immediately opening the Combobox when the `input` receives focus

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.tsx
This PR fixes an issue where updating the `className` didn't work. 
This was sort of deliberate because we didn't want React to diff and update the `className` if we are currently transitioning. However, we didn't check for transitioning state itself. If the `<Transition />` component is currently _not_ transitioning then changing the className should work as expected.
Fixes: #2714
> Allow changes to the `className` prop when the `<Transition />` component is currently not transitioning

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/description/description.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/label/label.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
This isn’t really ideal. We’d rather not export these and instead export implicit function types but TypeScript doesn’t appear to be too happy about trying to do that.
This is a WIP. Would definitely prefer to find a different solution here _if_ possible that fixes the problem but also doesn't increase the surface area of exported types.
Fixes #2306
> Export component interfaces

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/package.json
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/package.json
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/playground-react/data.ts
- packages/playground-react/package.json
- packages/playground-react/pages/combobox/combobox-virtualized.tsx
- packages/playground-vue/package.json
- packages/playground-vue/src/components/combobox/_virtual-example.vue
- packages/playground-vue/src/components/combobox/combobox-virtualized.vue
- packages/playground-vue/src/data.ts
- yarn.lock
This PR adds a new `virtual` prop to the `Combobox` component to improve performance issues by only
rendering what's visible on the screen.
Behind the scenes the `@tanstack/react-virtual` and `@tanstack/vue-virtual` libraries are used to do the heavy lifting.
Once the `virtual` prop is in use, it also requires the `Combobox.Option` to have an `order` prop. This prop is used to improve internal sorting based on this number instead of sorting by DOM node position.
This prop can also be used in a non-virtual `Combobox` version to improve some of the performance.
The diff looks like this:
```diff
- <Combobox>
+ <Combobox virtual>
<Combobox.Input />
<Combobox.Options>
{countries.map((country, idx) => (
-       <Combobox.Option key={country} value={country}>
+       <Combobox.Option …
```
> Add `virtual` prop to `Combobox` component

- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
Hello!
I've been migrating my React project to Preact. There seems to have been a longstanding infinite loop bug with HUI's RadioGroup over in Preact. (https://github.com/preactjs/preact/issues/3827)
I was looking into it, and its a simple line change to fix. To be honest I've no idea how this works fine in React!
Hopefully this can be merged and there isn't a reason why this isn't possible, looking over at the `vue` RadioGroup version for comparison, this effect seems to be only needed on mount rather than every render (which is what was happening when `props` was a dep causing parent to re-render, leading to an infinite loop), so this looks like it makes sense.
Thanks!
> Update Radio's OptionFn effect deps to fix infinite loop.

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/utils/render.ts
In Headless UI we have to merge multiple refs when rendering. For example we might use a ref internally to get access to a DOM node and the user might also pass in their own ref via forwardRef.
Our `render()` has to do some work to merge refs of children when rendering `Fragment` components. However, the ref callback we created was not stable. This resulted in an infinite render loop in certain scenarios where rendering a child component causes the parent to re-render (because of shared state in a context for instance).
A side-effect of this render loop was that `<Suspense>` did not work as expected. Sometimes never updating until the suspense boundary was re-created.
This introduces a new, internal hook called `useMergeRefsFn` that we can use that allows us to merge multiple refs and …
> Make sure `as={Fragment}` doesn’t result in a render loop

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/utils/calculate-active-index.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/utils/calculate-active-index.ts
- packages/playground-react/next.config.js
- packages/playground-react/pages/_app.tsx
- packages/playground-react/pages/combobox/combobox-virtualized.tsx
- packages/playground-vue/src/Layout.vue
- packages/playground-vue/src/components/combobox/_virtual-example.vue
- packages/playground-vue/src/components/combobox/combobox-virtualized.vue
This PR is an improvement on the [previous PR](https://github.com/tailwindlabs/headlessui/pull/2740) where we introduced a new `virtual` prop to the `Combobox` component.
This new API requires you to pass in a list of options, and provide a template to the `Combobox.Options` such that we can _only_ render the visible options (+ overscan).
**React:**
```tsx
<Combobox
virtual={{
options: ["Foo", "Bar", "Baz"],
disabled: (option) => option === "Bar",
}}
>
<Combobox.Input />
<Combobox.Options>
{({ option }) => <Combobox.Option value={option}>{option}</Combobox.Option>}
</Combobox.Options>
</Combobox>
```
**Vue:**
```vue
<template>
<Combobox :virtual="virtual">
<ComboboxInput />
<ComboboxOptions v-slot="{ option }">
<ComboboxOption :value="option">{{ option }}</ComboboxOption> …
```
> Implement new `virtual` API for the `Combobox` component

- packages/@headlessui-vue/src/utils/render.test.ts
- packages/@headlessui-vue/src/utils/render.ts
We accidentally broke the `data-headlessui-state="…"` attribute in Vue when using `as="template"`. In this situation the attribute would be omitted when it shouldn't be.
This PR fixes that so the `@headlessui/tailwindcss` plugin works again when using components from Radio Group, Listbox, Combobox, etc… with `as="template"`
Fixes #2786
> Fix state data attribute in Vue

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
Chrome currently has a bug if you use a `Listbox` with a `Label` and use the `aria-multiselectable` attribute. This combination will cause VoiceOver to _not_ announce the `role="option"` elements when interacting with them.
If we drop the `aria-multiselectable` OR the `aria-labelledby` it starts working. Alternatively replacing `aria-labelledby` with `aria-label` won't work either.
I filed a Chrome bug report about this here: https://bugs.chromium.org/p/chromium/issues/detail?id=1498261
---
Luckily there is a workaround in our `Listbox` implementation. Right now we always require the `Listbox.Button` to be there. The `Listbox.Options` component doesn't work on its own in our implementation.
This means that whenever we open the `Listbox` that we have to go via the `Listbox.Button`. This …
> Fix VoiceOver bug for `Listbox` component in Chrome

- .github/workflows/main.yml
- .github/workflows/prepare-release.yml
- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
- package.json
- packages/@headlessui-react/package.json
- packages/@headlessui-tailwindcss/package.json
- packages/@headlessui-tailwindcss/scripts/fix-types.js
- packages/@headlessui-vue/package.json
- packages/@headlessui-vue/src/utils/owner.ts
- packages/playground-react/package.json
- packages/playground-vue/package.json
- scripts/build.sh
- yarn.lock
Fixes #2838
Comically enough our ESM types *are* correct for CJS as well because we don't use default nor do we need to use `export =` in CJS. We only have named exports for Headless UI.
This means that, in TypeScript, the `export function`, `export let`, etc… syntax all works fine for CJS.
Given that, there's a quick and dirty fix for this:
- Copy the generated types file
- Rename it to have a cts extension
- Update `exports` to use point to these files separately
If we ever added a default export like `export default` then things would break but the Node 10 check would catch it. Likewise, if we ever did `module.exports = …` somewhere then the Node 16 check would catch that.
> Fix CJS types

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transitions/transition.test.tsx
- packages/@headlessui-react/src/components/transitions/transition.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/transitions/transition.ts
> fix DOMException when remove class with '\n' character in 'transition' component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/document-overflow/handle-ios-locking.ts
This PR fixes an issue where the scroll locking inside a `Dialog` component was _too_ strict because
horizontally scrolling inside the `Dialog` wasn't allowed anymore.
This PR fixes that by checking both vertical and horizontal scroll containers (that may or may not
be overflowing already) and only use `e.preventDefault()` if those do not exist.
> Allow horizontal scrolling inside the `Dialog` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/utils/render.ts
This PR fixes and improves the `disabled` and `aria-disabled` event handling that we introduced in
[#1265](https://github.com/tailwindlabs/headlessui/pull/1265). 
We wrongly assumed that we don't want to attach any event listeners if the `disabled` or
`aria-disabled` props were used. While in most cases this is true, and is even a no-op (the browser
doesn't call `onClick` on a `<button disabled>`) it is not true in other cases. 
For example `<a disabled>` doesn't exist, instead we use `<a aria-hidden="">`. If we now want to
"disabled" the native click behaviour we have to add `onClick={e => e.preventDefault()}`.
In the linked PR, we were removing the `onClick` we could have added. In this PR we make sure to
always add `e => e.preventDefault()` instead of the `onXYZ` handler we or you …
> Improve cancellation of events when using `disabled` or `aria-disabled` attributes

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/document-overflow/handle-ios-locking.ts
This PR fixes an issue that I only noticed in a production build and not in the local development
version (potentially related to strict mode?).
However, we are trying to scroll lock the page on iOS, a way to do this is to add
`overscroll-behavior: contain;` and call `event.preventDefault()` in the `touchmove` event. While
this works great, we have to account for scrollable elements _inside_ the allowed containers (e.g.:
a scrollable table in a dialog).
We did this by checking whether or not the `event.target` or any of its parent were scrollable. The
heuristic we used was two-fold:
1. Does the computed style have `overflow: auto | scroll;`, `overflow-x: auto | scroll;` and `overflow-y: auto | scroll;`
2. Or, is there an overflow happening `element.scrollWidth` > `element.clientWidth` or …
> Further fine tune scroll locking on iOS

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/input/input.tsx
- packages/@headlessui-react/src/components/select/select.tsx
- packages/@headlessui-react/src/components/textarea/textarea.tsx
This PR ensures that the types for `Input`, `Select` and `Textarea` expose information about the
`ref`.
Right now, these components do accept a ref and forward them to the correct underlying DOM element,
but the types aren't in sync.
> Ensure `Input`, `Select` and `Textarea` expose `Ref` related types

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR fixes an issue where `disabled` on the `<Tab/>` component wasn't exposed.
This will expose it such that you can use it with `ui-disabled`. In the Alpha version of React, you can also use `data-[disabled]` because it will be exposed as `data-disabled` over there as well.
Marked it as fixed because we already accept the `disabled` state and expose it in some other components so considered it "missing".
Fixes: #2864
> Expose `disabled` state on `<Tab />` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/dialog/dialog.ts
When using a `Dialog`, we should prevent the default behaviour of the event that triggered the "close" in the `useOutsideClick` call.
We recently made improvements to improve outside click behaviour on touch devices (https://github.com/tailwindlabs/headlessui/pull/2572) but due to the `touchend` event, the touch is still forwarded and therefore a potential button _behind_ the "backdrop" will also be clicked. This is not what we want.
Added the `event.preventDefault()` for the Dialog specifically because there are other places where we use `useOutsideClick` and where we _do_ want the behaviour where the click just continues. A concrete example of this is 2 `Menu`'s next to eachother where you open the first one, and then click on the second one. This should close first one (outside click) …
> Prevent default behaviour when clicking outside of a `Dialog.Panel`

- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.ts
> Don’t override explicit `disabled` prop for components inside `<MenuItem>`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/input/input.tsx
- packages/@headlessui-react/src/components/textarea/textarea.tsx
This PR improves the exposed `data-focus` for the `Input` and `Textarea` components.
This used to use the `isFocusVisible`, but for these components we always want to show a ring when it is focused regardless of whether it was focused via the keyboard or via the mouse.
> Use `isFocused` instead of `isFocusVisible` for `Input` and `Textarea` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/field/field.test.tsx
- packages/@headlessui-react/src/components/field/field.tsx
This PR ensures that the `Field` can be used using a render prop as the children of the `Field` component.
This means that we can now do this again:
```tsx
<Field>
{({ disabled }) => {
return <input className={disabled ? "..." : "..."} />;
}}
</Field>
```
This normally works in every component, but it was missing because we were manually wrapping the children in a component and forgot to handle this case.
> Ensure `children` prop of `Field` component can be a render prop

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/hidden.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/internal/hidden.ts
This PR adds the `hidden` attribute to the `<Hidden />` component if the `Features.Hidden` is used as a feature.
We used to only add `display: none`, but that's not enough since certain CSS selectors still "see" this DOM node. 
E.g.: `space-x-4` in Tailwind CSS will set the `margin-left` on everything but the first DOM node. It is implemented with an exception for the `hidden` attribute.
Fixes: #2947
> Add `hidden` attribute to internal `<Hidden />` component when the `Features.Hidden` feature is used

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/checkbox/checkbox.test.tsx
- packages/@headlessui-react/src/components/checkbox/checkbox.tsx
This PR fixes an issue where pressing `Enter` on a `<Checkbox />` component didn't attempt to submit the form. This PR solves that.
The `Checkbox` component is a `span` to make it stylable which means that it doesn't have the native capabilities to submit a form (we do render a hidden input field for exposing the data to the parent `form` but it doesn't retrieve any events directly).
This now implements the same logic as the `<Switch />` component where it attempts to submit the form. 
Fixes: #2958
> Attempt form submission when pressing `Enter` on `Checkbox` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/switch/switch.test.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/switch/switch.test.tsx
- packages/@headlessui-vue/src/components/switch/switch.ts
- packages/@headlessui-vue/src/test-utils/accessibility-assertions.ts
This PR allows overriding the `tabIndex` of the `<Switch />` component if you need to change the tab index. However, we still need it to be focusable using the keyboard so we will always fallback to `0` even if `-1` was pased.
Fixes: #2915
> Allow setting custom `tabIndex` on the `<Switch />` component

- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
Now the `<Listbox.Button>` component will submit the form when enter is pressed after being focused rather than opening the listbox. This is for consistency with all other form controls in Headless UI — this also matches the behavior of native browser form controls.
Fixes #2969
> [v2] Make `Listbox` submit form on `Enter` when not open

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
Resolves #2963 #2964
This PR fixes an issue with the `Combobox` component's `activeOption` render prop which was always `null` and also causing an error when hovering over an option with a `null` value.
> Fix Combobox `activeOption` render prop

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/checkbox/checkbox.tsx
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.test.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/internal/form-fields.tsx
- packages/@headlessui-react/src/test-utils/scenarios.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/listbox/listbox.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.ts
- packages/@headlessui-vue/src/components/switch/switch.test.tsx
- packages/@headlessui-vue/src/components/switch/switch.ts
This PR fixes an issue where form-like components are disabled then the hidden input fields should be disabled as well otherwise they will be submitted to the form.
We will now forward the `disabled` state to the hidden inputs.
Fixes: #2988
> Forward `disabled` state to hidden inputs in form-like components

- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/dialog/dialog.test.ts
- packages/@headlessui-vue/src/components/disclosure/disclosure.test.ts
- packages/@headlessui-vue/src/components/listbox/listbox.test.tsx
- packages/@headlessui-vue/src/components/menu/menu.test.tsx
- packages/@headlessui-vue/src/components/popover/popover.test.ts
- packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts
- packages/@headlessui-vue/src/components/switch/switch.test.tsx
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
Something I noticed while working on another issue, some of the test methods have been deprecated. This PR fixes that by using the new methods they expect.
> Replace deprecated Jest methods with the new methods

- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
This commit adds provenance for all published packages. See the NPM documentation [0].
Provenance will allow people to verify that the headlessui packages were actually built on GH Actions and with the content of the corresponding commit. This will help with supply chain security.
For this to work, the `id-token` permission was added only where necessary.
[0]: https://docs.npmjs.com/generating-provenance-statements
> CI: Add provenance to publised packages

- packages/@headlessui-react/LICENSE
- packages/@headlessui-tailwindcss/LICENSE
- packages/@headlessui-vue/LICENSE
This PR adds the missing LICENSE file to every package, instead of only keeping it in the root of the repo.
Fixes: #3010
> Add LICENSE file to each individual package

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/utils/__snapshots__/render.test.tsx.snap
- packages/@headlessui-react/src/utils/render.test.tsx
- packages/@headlessui-react/src/utils/render.ts
Typically when Headless UI components set certain props on a component, then they are there to make sure that the component behaves as expected. E.g.: `aria-*` attributes, `role` attributes, `tabIndex`, etc.
However, we also provide helpful `data-focus` or `data-hover` attributes that make styling components easier. These attributes are not necessary to make the component behave as expected.
This brings us to the problem that this PR solves. Sometimes when you use one of Headless UI's components, and you provide your own component that already contains the same `data-*` attributes, then your attributes will be overridden.
This PR solves that and prefers the existing `data-*` attributes over the ones we set in Headless UI.
This is currently only implemented when you can't really control …
> Prefer incoming `data-*` attributes, over the ones set by Headless UI

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/tabs/tabs.test.ts
- packages/@headlessui-vue/src/components/tabs/tabs.ts
This PR fixes an issue where the `selectedIndex` doesn't always match the visibly selected tab, when using a controlled `<Tab />` component.
The `<Tab />` component can be used in 2 ways:
- Uncontrolled: where the `selectedIndex` is managed internally by the component itself.
- Controlled: where the `selectedIndex` is managed by the parent component (or in other words, **you**).
When the `<Tab />` component is uncontrolled, and thus the state is managed internally, then we try to make sure that we maintain the active tab. For example, if you have the following tabs:
```
+---------+---------+---------+
| Tab foo | Tab bar | Tab baz |
|         | ------- |         |
+---------+---------+---------+
```
Right now `Tab bar` is the active one, if you now add or remove a tab _before_ `Tab bar` …
> Respect `selectedIndex` for controlled `<Tab/>` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
This PR fixes an issue where the `displayValue` on the `ComboboxInput` component is executed on every render. This PR fixes that by only executing the callback if either the `value` or the `displayValue` itself changes.
This is especially useful if you have a `displayValue` that is a function that does some heavy computation or that contains undeterministic code. E.g.: `Math.random()`, `Date.now()`, …
Fixes: #3044
> Prevent unnecessary execution of the `displayValue` callback in the `ComboboxInput` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- playgrounds/react/pages/combobox/combobox-countries.tsx
This PR exposes the `--input-width` and `--button-width` CSS variables in the `ComboboxOptions` component. 
This allows users to make the `ComboboxOptions` component the same width as the `ComboboxInput` or `ComboboxButton` or a combination of both.
The reason I added both is just because it doesn't hurt to have both, and when testing it on the countries example (https://headlessui-react-git-feat-add-combobox-input-width-tailwindlabs.vercel.app/combobox/combobox-countries) it was useful to have both.
> Expose `--input-width` and `--button-width` CSS variables on the `ComboboxOptions` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/hooks/use-element-size.ts
This PR exposes the `--button-width` CSS variable on the `PopoverPanel` component, similar to all are other components that accept an `anchor` prop.
> Expose the `--button-width` CSS variable on the `PopoverPanel` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/hooks/use-refocusable-input.ts
This PR improves the cursor position when re-focusing the `ComboboxInput` component. 
What used to happen is that in some scenario's the cursor would be placed at the beginning of the input instead of at the end.
This PR fixes that, but improves it a bit more:
1. If a selection inside the `ComboboxInput` was available, and you click the `ComboboxButton` (which blurs the input, focuses the button and then re-focuses the input), the selection is restored (as-if nothing happened).
2. If the input was focused, and you click on an `ComboboxOption`, then we re-focus the `ComboboxInput` and place the cursor at the end of the input. This allows you to continue typing without having to move the cursor.
This is something you have to test in Chrome and Safari separately.
> Fix cursor position when re-focusing the `ComboboxInput` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/mouse.ts
- packages/@headlessui-react/src/hooks/use-frame-debounce.ts
- packages/@headlessui-react/src/hooks/use-refocusable-input.ts
- packages/@headlessui-react/src/utils/disposables.ts
This PR improves the UX of the `Combobox` component. 
When you open the combobox via the button or when you select an option from the list, then the focus is briefly moved to the button or the option respectively and then we restore the focus to the input itself.
We improved this behaviour in #3065 where we ensure that the selection and cursor position inside of the input will be preserved when the focus is moved around as-if nothing happened.
However, this can result in a tiny selection flicker (because when the focus is moved to the button or the option, the selection is removed).
This PR improves on that behaviour by using the `mousedown` event instead of the `click` event. If we use `event.preventDefault()` in the `mousedown` event, then the focus will not be moved to the button or …
> Keep focus inside of the `<ComboboxInput />` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transition/transition.tsx
This PR marks the `entered` prop on the `Transition` component as deprecated. This prop was used to ensure that some classes stay after the transition finishes.
However, it makes more sense to use the `enterTo` and `leaveTo` classes to achieve the same effect. This was already implemented, so there is no need for the `entered` prop at all. We keep it for backwards compatibility reasons, but marking it as deprecated such that you can drop it from your own codebase if you want.
Quick summary:
- We keep the `enterTo` classes once the `enter` transition finishes
- We keep the `leaveTo` classes once the `leave` transition finishes
> Deprecate the `entered` prop on the `Transition` component

- packages/@headlessui-react/tsconfig.json
- packages/@headlessui-vue/tsconfig.json
This PR is a fix for internal usage while developing Headless UI itself. Until this PR, code actions in your editor for importing paths typically imported the wrong path.
It used absolute paths instead of relative paths. This did fail when building.
```diff
- import foo from 'utils/foo';
+ import foo from '../utils/foo';
```
This should now be fixed.
> Ensure import actions use the correct paths

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/checkbox/checkbox.test.tsx
- packages/@headlessui-react/src/components/checkbox/checkbox.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/internal/form-fields.tsx
This PR ensures that we always render the hidden form input elements for the `Checkbox`, `Switch` and `RadioGroup` components.
The reason why we didn't render them was because they weren't included in the `FormData` anyway as long as they are not "checked". However, this makes it harder if you want to get access to the elements if you use some form library that uses the inputs in the form. Additionally, this also means that we were adding and removing elements from the DOM.
Now with this change, they will always be there and the `checked` attribute will be updated behind the scenes instead. Now, the hidden inputs will always be available in the form data.
Note: if you don't pass the `name` prop, the hidden form inputs won't be rendered (same behavior as before).
Fixes: #2977
> Render hidden form input fields for `Checkbox`, `Switch` and `RadioGroup` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/tabs/tabs.tsx
> Make sure panels re-register when IDs are calculated in React < 18

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
This PR fixes an issue where defining the types of the `Combobox` component explicitly made the type of the `multiple` prop incorrect (it defaulted to `true`).
E.g.:
```ts
<Combobox<{ id: number, name: string }> />
```
This eventually became the following type:
```ts
{ id: number, name: string }[]
```
... which is incorrect.
> Ensure the `multiple` prop is typed correctly when passing explicit types to the `Combobox` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/floating.tsx
This is done for 2 reasons:
1. The default strategy in Floating UI was already `absolute`
2. It can improve performance drastically when using transitions
The main reason we used `fixed` was to ensure that it wasn't accidentally positioned to another `relative` element. However, all components that use this `FloatingProvider` will also use a portal which puts elements in the `<body>` already so this should be safe.
If it is not safe for your application, then you can still use the `fixed` strategy.
> Use `absolute` as the default Floating UI strategy

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
We deprecated the `nullable` prop because this is now the default behavior. However, we didn't delete the prop from the incoming `props`. This means that the `nullable` prop will end up in the underlying DOM node, or worse the `Fragment` (default tag) and error.
This PR fixes that by eating the `nullable` prop so that it never ends up on the underlying DOM node or `Fragment`.
> Omit `nullable` prop from `Combobox` component

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR ensures that clicking inside the scrollbar area of the `ComboboxOptions` does not close the `Combobox`.
The main issue (see #3071) is that clicking inside the scrollbar area moves focus into the `TabPanel` which blurs the `ComboboxInput` and in turn closes the `Combobox`.
Preventing the default behavior of the `mousedown` event when clicking inside the scrollbar area of the `ComboboxOptions` prevents the focus from moving to the `TabPanel` and keeps the `Combobox` open.
Fixes: #3071
> Prevent closing the `Combobox` component when clicking inside the scrollbar area

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
This PR changes the default tags for the following components:
- Use `div` as default tag for `ListboxOptions` and `ListboxOption` components
- Use `div` as default tag for `ComboboxOptions` and `ComboboxOption` components
These were using `ul` and `li` respectively, which means that if you used `as="div"` on one of them, that you would have to use `as="div"` on the other but that's not always clear and nothing will break or throw an error if you do. It would just be incorrect HTML.
We already set a custom `role` attribute, so the default role we get from `ul`/`li` elements was overwritten anyway.
- Use `div` as default tag for `TabGroup`
In a lot of places an additional wrapper element OR `as="div"` was requirement for layout such as constraining the width. Making the `TabGroup` as `div` …
> Change default tags for `ListboxOptions`, `ListboxOption`, `ComboboxOptions`, `ComboboxOption` and `TabGroup` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/internal/modal.tsx
When you render a `Listbox` in a `Dialog`, then clicking outside of the `Listbox` will only close the `Listbox` and not the `Dialog`.
This is because the `Listbox` is rendered _inside_ the `Dialog`, and the `useOutsideClick` hook will prevent the event from propagating to the `Dialog` therefore it stays open.
Then, if you add the `anchor` prop to the `ListboxOptions` then a few things will happen:
1. We will render the `ListboxOptions` in a `Modal`, which portals the component to the end of the `body` (aka, it won't be in the `Dialog` anymore).
2. The `anchor` prop, will use Floating UI to position the element correctly.
If you now click outside of the open `Listbox`, then the `Dialog` will receive the click event (because it is rendered somewhere else in the DOM) and therefore the …
> Ensure anchored components are properly stacked on top of `Dialog` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
This PR fixes an issue where the focus is not properly moved to the `ListboxOptions` or `MenuItems` component if the underlying DOM node is rendered at a later point in time.
This can happen when the `ListboxOptions` or `MenuItems` component is rendered inside a `Transition` component.
Fixes: #3107
> Move focus to `ListboxOptions` and `MenuItems` when they are rendered later

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/floating.tsx
This PR ensures that components with the `anchor` prop always use the `floatingStyles` from Floating UI (which contains `position: absolute`).
This is important, otherwise there is a brief moment where the `<ListboxOptions anchor={…} />` (in case of a `Listbox`) is rendered at the end of the page.
One side effect of this is that this could cause a scrollbar to appear for a moment. But the `anchor` prop also renders the component in a `Modal` which does scroll locking (by applying `overflow: hidden;` to the body).
A side effect of adding `overflow: hidden` is that the scrollbar is removed. This is nice, but this causes a visual jump when the scrollbar is removed. To counteract this, we also add a `padding-right` based on the width of the scrollbar to the body to prevent the visual jump. …
> Ensure anchored components are always rendered in a stacking context

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/tooltip/tooltip.tsx
- packages/@headlessui-react/src/internal/floating.tsx
This PR allows to pass a boolean to the `anchor` prop on the `MenuItems`, `ListboxOptions`, `ComboboxOptions` and `PopoverPanel` components.
- If `anchor` or `anchor={true}` is used, then the anchoring functionality will be enabled but with the default (empty) configuration.
- If `anchor={false}` is used, then the anchoring functionality will be disabled.
> Allow passing a boolean to the `anchor` prop

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
When using a combobox disabled options get a `data-disabled` attribute that can be used for styling. However, when the combobox was virtualized we were not. This happened because we were only looking at the disabled prop on the option itself but a virtual combobox uses a disabled function in the `virtual` options to determine whether or not an option is enabled.
This fixes that 👍 
@RobinMalfait you have an idea on how this should be tested?
> Make sure data-disabled is available on virtualized options

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
This PR introduces a frozen value, similar to the `Listbox` component. This allows us to keep the visual state of the "old" value when selecting a new value.
The reason for this is that when you select a value, the combobox will close and in a lot of cases a (fade out) transition is happening. If we change the selected state to the new value, then the UI will flicker (or at least changes visual state) when the transition is happening. This PR prevents that. This is also how the native `<select>` works. 
Note: the `Combobox` and `ComboboxInput` still know about the correct newly selected value and will update `aria-activedescendant` information correctly.
Also note that this only happens in "single value mode", if you use the `multiple` prop, then the selected value will be updated …
> Add frozen value to `ComboboxOptions` component

- package-lock.json
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/package.json
This PR updates the minimal version requirements for `react` and `react-dom` dependencies to React 18 because we are using some React 18 only features in Headless UI v2.
> Update minimal peer dependency version requirements for `react` and `react-dom`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/floating.tsx
- playgrounds/react/pages/menu/menu-with-transition.tsx
- playgrounds/react/pages/popover/popover.tsx
This PR introduces a shorthand for the `anchor` API. The `anchor` prop now accepts a string that maps to the `anchor.to` property in the long-form object. Note: the long form object syntax is still supported.
The `anchor.gap`, `anchor.offset` and `anchor.padding` options use CSS variables by default. They are defined as `var(--anchor-gap)`, `var(--anchor-offset)` and `var(--anchor-padding)` respectively.
This means that you can fully customize the anchor styles by setting CSS variables, for example via Tailwind classes.
An example using Tailwind CSS:
```tsx
<Listbox>
<ListboxButton>Options</ListboxButton>
<ListboxOptions anchor="bottom start" className="[--anchor-gap:var(--spacing-1)] [--anchor-offset:calc(var(--spacing-1)*-1)]">
<ListboxOption>Listbox option A</ListboxOption> …
```
> Add string shorthand for the `anchor` prop

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/floating.tsx
We want to constrain the anchored element within the viewport (minus the padding if there is some). But without an `overflow: auto`, it would overflow and the `maxWidth` / `maxHeight` are a bit pointless.
Once you opt-in to `anchor`, then we have to provide styles anyway. This improves the UX.
> Add `overflow: auto` when using the `anchor` prop

- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
This PR improves the internal demo modes for the following components:
- `Dialog`
- `Combobox`
- `Menu` 
- `Popover`
This PR also adds a demo mode for the `Listbox` component.
> Improve internal demo mode

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/hooks/use-transition.ts
We recently made a change that the `Transition` component renders a `Fragment` by default. We also made sure that a `TransitionRoot` component (which could exist for orchestration purposes for child transitions) doesn't render a DOM node when it doesn't need to. This is the case if it doesn't have any `enter`, `enterFrom`, `enterTo`, `leave`, `leaveFrom`, or `leaveTo` props.
However, this caused a bug where the `Transition` component doesn't properly mount or unmount its children when the `TransitionRoot` component doesn't render a DOM node. This is because the `Transition` component relies on DOM transition events and will call the `onStart` and `onStop` callbacks when the transition starts and ends.
To solve this, we make sure to still call the `onStart` and `onStop` callbacks, because …
> Ensure `TransitionRoot` component without props transitions correctly

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/floating.tsx
When using the `anchor` prop, we try to position the anchored element within the viewport. We use the size middleware of Floating UI to ensure we are working in a constrained `max-width` and `max-height`.
However, if you want to limit the height of let's say a `ComboboxOptions` then you instinctively add `max-h-60` for example. The problem is that the `max-height` set by Floating UI will win because it's inline styles.
You could use `!max-h-60` which makes it `!important`, but then you can run into an issue where the max height set by the user is larger than the available space which results in combobox options that are unavailable.
To solve this, we want best of both worlds by ensuring we prefer the size from the user, but constrain it with the value we know.
We now read from a …
> Use `var(--anchor-max-height)` when using the `anchor` prop

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-inert-others.tsx
If you had a bare text node anywhere in the parent tree of an "allowed element" passed to useInertOthers() we would error because `getAtribute()` only exists on elements.
Basically code like this fails after interacting with the menu:
```jsx
test
<Menu>…</Menu>
```
> Only check for elements in `useInertOthers`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/floating.tsx
Our uses of the `flip` and `size` middleware from Floating UI were not taking the padding into account when they should be. This resulted in a weird behavior where scrolling or shrinking the viewport could change the height of the anchored element when there was definitely enough space for it to flip.
Now, it will prefer flipping and only shrink when there's not enough space to flip.
> Fix anchored elements not flipping when there is padding

- packages/@headlessui-react/src/components/combobox/combobox.tsx
Otherwise the render function will get called with different options by `render()` resulting in undefined (and possible render errors when operating on objects)
> Render virtual items during an exiting transition

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
With this change you'll be able to use the `empty:hidden` class to hide the combobox options when there are no options visible in both virtualized and normal comboboxes.
> Only render virtual options wrapper when there are items to show

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
1. If you open a combobox, select an option with the mouse (which closes it), and then reopen it does not scroll to the active option. This PR fixes this by resetting the internal "activation trigger" when the combobox closes.
2. If you open a combobox, hover over an option, then press up/down to select the option above or below it, then scroll with the mouse wheel the combobox will not let you scroll past the currently active option. This PR fixes this by ensuring interactions with the scroll wheel count as "pointer" interactions which allows the list to scroll freely.
> Fix issues with scrolling in a virtual combobox

- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/description/description.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
We keep specific types for elements with special meaning, such as `HTMLButtonElement`, `HTMLLabelElement` or `HTMLInputElement` because they receive certain attributes that generic DOM nodes (such as `HTMLDivElement`) don't
For the components where we use simple `div` elements by default (and where people use `as={...}` that renders a different element), it doesn't make sense to use `HTMLDivElement`. Using a more generic `HTMLElement` is simpler and more correct.
E.g.: we still had `HTMLUListElement` and `HTMLLIElement` for "div" DOM nodes which is incorrect.
This shouldn't be a breaking change because an `HTMLDivElement` is still a valid `HTMLElement`. The other way around wouldn't be the case.
> Use more generic `HTMLElement` type for DOM elements

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
Given that all components are available using names without a dot (e.g. `MenuItems` instead of `Menu.Items`, `ComboboxOption` instead of `Combobox.Option`, etc…) and that this isn't compatible with RSC we're deprecating this notation and pointing users to use the new names instead. All the old imports _will still work_ — this is merely a deprecation as we'll be removing these in a future version of Headless UI.
Here's a map of all the old component names and the new component names:
| Old Name | New Name |
| -- | -- |
| `<Combobox.Button>` | `<ComboboxButton>` |
| `<Combobox.Input>` | `<ComboboxInput>` |
| `<Combobox.Label>` | `<Label>` |
| `<Combobox.Option>` | `<ComboboxOption>` |
| `<Combobox.Options>` | `<ComboboxOptions>` |
| `<Dialog.Backdrop>` | `<DialogBackdrop>` |
| …
> Deprecate dot notation

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog-backdrop/dialog-backdrop.tsx
- packages/@headlessui-react/src/components/dialog-overlay/dialog-overlay.tsx
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/index.test.ts
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- playgrounds/react/pages/dialog/dialog.tsx
We deprecated those components in v1.6, since they are no longer documented and this is a major release, we can safely get rid of it.
If you still run into this, you should be able to replace the `<DialogOverlay>` and `<DialogBackdrop>` components with a simple `<div>` instead.
```diff
<Dialog>
-    <DialogOverlay className="..." />
+    <div className="..." />
<DialogPanel>
Content
</DialogPanel>
</Dialog>
```
Or
```diff
<Dialog>
-    <DialogBackdrop className="..." />
+    <div className="..." />
<DialogPanel>
Content
</DialogPanel>
</Dialog>
```
> Remove deprecated `DialogBackdrop` and `DialogOverlay` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/document-overflow/handle-ios-locking.ts
- packages/@headlessui-vue/src/hooks/document-overflow/handle-ios-locking.ts
We prevent the default `touchmove` event on some elements inside a dialog _on iOS_ as it is the only reliable way to prevent scrolling as `overflow: hidden` itself is not enough in some cases.
We shouldn't do this for `input` elements because cancelling the event for `<input type="range">` prevents the user from interacting with it at all. This PR checks for input elements and bails.
Fixes #3165
> Don’t cancel `touchmove` on `input` elements inside a dialog

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
These got left in from a rebase when they shouldn’t’ve been. whoops.
Fixes #3175
> Remove accidental deprecation comments on `<DialogPanel>` and `<DialogTitle>`

- packages/@headlessui-react/src/hooks/use-frame-debounce.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- packages/@headlessui-vue/src/hooks/use-disposables.ts
- packages/@headlessui-vue/src/hooks/use-frame-debounce.ts
- packages/@headlessui-vue/src/mouse.ts
This PR fixes an issue where typing into a Combobox (filtering), and then clicking an option doesn't correctly choose the option.
We also made sure that the `ComboboxInput` stays focused after selecting an option (even when clicking).
Fixes: #3178
> Ensure clicking a `ComboboxOption` after filtering the options, correctly triggers a change

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-inert-others.tsx
This PR improves the performance of the internal `useInertOthers` hook, which will be visible when a lot of elements are rendered on the page.
This gets rid of the default function arguments for `allowed` and `disallowed` and does an internal null check instead.
> Improve performance of internal `useInertOthers` hook

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
Our internal `__demoMode` prop that we use is intended to be disabled internally once a user interacts with the Combobox. However, we were incorrectly overriding this in a `useMemo` with the value of the prop which was always `true`.
> Make sure disabling demo mode on `<Combobox>` works

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
A dialog in demo mode always focuses the dialog container when it's not supposed to focus anything by default. This PR fixes that by removing the "fallback" focus element which is focused when nothing else is focused.
> Don’t set a focus fallback for Dialog’s in demo mode

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
This PR ensures that the page doesn't scroll down when pressing `Escape` to close an open `Dialog` component.
This only happens in Safari, and if the `document.activeElement` is an `<input>` for example. It also only happens when pressing `Escape`, not when clicking outside of the `Dialog` component.
The reason why is a bit confusing but it does make sense:
Whenever the the currently focused element is moved on the page, Safari will try to keep the `document.activeElement` in view. This means that when you press `Escape` that the `<input>` element is still focused, but since the `Dialog` closes, the `<input>` is still rendered in a portal at the end of the page. Because it's rendered there, Safari will try and keep it in view, which causes the page to scroll down.
It doesn't happen when …
> Ensure page doesn't scroll down when pressing `Escape` to close the `Dialog` component

- packages/@headlessui-react/src/components/dialog/dialog.tsx
When you have a `role="dialog"` and an `aria-modal="true"` at the same time, then Safari will focus the first focusable element inside the dialog.
This is not ideal, because in demo mode this means that the focus is moved around to various DOM elements.
This PR ensures that while demo mode is active, that the `aria-modal` attribute is not applied which means that focus is not automatically applied in Safari.
> Improve demo mode for `Dialog` component in Safari

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/switch/switch.tsx
This PR marks the `SwitchGroup` component as deprecated in favor of the new `<Field>` component.
The `SwitchGroup` component was useful if you wanted to link a `<Switch>` and a `<Switch.Label>` together. However, now we have more generic components that allows you to do this instead and is more consistent with all other components as well.
E.g.:
```tsx
<Switch.Group>
<Switch.Label>Label</Switch.Label>
<Switch />
</Switch.Group>
```
↓↓↓↓
```tsx
<SwitchGroup>
<SwitchLabel>Label</SwitchLabel>
<Switch />
</SwitchGroup>
```
↓↓↓↓
```tsx
<Field>
<Label>Label</Label>
<Switch />
</Field>
```
This `Field` and `Label` component combination can also be used with other components like `Checkbox`, `Combobox`, `Input`, `Listbox`, `Radio`, `Select`, and `Textarea`.
> Mark `SwitchGroup` as deprecated, prefer `Field` instead

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
This PR fixes an issue where toggling between virtual and non-virtual mode would not correctly merge the `virtual` configuration and therefore it would crash the entire component.
This PR fixes that behavior and correctly switches to virtual mode. This also contains some internal refactors to clean things up related to `virtual` mode.
Fixes: #3235
> Fix crash when toggling between `virtual` and non-virtual mode in `Combobox` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
This PR fixes a bug where pressing <kbd>tab</kbd> on a `<PopoverButton>` does not move focus inside of a portalled `<PopoverPanel>` component when it is opened and when you are not using a wrapping `<PopoverGroup>` component.
If you didn't use a `<Portal />` or `portal` or `anchor` prop then this would not be an issue.
If you used a `<PopoverGroup />` then this would not be an issue.
Fixes: #3231
> Ensure tabbing to a portalled `<PopoverPanel>` component moves focus inside (without using `<PortalGroup>`)

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/checkbox/checkbox.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/hooks/use-default-value.ts
This PR fixes a bug where it would call the `onChange` of a `<Listbox>` or `<Combobox>` component when used inside of a `<form>` even if no `defaultValue` was provided. This also happened for the `<Checkbox>` and `<Switch>` component but for the `defaultChecked` prop.
This means that the `onChange` would be called with `undefined` which your application might not expect.
This PR only calls `onChange` with the `defaultValue` (or `defaultChecked` for `<Checkbox>` or `<Switch>` components) if it is provided.
This PR also has a small refactor to ensure we can safely use `defaultChecked` and `defaultValue` in dependency arrays of hooks.
> Only handle form reset when `defaultValue` is used

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/field/field.test.tsx
- packages/@headlessui-react/src/components/fieldset/fieldset.test.tsx
- packages/@headlessui-react/src/components/fieldset/fieldset.tsx
- packages/@headlessui-react/src/hooks/use-resolved-tag.ts
This PR improves the default behavior of our `<Fieldset />` component.
Initially we used a `div` because `fieldset` / `legend` is hard to style otherwise. However, a fieldset on its own is still useful and has some benefits (such as disabling all native form elements if the `fieldset` itself is disabled).
We still setup an internal `DisabledProvider` such that our own components can read from this state and disable themselves accordingly.
This is technically a breaking change, but I doubt that anyone runs into this issue.
If so, you can apply the following diff to fix it:
```diff
- <Fieldset>
+ <Fieldset as="div">
{/* … */}
</Fieldset>
```
Note: if you were already using `disabled` on the `<Fieldset disabled>`, and you use `as="div"` then you won't have the default behavior where it …
> Use native `fieldset` instead of `div` by default for `<Fieldset />` component

- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/hooks/use-did-element-move.ts
- packages/@headlessui-react/src/hooks/use-inert-others.test.tsx
- packages/@headlessui-react/src/hooks/use-inert-others.tsx
- packages/@headlessui-react/src/hooks/use-on-disappear.ts
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-react/src/hooks/use-scroll-lock.ts
- packages/@headlessui-react/src/hooks/use-tree-walker.ts
This PR is an internal refactor change that cleans up the signature of hooks that require an `enabled` state.
Whenever a hook requires an `enabled` state, the `enabled` parameter is moved to the front. Initially this was the last argument and enabled by default but everywhere that we use these hooks we have to pass a dedicated boolean anyway.
This makes sure these hooks follow a similar pattern. Bonus points because Prettier can now improve formatting the usage of these hooks. The reason why is because there is no additional argument after the potential last callback.
Before:
```ts
let enabled = data.__demoMode ? false : modal && data.comboboxState === ComboboxState.Open
useInertOthers(
{
allowed: useEvent(() => [
data.inputRef.current,
data.buttonRef.current,
data.optionsRef.current,
]), …
```
> [internal] Move `enabled` parameter in hooks to first argument

- package-lock.json
- packages/@headlessui-react/package.json
This PR bumps dependencies in `package.json` to the latest version.
This is technically not needed because all versions are within the range specified in `package.json`, but it also doesn't hurt.
Fixes: #3238
> Bump dependencies

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
This PR fixes an issue where a `<Combobox>` would close if you click inside the scrollbar area on the `<ComboboxOptions>`. This is because clicking inside the scrollbar area performs a click on the element below the scrollbar (at least on macOS). If the element below is focusable, then focus will be moved there.
If focus is moved to the underlying element, then the `<ComboboxInput>` will blur which causes the `<Combobox>` will close.
This issue can be seen in #3230 where using the `<Combobox>` inside the `<Dialog>` then clicking in the scrollbar area of the `<ComboboxOptions>` will move the focus to the `<Dialog>` itself and closes the `<Combobox>`.
Fixes: #3230
> Keep `<Combobox />` open when clicking in scrollbar on `<ComboboxOptions>`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
This PR makes sure that incoming `style` props are merged in with the `style` prop that we provide.
We were overriding the `style` prop entirely on the `<ComboboxOptions>`, `<ListboxOptions>`, `<MenuItems>`, and `<PopoverPanel>` for anchoring purposes, as well as provided some CSS variables.
This now ensures that the incoming `style` prop gets merged in.
Fixes: #3248
> Merge incoming `style` prop on `ComboboxOptions`, `ListboxOptions`, `MenuItems`, and `PopoverPanel` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
Fixes #3189
The dropdown will jitter when using the native scrollbar **before** entering the dropdown list with your cursor or using the mouse wheel to scroll.
This is because the `﻿ActivationTrigger` has not been set to pointer. As a result, ﻿`scrollToIndex` is called while you are attempting to scroll, leading to the rubberband effect.
If you are on macOS, go to **System Settings** and set Show Scroll Bars to **Always**.
It can be difficult to reproduce without this, as you must hover over the native scroll bar first avoid triggering any React events.
https://github.com/danthomps/headlessui/assets/7358641/0fa2cc8b-7855-4a7a-a04e-0c5551a5e221
Occasionally, React can render the scrolling quickly enough to make the rubberbanding non-visible, making it somewhat challenging to consistently …
> Fix visual jitter in `Combobox` component when using native scrollbar

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/utils/stable-collection.tsx
These may break in any React release which may result in blocking the ecosystem from seemlessly upgrading to new React releases.
We can use `useId` instead which is available since React 18.
Keep in mind that the whole hook is not safe in concurrent rendering. It increments `render` during render but only decrements in an effect cleanup. React may render multiple times before actually committing. The keys would leak in those scenarios (e.g. when a sibling suspends).
Closes https://github.com/tailwindlabs/headlessui/issues/3167
> Use `useId` instead of React internals

- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
This PR improves some internals by using `flushSync()` instead of our `d.nextFrame()` calls.
The benefit is that `flushSync()` guarantees that the DOM is updated after this call finishes. This means that we don't have to schedule a callback in the future and _hope_ that the DOM is updated by that time.
> Internal refactor: use `flushSync()` instead of `d.nextFrame()`

- package-lock.json
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-document-event.ts
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-react/src/hooks/use-tab-direction.ts
- packages/@headlessui-react/src/hooks/use-window-event.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/hooks/use-document-event.ts
- packages/@headlessui-vue/src/hooks/use-outside-click.ts
- packages/@headlessui-vue/src/hooks/use-tab-direction.ts
- packages/@headlessui-vue/src/hooks/use-window-event.ts
- playgrounds/vue/package.json
This PR improves the outside click behavior on touch devices.
Before this change, if a `<Menu />` or `<Dialog />` was open, then "scrolling" or "swiping" your finger on the screen would close the `<Menu />` or `<Dialog />` respectively.
This is because we also checked for `touchend` events (which are fired when you lift your finger). Right now, we will make sure that your finger has to move at least some amount (set it to 30px for now, which felt good while testing on mobile devices) in order to cancel the outside click behaviour. If you didn't move within 30px then we consider it an outside click.
Now, scrolling doesn't close the component, but a tap (`touchend`) will close it as expected.
Fixes: #3038
> Cancel outside click behavior on touch devices when scrolling

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/transition/__snapshots__/transition.test.tsx.snap
- packages/@headlessui-react/src/components/transition/transition.test.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/components/transition/utils/transition.ts
- packages/@headlessui-react/src/hooks/use-flags.ts
- packages/@headlessui-react/src/hooks/use-transition-data.ts
This PR adds a new way of dealing with transitions. Instead of using the `<Transition />` component and using the `enter`, `enterFrom`, `enterTo`, `leave`, `leaveFrom` and `leaveTo` props, we can now define all of that in CSS.
Most components that are rendered conditionally based on the state of the component:
- `ComboboxOptions`
- `DisclosurePanel`
- `ListboxOptions`
- `MenuItems`
- `PopoverPanel`
Will now accept a `transition` prop. The moment that is enabled then we will expose `data-from`, `data-enter`, `data-exit` and `data-transition` data attributes at the correct time. You can use these data attributes in your CSS or Tailwind Classes to style these components.
The lifecycle of the data attributes look like this:
```
┌─────┐              │       ┌────────────┐
│From │ …
```
> Introduce CSS based transitions

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
This PR updates the behavior of the `Listbox` component and allows you to use <kbd>tab</kbd> and <kbd>shift+tab</kbd> and it will go to the next or previous focusable element respectively.
Before this we used to focus trap, but now we will be consistent with the existing `Combobox` and `Menu` components. This also now reflects the ARIA Authoring Practices Guide.
Fixes: #3272
> Allow `Tab` and `Shift+Tab` when `Listbox` is open

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transition/__snapshots__/transition.test.tsx.snap
- packages/@headlessui-react/src/components/transition/transition.test.tsx
- packages/@headlessui-react/src/hooks/use-transition-data.ts
This PR updates the newly exposed data attributes introduced in #3273
After playing with them in real projects, we improved the naming for a few reasons:
1. If you are describing the "from" state and if it's different for `enter` and `exit` then you would have to type:
```html
<div
class="data-[enter]:data-[from]:-translate-x-full data-[exit]:data-[from]:-translate-x-full"
></div>
```
And `data-[exit]:data-[from]` reads like you are transitioning from a certain state, but you are transitioning _to_ that state.
2. If you use `leave` instead of `exit` then it will be consistent with the properties that we already have on the `Transition` component. Additionally, the length is the same now so they align better.
```jsx
<div
className={clsx(
"data-[enter]:data-[closed]:-transition-x-full", …
```
> Rename `data-from` -> `data-closed` and `data-exit` -> `data-leave`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/internal/frozen.tsx
- playgrounds/react/pages/combobox/combobox-countries.tsx
- playgrounds/react/pages/combobox/combobox-virtualized.tsx
- playgrounds/react/pages/listbox/listbox-with-pure-tailwind.tsx
This PR improves the UX when you are closing a `Combobox` that uses a `Transition` while closing.
Typically the `Combobox` component is used with a filtered list based on the value of the `ComboboxInput`. When the `Combobox` closes then the `onClose` will be called. In this function you typically reset the search query state as well:
```tsx
import { Combobox, ComboboxInput, ComboboxOption, ComboboxOptions } from '@headlessui/react'
import { useState } from 'react'
const people = [
{ id: 1, name: 'Durward Reynolds' },
{ id: 2, name: 'Kenton Towne' },
{ id: 3, name: 'Therese Wunsch' },
{ id: 4, name: 'Benedict Kessler' },
{ id: 5, name: 'Katelyn Rohan' },
]
function Example() {
const [selectedPerson, setSelectedPerson] = useState(people[0])
const [query, setQuery] = useState('')
const …
```
> Improve UX by freezing `<ComboboxOptions />` component while closing

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/index.test.ts
- playgrounds/react/pages/dialog/dialog-built-in-transition.tsx
This PR adds a `transition` prop to the `<Dialog />` component. Internally it uses the `<Transition />` and `<TransitionChild />` components to coordinate the transitions.
The `<Dialog />` itself will be wrapped in a `<Transition />`, the `<DialogPanel />` will be wrapped in a `<TransitionChild />`, and to make the backdrop transition happen we re-introduced the `<DialogBackdrop />` component which is a `div` wrapped in a `<TransitionChild />`.
Recently we introduced `data-*` attribute based transitions (#3273) to simplify transitions. This also introduced the `transition` prop on components such as:
- `ComboboxOptions`
- `DisclosurePanel`
- `ListboxOptions`
- `MenuItems`
- `PopoverPanel`
This PR now also adds it to the `<Dialog />` component. This is what a migration could look like: …
> Add `transition` prop to `<Dialog />` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover-backdrop/popover-backdrop.tsx
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/index.test.ts
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
Now we'll have a `<PopoverBackdrop />` component and a `PopoverBackdropProps` type. We're aliasing `PopoverOverlay` to `PopoverBackdrop` and `PopoverOverlayProps` to `PopoverBackdropProps` for backwards compatibility.
> Rename `PopoverOverlay` to `PopoverBackdrop`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/internal/open-closed.tsx
- playgrounds/react/pages/dialog/dialog-built-in-transition.tsx
- playgrounds/react/pages/dialog/dialog.tsx
This PR is a continuation of #3307
In #3307 we introduced the `transition` prop on the `Dialog` component. But to make the API more consistent with the other components we want to be explicit and add the `transition` prop to the elements where the data attributes are being used.
This means that instead of enabling it on the `Dialog` directly, you add the `transition` prop to the individual components:
```tsx
<Dialog open={open} onClose={setOpen}>
<DialogBackdrop transition className="ease-in-out duration-300 data-[closed]:opacity-0 data-[closed]:scale-95" />
<DialogPanel transition className="ease-in-out duration-300 data-[closed]:opacity-0 data-[closed]:scale-95 bg-white">
{/* … */}
</DialogPanel>
</Dialog>
```
It's only needed on the `Dialog` component directly if you also want to …
> Add `transition` prop to `DialogPanel` and `DialogBackdrop` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
This PR adds the `aria-hidden` attribute to the `DialogBackdrop` component to be consistent with the `PopoverBackdrop` component.
> Add `aria-hidden` to `DialogBackdrop` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/transition/__snapshots__/transition.test.tsx.snap
- packages/@headlessui-react/src/components/transition/transition.test.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/hooks/use-transition.ts
This PR makes sure that the transition data, such as `closed`, `enter`, `leave` and `transition` is only mapped as data attributes e.g.: `data-closed`.
This PR removes the information from the render prop.
```tsx
<Menu>
<MenuItems>
{({ ... /* Won't include `closed`, `enter`, `leave`, or `transition` */ }) => (
<>
<MenuItem as="a" href="#">
Alice
</MenuItem>
<MenuItem as="a" href="#">
Bob
</MenuItem>
<MenuItem as="a" href="#">
Charlie
</MenuItem>
</>
)}
</MenuItems>
</Menu>
```
> Remove transition state from render props

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/types.ts
- packages/@headlessui-react/src/utils/render.test.tsx
- packages/@headlessui-react/src/utils/render.ts
The existing `PropsForFeatures` type is meant to enable mutually exclusive props. 
A component may accept `static` and `unmount` but may not accept both simultaneously. We encoded this in the typescript types but it's causing more problems than it solves. For example, `Omit<ComponentProps, 'className'>` can't be spread back onto the component.
So this basically replaced the three cases with the following:
1. `{ static?: boolean }`
2. `{ unmount?: boolean }`
3. `{ static?: boolean, unmount?: boolean }`
This makes TypeScript much happier about the types and should help typeschecking performance too.
> Fix issues spreading omitted props onto components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.tsx
This PR fixes a bug where using the `anchor="selection"` results in an incorrectly positioned anchor panel.
This happened because we computed the `index` too late and didn't re-render to fix up the UI.
To solve this, this PR computes it based on actual state instead of DOM nodes.
We will also compute the selected option based on the frozen state. This will prevent UI glitches while closing the `Listbox`.
> Fix initial `anchor="selection"` state

- packages/@headlessui-react/src/components/combobox/combobox.tsx
> Use `any` for `ComboboxOptions` render prop `option`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
Ensure that each `Dialog` is always a new `Transition` boundary such that nested `TransitionChild` components are correctly handled.
If you happen to nest `Dialog` components in places where you shouldn't (e.g.: inside a `Disclosure` instead of a `DisclosurePanel`) then it could lead to a crash that has been fixed by this change.
Fixes: #3316
Fixes: #3322
> Fix incorrect `Transition` boundary for `Dialog` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.tsx
This PR fixes an issue where anchoring related styles were applied to the `ListboxOptions` even without using the `anchor` prop.
Fixes: #3336
> Fix prematurely added anchoring styles on `ListboxOptions`

- package-lock.json
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/package.json
- packages/@headlessui-react/src/components/combobox/combobox.tsx
This PR fixes an issue where using `@tanstack/react-virtual` with an empty array could lead to crashes such as:
```
Error: Unexpected undefined
```
Providing an empty array can happen if you filter the options based on the value of the `ComboboxInput`.
This PR fixes that by bumping the `@tanstack/react-virtual` library and using the `enabled` value and disable it when no options are given.
Fixes: #3353
> Fix crash in `Combobox` component when in `virtual` mode when options are empty

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/internal/floating.tsx
- playgrounds/react/pages/listbox/listbox-with-pure-tailwind.tsx
This PR fixes an issue where your tests could hang (due to an infinite loop) when testing components using the `anchor` prop in a JSDOM based environment.
The issue that we were causing an infinite loop because some computation ended up resulting in `NaN`. There is also a very elegant purely CSS based solution (using `round()`) to the underlying problem, but it _just_ got support in Chrome, so for now we will just fix the issue.
Fixes: #3339
Fixes: #3294
> Fix hanging tests when using `anchor` prop

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/popover/popover.tsx
This PR fixes an issue where the combination of the `focus` and `transition` prop on the `PopoverPanel` component didn't work as expected.
The issue is that we moved focus inside the `PopoverPanel` in an effect, and we relied on a `useRef` to get access to the `PopoverPanel` DOM node. However, due to the transition, this ref wasn't filled in. The moment the ref is filled in, it's too late and the effect doesn't re-run anymore.
Instead, we rely on the DOM element that's coming from state. This one is updated and will re-render the component because we update the state when the ref is available.
Fixes: #3358
> Fix `transition` and `focus` prop combination for `PopoverPanel` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/hooks/use-root-containers.tsx
- packages/@headlessui-react/src/internal/hidden.tsx
This PR fixes an issue where nested `Popover` components that are using the `anchor` prop (and thus are portalled) are not correctly closed when clicking outside.
The issue stems from incorrect DOM node references to know whether we are allowed to click on a certain DOM element or not.
As a general recap, when an outside click happens, we need to react to it and typically use the `useOutsideClick` hook for this.
We also require the context of "allowed root containers", this means that clicking on a 3rd party toast when a dialog is open, that we allow this even though we are technically clicking outside of the dialog. This is simply because we don't have control over these elements.
We also need a reference to know what the "main tree" container is, because this is the container where your …
> Fix outside click in nested portalled `Popover` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/utils/active-element-history.ts
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/utils/active-element-history.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
Right now, we have to record when a click / mousedown / focus event happens on an element. But when you click on a non-focusable element inside of a focusable element then we record the inner element instead of the outer one.
This happens in this scenario:
```html
<button>
<span>click me</span>
</button>
```
This solves it by resolving the closest focusable element (and we fallback to the e.target as a last resort)
Fixes: #3320
> Fix restoring focus to correct element when closing `Dialog` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
This PR fixes an issue where React shows a warning that it is not able to use `flushSync` while it's already rendering.
The recommended solution in that case is to move the `flushSync` call to a scheduler task or micro task.
The scenario where it happens in this case:
```ts
{condition && (
<Combobox immediate>
<ComboboxInput autoFocus />
</Combobox>
)}
```
This will conditionally render the `Combobox` with the `immediate` prop (which means that it will open once the `ComboboxInput` receives focus). But the `ComboboxInput` also has the `autoFocus` prop which means that it will focus immediately when it's rendered.
Fixes: #3334
> Fix `flushSync` warning for `Combobox` component with `immediate` prop enabled

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transition/transition.tsx
This was originally introduced in https://github.com/tailwindlabs/headlessui/pull/1519 to fix an issue where some enter transitions where broken: https://github.com/tailwindlabs/headlessui/issues/1503
However, since we refactored the `Transition` component to make use of the `useTransition` hook, I can't seem to reproduce this issue anymore.
In fact, removing this code fixes an issue.
The bigger issue here is that when the component becomes hidden, that we always set the state to hidden as well. But if it becomes visible again, we don't show it again.
Right now, since I couldn't reproduce any of the other issue, I opted to just removing the code entirely. But if we ever need it again, we probably have to make sure that it becomes visible in the other scenario as well.
Fixes: #3328
> Ensure `Transition` component state doesn't change when it becomes hidden

- packages/@headlessui-vue/README.md
This PR updates the link to the Vue docs for Headlessui.
> Update link to Vue docs

- packages/@headlessui-react/src/components/combobox/combobox.tsx
Fixes: https://github.com/tailwindlabs/headlessui/issues/3391
When multiple is specified we expect TValue to already be an array, so lets just ensure its an array and use it as the type for virtual.options. Similarly the disabled callback gets passed a TValue, but when multiple is true it is passed something of type element of TValue.
Behaviour in javascript lines up with this fine, just a type level fix afaik.
> Fix `Combobox` `virtual` mode types for `multiple`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/components/transition/__snapshots__/transition.test.tsx.snap
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/hooks/use-did-element-move.ts
- packages/@headlessui-react/src/hooks/use-element-size.ts
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-react/src/hooks/use-refocusable-input.ts
- packages/@headlessui-react/src/hooks/use-resolve-button-type.ts
- packages/@headlessui-react/src/hooks/use-transition.ts
This PR fixes an issue where components such as the `MenuItems` and the `ListboxOptions` won't close correctly if these are used in combination with the `transition` prop and _after_ you scrolled the page a little bit.
For some background information: the `Menu` and `Listbox` components can be used with the `transition` prop so that the `MenuItems` and `ListboxOptions` can be transitioned in and out based on the open/closed state.
To make the user experience better, we have some logic to check whether the `MenuButton` or `ListboxButton` moved from its initial position. If it did move when it's closing, then we immediately stop all transitions by unmounting the `MenuItems` or `ListboxOptions` immediately.
A situation this happens in:
1. Open the `Menu` (with the `transition` prop)
2. Press …
> Fix closing components using the `transition` prop, and after scrolling the page

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/close-provider.tsx
This PR adds a missing client boundary in the close provider file that was causing crashes when used with Turbopack as reported in the Next.js repo: https://github.com/vercel/next.js/issues/68205
Thanks to @richardasymmetric [fantastic repro](https://github.com/vercel/next.js/issues/68205
) I could check out the example repo and link a tarball build of the updated `@headlessui/react` package to validate that this is enough to resolve the issue. After this change, `next dev` and `next dev --turbo` work in the same way.
> Add client hint to close provider

- .github/workflows/main.yml
- .github/workflows/prepare-release.yml
- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
GitHub began the Node 16 deprecation process a year ago [^1][^2]. Our workflow runs have been annotated with the deprecation warnings.
This PR updates all workflows to use the latest version of actions which runs on Node 20. No breaking changes introduced.
1. [actions/checkout](https://github.com/actions/checkout) 
2. [actions/setup-node](https://github.com/actions/setup-node)
3. [actions/cache](https://github.com/actions/cache)
4. [softprops/action-gh-release](https://github.com/softprops/action-gh-release)
[^1]: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
[^2]: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> Update workflows to use latest version of actions

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.test.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
This PR fixes a bug where the components don't always properly close when using the `transition` prop on those components.
The issue here is that the internal `useTransition(…)` hook relies on a DOM node. Whenever the DOM node changes, we need to re-run the `useTransition(…)`. This is why we store the DOM element in state instead of relying on a `useRef(…)`. 
Let's say you have a `Popover` component, then the structure looks like this:
```ts
<Popover>
<PopoverButton>Show</PopoverButton>
<PopoverPanel>Contents</PopoverPanel>
</Popover>
```
We store a DOM reference to the button and the panel in state, and the state lives in the `Popover` component. The reason we do that is so that the button can reference the panel and the panel can reference the button. This is needed for some `aria-*` …
> Fix components not properly closing when using the `transition` prop

- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/package.json
- packages/@headlessui-vue/src/hooks/use-id.ts
https://github.com/tailwindlabs/headlessui/discussions/3457
Vue 3.5 added a native SSR-safe `useId` function. This PR updates the code to use that function by default if no custom function has been provided.
Theoretically this is a breaking change, as versions prior to Vue 3.5 are no longer supported.
However, package managers should emit a warning or an error when the peer dependency range is no longer satisfied.
> use native `useId` from Vue.js 3.5 when available

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.tsx
This PR fixes an issue where the `ListboxOptions` component was incorrectly marked as `inert`.
We only mark the other elements on the page as `inert` once the `Listbox` is in a visible state. The issue is that the `data.optionsElement` (a reference to the DOM node) was not populated with the actual DOM node yet at the time the `useInertOthers(…)` hook was applied. 
Due to the usage of `useEvent(…)`, instead of `useCallback(…)` the internal `useEffect(…)` hook didn't re-run because the `allowed` function was already stable. 
With this fix, the `allowed` function will change whenever its dependencies change.
Fixes: #3464
> Fix `ListboxOptions` being incorrectly marked as `inert`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/button/button.test.tsx
- packages/@headlessui-react/src/components/button/button.tsx
- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
This PR fixes an issue where a maximum update depth exceeded error was thrown when using `as={Fragment}` on button related components.
The issue here is that the `ref` on a element would re-fire every render _if_ the a function was used _and_ the function is a new function (aka not a stable function).
This resulted in the `ref` being called with the DOM element, then `null`, then the DOM element, then `null`, and so on.
To solve this, we have to make sure that the `ref` is always a stable reference.
Fixes: #3476
Fixes: #3439
> Fix crash when using `as={Fragment}` on `MenuButton`, `ListboxButton`, `DisclosureButton` or `Button` components

- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
Using @headlessui close methods/types in a project with eslint-typescript currently causes "UnboundMethod" errors because we're using class member syntax to define the functions.
I tweaked the declarations here to use arrow syntax in few places. The behavior should be unchanged, but we are no longer implying the existence of a "this"
> Update react types to avoid unbound method lint errors

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-transition.ts
In some environments `Element` won't be available, which is needed for the `Element.prototype.getAnimations` polyfill. If `Element` is not available at all, it means that we are not in a browser so we don't need the polyfill.
Fixes: #3490
> Ensure `Element` is available before polyfilling

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/floating.tsx
This PR fixes an issue where in some environments where `HTMLElement` is not
available (on the server) and AG Grid is used, we crashed.
This happens because the `HTMLElement` is polyfilled to an empty object. This means that the `typeof HTMLElement !== 'undefined'` check passed, but the `v instanceof HTMLElement` translated to `v instanceof {}` which is invalid and resulted in a crash...
This PR solves it by checking for exactly what we need, in this case whether the `outerHTML` property is available.
Alternatively, we could use `return v?.outerHTML ?? v`, but not sure if that's always safe to do.
Fixes: #3471
> Fix crash when using `instanceof HTMLElement` in some environments

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/components/combobox/combobox.ts
This PR is a different approach compared to #3487. 
Instead of checking whether we are in a test environment (specifically in a Jest environment), I think we can just get rid of the check entirely and use the virtualizer in all environments.
This will remove an unnecessary check for `process` being available and gets rid of `process` entirely. It also fixes an issue that #3487 tries to solve where `process` is available, but `process.env` is not.
Closes: #3487
> Cleanup `process` in Combobox component when using virtualization

- packages/@headlessui-react/src/components/button/button.tsx
- packages/@headlessui-react/src/components/checkbox/checkbox.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/data-interactive/data-interactive.tsx
- packages/@headlessui-react/src/components/description/description.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/field/field.tsx
- packages/@headlessui-react/src/components/fieldset/fieldset.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/input/input.tsx
- packages/@headlessui-react/src/components/label/label.tsx
- packages/@headlessui-react/src/components/legend/legend.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/select/select.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/components/textarea/textarea.tsx
- packages/@headlessui-react/src/components/tooltip/tooltip.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/internal/hidden.tsx
- packages/@headlessui-react/src/test-utils/execute-timeline.ts
- packages/@headlessui-react/src/types.ts
- packages/@headlessui-react/src/utils/render.test.tsx
- playgrounds/react/pages/suspense/portal.tsx
The global JSX type is deprecated in React 18.3 and removed in React 19 RC. This PR changes the code to use the supported React.JSX syntax instead.
PS. Would you accept a similar PR for 1.x? I personally haven't upgraded all my projects yet.
> Use `React.JSX` instead of `JSX`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/button/button.tsx
- packages/@headlessui-react/src/components/checkbox/checkbox.tsx
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/data-interactive/data-interactive.tsx
- packages/@headlessui-react/src/components/description/description.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/field/field.tsx
- packages/@headlessui-react/src/components/fieldset/fieldset.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/input/input.tsx
- packages/@headlessui-react/src/components/label/label.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/select/select.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/components/textarea/textarea.tsx
- packages/@headlessui-react/src/components/tooltip/tooltip.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/internal/hidden.tsx
- packages/@headlessui-react/src/utils/render.test.tsx
- packages/@headlessui-react/src/utils/render.ts
This PR fixes an issue where a `Maximum update depth exceeded` error occurs if you use `as={Fragment}` in the `ListboxOptions` component.
This PR also includes a refactor to make sure this exact issue cannot happen anymore in other components.
Fixes: #3507
> Fix crash in `ListboxOptions` when using `as={Fragment}`

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/package.json
- packages/@headlessui-react/src/utils/render.ts
This PR fixes an issue where `@headlessui/react` was not compatible with React 19.
We made sure that accessing `ref`s is safe and works in React 18 and React 19. We also made sure to include React 19 as a valid version in the peer dependencies. For now, we also allowed the RC versions of React and React DOM.
> Add React 19 support

- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/utils/owner.ts
- packages/@headlessui-vue/src/utils/owner.ts
This PR improves the internal `<Portal>` component by allowing to pass in a custom `ownerDocument`.
This fixes an issue if you do something like this:
```ts
import { Menu, MenuButton, MenuItem, MenuItems } from '@headlessui/react'
import { useState } from 'react'
import { createPortal } from 'react-dom'
export default function App() {
let [target, setTarget] = useState(null)
return (
<div className="grid min-h-full place-content-center">
<iframe
ref={(iframe) => {
if (!iframe) return
if (target) return
let el = iframe.contentDocument.createElement('div')
iframe.contentDocument.body.appendChild(el)
setTarget(el)
}}
className="h-[50px] w-[75px] border-black bg-white"
>
{target && createPortal(<MenuExample />, target)}
</iframe>
</div>
)
}
function MenuExample() {
return (
<Menu> …
```
> Use correct `ownerDocument` when using internal `<Portal/>`

- package-lock.json
- packages/@headlessui-react/package.json
`@tanstack/react-virtual` added peer deps support for React 19 in [v3.11.0](https://github.com/TanStack/virtual/releases/tag/v3.11.0) (https://github.com/TanStack/virtual/pull/893)
This PR upgrades the packages. This can resolve some warnings on some React 19 projects, e.g.:
```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @tanstack/react-virtual@3.10.9
npm warn Found: react@19.0.0
npm warn node_modules/react
npm warn   peer react@"^18 || ^19 || ^19.0.0-rc" from @headlessui/react@2.2.0
npm warn   node_modules/@headlessui/react
npm warn     @headlessui/react@"^2.2.0" from the root project
npm warn   15 more (@floating-ui/react, @floating-ui/react-dom, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer react@"^16.8.0 || ^17.0.0 || ^18.0.0" from …
```
> Bump @tanstack/react-virtual

- package-lock.json
- packages/@headlessui-tailwindcss/CHANGELOG.md
- packages/@headlessui-tailwindcss/package.json
Resolves #3633
Bumps the version range for `@headlessui/tailwindcss` to ensure support with Tailwind CSS v4.
> Support installing with Tailwind CSS v4

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/input/input.tsx
- packages/@headlessui-react/src/components/select/select.tsx
- packages/@headlessui-react/src/components/textarea/textarea.tsx
This PR fixes an issue with the `aria-invalid` attributes on some form elements.
In theory this shouldn't matter and behaves the same as other attributes. MDN also mentions that any other value than the known set of values will be treated as `true`.
However, some tools, including the Accessibility tab in Google Chrome will complain because we set it to `aria-invalid=""`.
We already used `'true'` for `aria-checked` as well, so this change makes it more consistent.
It will also make sure that `aria-invalid:flex` in Tailwind CSS works as expected because this compiles to:
```css
.aria-invalid\:flex {
&[aria-invalid="true"] {
display: flex;
}
}
```
Which means that the current implementation didn't work in this case either.
Fixes: #3623
> Fix `aria-invalid` attributes to have a valid `'true'` value

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/checkbox/checkbox.tsx
This PR allows you to pass a `tabIndex` to the `Checkbox` component.
> Accept `tabIndex` on `Checkbox` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
This PR allows you to pass a `tabIndex` to the `<RadioGroup>` component and it will internally pass it down to the correct `<Radio />` or `<RadioGroupOption>` component.
The reason we do it this way is because only a single radio should be focusable (moving between radios can be done via the arrow keys instead of the tab key).
> Accept `tabIndex` on `<RadioGroup>` component

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- playgrounds/react/pages/combobox/combobox-virtualized.tsx
This PR fixes an issue where the `Combobox` component crashes if you are using the `virtual` option and you quickly type something such that the `Combobox` opens but no valid options are available.
We already check if the current active index is available in the internal `options` list. However, if you then call `virtualizer.scrollToIndex(data.activeOptionIndex)` it will crash if you are too fast.
https://github.com/user-attachments/assets/f48172e6-4098-4a31-aa16-67ce21f074d1
If you are typing slowly, then it will work as expected.
https://github.com/user-attachments/assets/9d522bd5-5b54-4c12-9250-a2d92a511b35
I did find an open issue on TanStack's repo about this: https://github.com/TanStack/virtual/issues/879
This PR is basically a workaround by delaying the call. But it does have the …
> Fix `Unexpected undefined` crash in `Combobox` component with `virtual` mode

- package-lock.json
- packages/@headlessui-react/package.json
- packages/@headlessui-react/src/machine.ts
- packages/@headlessui-react/src/react-glue.tsx
- scripts/watch.sh
This PR is just a chore to prepare for future performance optimizations. Essentially I want to improve the performance of the `Menu`, `Listbox` and `Combobox` components but I want to do it in separate PRs such that reverting the improvements can be done if needed.
This PR just sets up a `Machine` for state machines, and adds some helpers such as a `useSlice` to calculate parts of the state machine. Component using the `useSlice` will only re-render _if_ the slice changes.
So apart from adding a library (`useSyncExternalStoreWithSelector`) and adding some setup code. Nothing in this PR changes the behavior of the components.
> Prepare for performance improvements

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/menu/menu-machine-glue.tsx
- packages/@headlessui-react/src/components/menu/menu-machine.ts
- packages/@headlessui-react/src/components/menu/menu.tsx
This PR improves the performance of the `Menu` component.
Before this PR, the `Menu` component is built in a way where all the state lives in the `Menu` itself. If state changes, everything re-renders and re-computes the necessary derived state.
However, if you have a 1000 items, then every time the active item changes, all 1000 items have to re-render.
To solve this, we can move the state outside of the `Menu` component, and "subscribe" to state changes using the `useSlice` hook introduced in https://github.com/tailwindlabs/headlessui/pull/3684.
This will allow us to subscribe to a slice of the state, and only re-render if the computed slice actually changes.
If the active item changes, only 3 things will happen:
1. The `MenuItems` will re-render and have an updated …
> Improve `Menu` component performance

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox-machine-glue.tsx
- packages/@headlessui-react/src/components/listbox/listbox-machine.ts
- packages/@headlessui-react/src/components/listbox/listbox.tsx
This PR improves the performance of the `Listbox` component.
Before this PR, the `Listbox` component is built in a way where all the state lives in the `Listbox` itself. If state changes, everything re-renders and re-computes the necessary derived state.
However, if you have a 1000 options, then every time the active option changes, all 1000 options have to re-render.
To solve this, we can move the state outside of the `Listbox` component, and "subscribe" to state changes using the `useSlice` hook introduced in https://github.com/tailwindlabs/headlessui/pull/3684.
This will allow us to subscribe to a slice of the state, and only re-render if the computed slice actually changes.
If the active option changes, only 3 things will happen:
1. The `ListboxOptions` will re-render and have an …
> Improve `Listbox` component performance

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
This is a small behavioral change, but this PR will change when the `Menu` and `Listbox` components open. 
This PR will now open the `Menu` and `Listbox` components on `mousedown` instead of `click`. This will make it feel more responsive and faster to the user.
This is also how macOS for example opens menu-like components on the OS level. This is also how the native `<select>` (at least on macOS) works.
> Open `Menu` and `Listbox` on `mousedown`

- packages/@headlessui-react/src/components/listbox/listbox-machine.ts
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu-machine.ts
- packages/@headlessui-react/src/components/menu/menu.tsx
In a previous PR, we already batched registering options. This PR also batches unregistering options to make the closing behavior smoother when there are a lot of items rendered.
> Improve performance of `Listbox` and `Menu` when closing

- packages/@headlessui-react/src/components/listbox/listbox-machine.ts
- packages/@headlessui-react/src/components/menu/menu-machine.ts
I'm not 100% sure this is the right fix but it _does_ fix keyboard navigation in listbox and menu when using strict mode.
Basically the same items/options are being registered more than once and that causes the arrow up/down logic to only advance on every other keypress.
> Only register an option once in strict mode

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/transition/transition.tsx
This PR fixes an issue where the scroll locking logic was incorrectly re-enabled in Dialogs if you were using a `Transition` component or a `transition` prop _and_ you had nested  components with the `transition` prop (or a nested `TransitionChild` component) _and_ the parent transition finishes before any of its children.
To visualize this, it would happen in this situation:
```tsx
<Dialog transition> /* No transition classes */
<DialogBackdrop transition className="duration-500" />
<DialogPanel transition className="duration-200" />
</DialogPanel>
</Dialog>
```
With the `transition` prop, internally these components would render a wrapper `Transition` component.
The `Dialog` will look at the open/closed state provided by the `Transition` component to know whether to unmount its children …
> Fix `Transition` component from incorrectly exposing the `Closing` state

- package-lock.json
- package.json
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/package.json
- packages/@headlessui-react/src/components/combobox/combobox-machine-glue.tsx
- packages/@headlessui-react/src/components/combobox/combobox-machine.ts
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-vue/package.json
- packages/@headlessui-vue/src/components/combobox/combobox.test.ts
- packages/@headlessui-vue/src/components/combobox/combobox.ts
- patches/@tanstack+virtual-core+3.13.6.patch
- playgrounds/react/pages/combobox/combobox-countries.tsx
This PR improves the performance of the `Combobox` component. This is a similar implementation as:
- https://github.com/tailwindlabs/headlessui/pull/3685
- https://github.com/tailwindlabs/headlessui/pull/3688
Before this PR, the `Combobox` component is built in a way where all the state lives in the `Combobox` itself. If state changes, everything re-renders and re-computes the necessary derived state.
However, if you have a 1000 items, then every time the active item changes, all 1000 items have to re-render.
To solve this, we can move the state outside of the `Combobox` component, and "subscribe" to state changes using the `useSlice` hook introduced in https://github.com/tailwindlabs/headlessui/pull/3684.
This will allow us to subscribe to a slice of the state, and only re-render if the …
> Improve `Combobox` component performance

- jest/polyfills.ts
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/hooks/use-quick-release.ts
- packages/@headlessui-react/src/utils/dom.ts
- playgrounds/react/pages/menu/menu.tsx
This PR adds a new quick trigger feature to the `Menu`. Not sure what the best
name for this is, but essentially this is the behavior:
Recently we made sure that the `Menu` opens on `mousedown` (not just `click`).
This means that we can perform the following quick action:
1. `mousedown` on the `MenuButton` — this will open the `Menu`
2. Without releasing the mouse button yet, move your mouse over one of the `MenuItem`s — this will highlight the currently active `MenuItem`.
3. Release the mouse button — this will invoke the currently active `MenuItem` and close the `Menu`.
This now means that you can perform actions very quickly.
What this PR doesn't do yet is if you have a scrollable list, then it won't scroll up or down when you reach the ends of the list. For this we would need to …
> Add a quick trigger action to the `Menu`, `Listbox` and `Combobox` components

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/label/label.tsx
- playgrounds/react/pages/combinations/form.tsx
This PR fixes an issue where the `<Label>` component didn't open the `<input type="file">` when clicking it.
For native elements, the `Label` component already renders a native `<label>` behind the scenes. Some native elements like `<input type="checkbox">` immediately change the state of the element whereas some other elements don't such as `<select></select>` you just get the focus.
However, `<input type="file">` should also immediately open the file picker when clicking the label and this was not the case. This PR fixes that.
Since we are already using a native `<label>` _and_ linking the `<label>` with its `<input type="file">` performing a `.click()` is allowed.
Fixes: #3680
You can play with it here: https://headlessui-react-git-fix-issue-3680-tailwindlabs.vercel.app/combinations/for …
> Fix clicking `<Label />` opens `<input type="file">`

- packages/@headlessui-react/src/components/label/label.tsx
- packages/@headlessui-react/src/utils/dom.ts
- playgrounds/react/pages/combinations/form.tsx
This PR fixes an issue where clicking on an interactive element _inside_ of a `<Label>` component should work as expected.
For example, if you have this situation:
```html
<label for="tac">
<input id="tac" type="checkbox" name="terms-and-conditions" />
I agree to the <a href="terms-and-conditions.html">Terms and Conditions</a>
</label>
```
Clicking on the `<a href="#">` inside the label should _not_ check the checkbox, but should open the link instead.
Fixes: #3658
> Ensure clicking on interactive elements inside `<Label>` works

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/label/label.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/hooks/document-overflow/handle-ios-locking.ts
- packages/@headlessui-react/src/hooks/use-on-disappear.ts
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-react/src/hooks/use-quick-release.ts
- packages/@headlessui-react/src/hooks/use-refocusable-input.ts
- packages/@headlessui-react/src/hooks/use-resolved-tag.ts
- packages/@headlessui-react/src/hooks/use-root-containers.tsx
- packages/@headlessui-react/src/internal/floating.tsx
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-react/src/utils/active-element-history.ts
- packages/@headlessui-react/src/utils/bugs.ts
- packages/@headlessui-react/src/utils/disposables.ts
- packages/@headlessui-react/src/utils/dom.ts
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-react/src/utils/get-text-value.ts
This PR fixes an issue where the focus is not returned to an `SVG` element with a `tabIndex` correctly.
There are a few issues going on here:
1. We assume that the element to focus (`e.target`) is an instanceof `HTMLElement`, but the `SVGElement` is not an instanceof `HTMLElement`.
2. By using `instanceof` we are checking against concrete classes, so if this happen to cross certain contexts (Shadow DOM, Iframes, ...) then the instances would be different.
To solve this, we will now:
1. Relax the types and only care about the actual attributes and methods we are interested in. In most cases this means changing internal types from `HTMLElement` to `Element` for example.
2. We will check whether certain properties are available in the object to deduce the correct type from the object.
Fixes: …
> Fix focus not returned to SVG Element

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox-machine.ts
- packages/@headlessui-react/src/components/listbox/listbox.tsx
This PR fixes an issue where if a Listbox does not have a value yet, and it's opened via an ArrowUp or ArrowDown (on the ListboxButton) then it didn't correctly go to the firs or last option.
Before, we were opening the listbox in a `flushSync()` call, after that call we were focusing the first or last option depending on if you used the ArrowDown or ArrowUp keys.
However, the options can and will be registered at a later point in time, which means that the focus of first or last option is technically going to fail because no options are available yet.
With this fix we don't need the `flushSync` call, and instead we passthrough a pending focus. Once the options are registered, if a pending focus is present, only then will we focus the correct option.
This gets rid of timing issues.
> Fix `Listbox` not focusing first or last option on ArrowUp/ArrowDown

- packages/@headlessui-react/src/components/combobox/combobox.test.tsx
- packages/@headlessui-react/src/components/dialog/dialog.test.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/popover/popover.test.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx
- packages/@headlessui-react/src/components/switch/switch.test.tsx
- packages/@headlessui-react/src/components/tabs/tabs.test.tsx
This PR simplifies the internal tests a bit.
1. Don't explicitly test if a component has a specific ID
1. Don't mock the `useId` hook if it's not necessary
What we care about more is that 2 components (E.g.: `MenuButton` and `MenuItems`) are connected to each other. This is done via `id` and `aria-controls` attributes. The exact ID is not important.
The main motivation for this is that every time we introduce some `useId()` hook call somewhere, the IDs will shift and it will look like some tests are broken.
If we are not explicitly testing the IDs, we also don't really care about deterministic incrementing IDs in tests, so therefore we can remove some `useId` mocking.
Note: some tests still have mocks like this (e.g.: `description.test.ts` & `label.test.ts`) but that's because they have …
> Simplify internal tests

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-is-top-layer.ts
- packages/@headlessui-react/src/machine.ts
- packages/@headlessui-react/src/machines/stack-machine.ts
- playgrounds/react/pages/dialog/dialog.tsx
This PR fixes a performance issue where all components using the `useIsTopLayer` hook will re-render when the hook changes.
For context, the internal hook is used to know which component is the top most component. This is important in a situation like this:
```
<Dialog>
<Menu />
</Dialog>
```
If the Menu inside the Dialog is open, it is considered the top most component. Clicking outside of the Menu or pressing escape should only close the Menu and not the Dialog.
This behavior is similar to the native `#top-layer` you see when using native dialogs for example.
The issue however is that the `useIsTopLayer` subscribes to an external store which is shared across all components. This means that when the store changes, all components using the hook will re-render. 
To make things worse, since …
> Performance improvement: only re-render top-level component

- packages/@headlessui-react/src/components/popover/popover-machine-glue.tsx
- packages/@headlessui-react/src/components/popover/popover-machine.ts
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- playgrounds/react/pages/popover/popover.tsx
This PR is an internal refactor, similar to what we did recently for the `Menu`, `Listbox` and `Combobox` components by using a dedicated state machine.
This is basically a one-to-one translation without any further optimizations
1. All tests are passing
1. Verified that the Popover still works as expected: https://headlessui-react-git-chore-popover-using-st-7fa062-tailwindlabs.vercel.app/popover/popover
> Implement `Popover` using a separate state machine

- jest/polyfills.ts
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox-machine-glue.tsx
- packages/@headlessui-react/src/components/combobox/combobox-machine.ts
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/listbox/listbox-machine-glue.tsx
- packages/@headlessui-react/src/components/listbox/listbox-machine.ts
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu-machine-glue.tsx
- packages/@headlessui-react/src/components/menu/menu-machine.ts
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover-machine-glue.tsx
- packages/@headlessui-react/src/components/popover/popover-machine.ts
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/hooks/use-outside-click.ts
- packages/@headlessui-react/src/hooks/use-scroll-lock.ts
- playgrounds/react/pages/menu/menu.tsx
- playgrounds/react/pages/menu/multiple-elements.tsx
- playgrounds/react/pages/popover/popover.tsx
Fixes: #3701
This PR fixes an issue where an open `Menu` is not closed when opening a new `Menu`. This is also fixed for `Listbox` and `Combobox` that used the same techniques.
This happened because we recently shipped an improvement where the `Menu` opens on `pointerdown` instead of on `click`. This means that the `useOutsideClick` hook was not correct anymore because it relies on `click`.
We could try and figure out that we should already close on `pointerdown` but this might not be expected for other components. Instead we want to simplify things a bit and ideally not even worry about what event caused a specific state change.
Instead of trying to fight timing issues when certain events happen, this PR takes a slightly different approach.
We already had the concept of a "top-layer" …
> Fix closing `Menu` when other `Menu` is opened

- jest/polyfills.ts
- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- playgrounds/react/pages/listbox/listbox-overlaps.tsx
Fixes #3750
@RobinMalfait is this the right approach?
> Fix listbox closing immediately after opening on touch devices

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/hooks/use-quick-release.ts
This PR fixes an issue where menu items would be invoked twice when you click on an item.
This is due to a bug in the `useQuickRelease` hook where the timestamp was not reset correctly, which means that the actual click caused a quick release trigger. This in turn selects / invokes the menu item even though it was already triggered by the click of the user.
This PR fixes that by resetting the timestamp as soon as possible, which also cleans up the code a bit because there is only 1 branch where we need to reset instead of in every branch before returning.
Fixes: #3763
Fixes: #3764
Fixes: #3765
> Fix incorrect double invocation of menu items

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/listbox/listbox.test.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.test.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
This PR fixes an issue where adding a ref to the `<MenuButton ref={btnRef}>` and later calling `btnRef.current.click()` would not open the `Menu`.
This is happening because recently we started using `pointerdown` instead of `click` to open the `Menu`. So the only way to open the `Menu` programmatically is to call `btnRef.current.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }))` which is a bit of a mouthful.
We also recently fixed an issue where the `Listbox` would immediately close after opening the Listbox on touch devices. That solution required us to not only handle the `pointerdown` event but also the `click` event.
So if anything, this PR makes the code more consistent between the `Menu` and `Listbox` component behavior and in turn solves this `ref.current.click()` …
> Ensure `buttonRef.current.click()` works

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
This PR fixes an issue where a listbox with the `static` option had a delayed `selected` value.
This was happening because of 2 reasons:
1. The `isSelected` function had stale data
2. We use a "frozen value", but we shouldn't do that when the listbox options are using the `static` option.
The frozen data is used to prevent UI jumps when you have transitions. For example, if you fade out the listbox when closing then if you select an option the selected state (and a checkmark for example) would move around to the newly selected option while the listbox is fading out. To prevent that we "freeze" the selected value until the listbox is fully closed. This behaves the same as a native select element.
Fixes: #3778
Tested the fix with the reproduction from the issue: …
> Ensure we are not freezing data when the `static` prop is used

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/switch/switch.tsx
- packages/@headlessui-react/src/hooks/document-overflow/overflow-store.ts
- packages/@headlessui-react/src/hooks/use-transition.ts
This PR fixes an issue where the types for certain event handlers such as `onChange` on the `Combobox` component were incorrectly typed as bivariant instead of contravariant.
This is now fixed by using function property syntax instead of method syntax.
Before:
```tsx
function onChange(value: string) {}
// This would have worked, even though the internal types are `(value: string | null) => void`
return <Combobox onChange={onChange} />;
```
After:
```tsx
function onChange(value: string) {}
// This now errors because we expect `string | null`
return <Combobox onChange={onChange} />;
```
In both cases:
```tsx
function onChange(value: string | null) {}
// This is the correct type, and works in both cases
return <Combobox onChange={onChange} />;
```
A pure TypeScript example, thanks to …
> Ensure `onChange` types are contravariant instead of bivariant

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/test-utils/interactions.ts
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-vue/CHANGELOG.md
- packages/@headlessui-vue/src/test-utils/interactions.ts
- packages/@headlessui-vue/src/utils/focus-management.ts
- [`<summary>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary) is a built-in heading tag that is nested inside a [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) tag to toggle its contents. It's keyboard tab-able by default and not currently recognized by Headless UI.
- There are no attributes that disable a summary tag, and adding `tabindex="-1"` makes it behave like any other normally-tab-able element.
- I didn't spot any tests that specifically check for tab-ability of elements outside of buttons and inputs. Let me know if I missed anything.
> Support `<summary>` as a focusable element

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/hooks/use-element-size.ts
This PR fixes an issue where the `--button-width` and `--input-width` CSS variables weren't always up to date.
We compute these values initially when the component mounts based on the `getBoundingClientRect` of the button and input elements. 
To ensure we catch changes in size, we setup a `ResizeObserver` that watches for changes to the button and input elements.
Unfortunately, `ResizeObserver` doesn't fire when the size changes due to CSS properties such as `transform` or `scale`. As far as I can tell, there isn't a single event or Observer we can use to catch all possible changes.
One solution to this problem would be to delay the computation of the sizes until after all transitions have completed and then we could even introduce a small delay to ensure everything is in its final state. …
> Ensure `--button-width` and `--input-width` are always up to date

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/transition/transition.tsx
- packages/@headlessui-react/src/utils/render.ts
This PR fixes an issue in React 19 where a warning is shown in the console:
```
Invalid prop `data-headlessui-state` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
```
This PR fixes that by doing 2 things:
1. We make sure that we properly check for `Fragment`. We were relying on identity, but will now also check the underlying symbol.
2. Make sure that the element we forward props to is not a `Fragment` either.
- All existing tests still pass (this codebase is using React 18 instead of 19,
where we can't reproduce the warning)
- Tested in a reproduction repo with React 19 that the warning is gone.
Before:
After:
Fixes: #3597
Fixes: #3351
> Fix 'Invalid prop `data-headlessui-state` supplied to `React.Fragment`' warning

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
- packages/@headlessui-react/src/components/dialog/dialog.tsx
- packages/@headlessui-react/src/components/disclosure/disclosure.tsx
- packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx
- packages/@headlessui-react/src/components/listbox/listbox.tsx
- packages/@headlessui-react/src/components/menu/menu.tsx
- packages/@headlessui-react/src/components/popover/popover-machine.ts
- packages/@headlessui-react/src/components/popover/popover.tsx
- packages/@headlessui-react/src/components/portal/portal.tsx
- packages/@headlessui-react/src/components/radio-group/radio-group.tsx
- packages/@headlessui-react/src/components/tabs/tabs.tsx
- packages/@headlessui-react/src/hooks/use-owner.ts
- packages/@headlessui-react/src/hooks/use-refocusable-input.ts
- packages/@headlessui-react/src/hooks/use-root-containers.tsx
- packages/@headlessui-react/src/test-utils/accessibility-assertions.ts
- packages/@headlessui-react/src/utils/focus-management.ts
- packages/@headlessui-react/src/utils/owner.ts
This PR improves the focus management when Headless UI components are used inside of a shadow DOM.
We already tried to not use `document` directly, but instead rely on `someKnownElement.ownerDocument` to get the correct document context. 
This is unfortunately not enough, because if you have a focused element _inside_ the shadow DOM, then `ownerDocument.activeElement` will return the wrapping shadow DOM node and not the actual focused element inside of the shadow DOM.
This PR improves that behavior by using `getRootNode()` instead and then we read information such as the `activeElement` from there.
It's going to be easier if you look at this reproduction. The element with the black border is a shadow DOM element. The `toggle` button is a Popover button.
Expected behavior:
1. You can tab …
> Improve focus management in shadow roots

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/components/combobox/combobox.tsx
Fixes #3558
Our combobox uses them to jump to the beginning or end of the option list but it doesn't make sense to capture these if the combobox isn't open.
This will allow the home/end keys to function normally for the Combobox's input field which means, for Windows at least, the caret will moved to the beginning or end of the input. (macOS doesn't do this unless you also hold shift to select text).
Before:
https://github.com/user-attachments/assets/8d545613-cd93-4a46-8609-cc66dd960502
After:
https://github.com/user-attachments/assets/426748b5-f66d-4bb9-80ba-be6a9b621618
> Allow home/end key default behavior inside `ComboboxInput` when `Combobox` is closed

- packages/@headlessui-react/CHANGELOG.md
- packages/@headlessui-react/src/internal/frozen.tsx
We were wrapping rendered children in `<Frozen>` in a combobox however the refs weren't being forwarded through the internal `<Frozen>` component resulting in issues when rendering `<ComboboxOptions>` as a `Fragment`.
After this PR the following code no longer warns about function components not accepting refs.
```tsx
import { Combobox, ComboboxInput, ComboboxOption, ComboboxOptions } from '@headlessui/react'
import React from 'react'
export default function Example() {
return (
<div className="p-4">
<Combobox>
<ComboboxInput className="rounded border border-neutral-400 p-2" />
<ComboboxOptions as={React.Fragment}>
<div className="bg-orange-500 p-4">
<ComboboxOption value="a">A</ComboboxOption>
</div>
</ComboboxOptions>
</Combobox>
</div>
)
}
```
Fixes #3384
> Ensure refs are forwarded when freezing data
