tailwindlabs/headlessui

packages/@headlessui-react/README.md
Hey there!
I just added a couple of fragments to the jsx examples to prevent the famous error `"Parse Error: Adjacent JSX elements must be wrapped in an enclosing tag"`.
Greetings!
=> jsx wrapped in enclosing tags (@headlessui-react/readme.md)

packages/@headlessui-react/src/components/transitions/transition.tsx
=> cleanup transition

packages/@headlessui-react/README.md
Looks like an old variable that hasn't been renamed
=> Fix variable name in README

packages/@headlessui-react/README.md, packages/@headlessui-vue/README.md
- format README's with Prettier
- hoist people list
- make whitespace consistent
=> improve documentation

packages/@headlessui-vue/src/components/listbox/listbox.ts, packages/@headlessui-vue/src/components/switch/switch.ts
This PR fixes #122 
Docs: https://v3.vuejs.org/api/options-data.html#emits
Difference to Vue 2: https://v3.vuejs.org/guide/migration/emits-option.html#_3-x-behavior
=> Added emits property to Vue components

packages/@headlessui-react/README.md
remove unused import in example
=> Small cleanup in React Readme

packages/@headlessui-react/src/components/menu/menu.tsx, packages/@headlessui-react/src/components/radio-group/radio-group.tsx, packages/@headlessui-react/src/hooks/use-tree-walker.ts, packages/@headlessui-vue/src/components/menu/menu.ts, packages/@headlessui-vue/src/components/radio-group/radio-group.ts, packages/@headlessui-vue/src/hooks/use-tree-walker.ts
- add useTreeWalker hooks
- use useTreeWalker hook
=> add use tree walker hook

packages/@headlessui-vue/src/components/dialog/README.md, packages/@headlessui-vue/src/components/dialog/dialog.test.ts, packages/@headlessui-vue/src/components/dialog/dialog.ts, packages/@headlessui-vue/src/components/portal/portal.ts, packages/@headlessui-vue/src/internal/portal-force-root.ts, packages/@headlessui-vue/src/internal/stack-context.ts, packages/@headlessui-vue/src/utils/render.ts
- use close event instead of onClose prop
- pass explicit `visible` prop to the `Portal` component
- ensure that we can render Dialog in a transition
=> Improve Vue dialog

packages/@headlessui-react/src/utils/render.ts
=> chore: Fix typo in render.ts

CHANGELOG.md, packages/@headlessui-react/src/components/dialog/dialog.test.tsx, packages/@headlessui-react/src/components/dialog/dialog.tsx, packages/@headlessui-vue/src/components/dialog/dialog.test.ts, packages/@headlessui-vue/src/components/dialog/dialog.ts
=> fix clicks and form submissions in Dialog component

CHANGELOG.md, packages/@headlessui-react/src/components/radio-group/radio-group.test.tsx, packages/@headlessui-react/src/components/radio-group/radio-group.tsx, packages/@headlessui-vue/src/components/radio-group/radio-group.test.ts, packages/@headlessui-vue/src/components/radio-group/radio-group.ts
This will happen when:
- The RadioGroup is disabled
- The RadioGroup Option is disabled
Closes: #515
=> add `aria-disabled` to RadioGroup Options

CHANGELOG.md, packages/@headlessui-react/package.json
=> Update react peer dependency version range

CHANGELOG.md, packages/@headlessui-vue/src/components/dialog/dialog.ts
=> Fix missing type causing prop check error

CHANGELOG.md, packages/@headlessui-react/package.json
- ensure react-dom is also a peer dependency
- prepare peer dependencies for React 18
Closes: #615
=> improve react peer deps

CHANGELOG.md, packages/@headlessui-vue/src/hooks/use-window-event.ts
=> Use `watchEffect` instead of immediately using an event listener on `window`

packages/@headlessui-vue/examples/src/components/tabs/tabs.vue
This PR is a rebased version of #1006, while maintaining the original author.
Closes #1006
=> Fix missing key binding in examples

packages/@headlessui-react/src/components/focus-trap/focus-trap.test.tsx, packages/@headlessui-vue/src/components/focus-trap/focus-trap.test.ts
This PR adds some tests that proves that the guard against infinite loops is important.
=> Add tests to prove guarding against infinite loops is important

packages/@headlessui-react/src/components/combobox/combobox.tsx, packages/@headlessui-react/src/components/description/description.tsx, packages/@headlessui-react/src/components/dialog/dialog.tsx, packages/@headlessui-react/src/components/disclosure/disclosure.tsx, packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx, packages/@headlessui-react/src/components/label/label.tsx, packages/@headlessui-react/src/components/listbox/listbox.tsx, packages/@headlessui-react/src/components/menu/menu.tsx, packages/@headlessui-react/src/components/popover/popover.tsx, packages/@headlessui-react/src/components/portal/portal.tsx, packages/@headlessui-react/src/components/radio-group/radio-group.tsx, packages/@headlessui-react/src/components/switch/switch.tsx, packages/@headlessui-react/src/components/tabs/tabs.tsx, packages/@headlessui-react/src/hooks/use-event.ts, packages/@headlessui-react/src/hooks/use-flags.ts, packages/@headlessui-react/src/hooks/use-iso-morphic-effect.ts, packages/@headlessui-react/src/hooks/use-sync-refs.ts, packages/@headlessui-react/src/internal/stack-context.tsx
This PR does a bit of cleanup / consistency work...
=> General/random internal cleanup (part 1)

packages/@headlessui-react/CHANGELOG.md, packages/@headlessui-react/src/components/combobox/combobox.tsx, packages/@headlessui-vue/CHANGELOG.md, packages/@headlessui-vue/src/components/combobox/combobox.ts
Fix https://github.com/tailwindlabs/headlessui/issues/1849
=> Prevent option selection in `ComboboxInput` while composing

packages/@headlessui-vue/CHANGELOG.md, packages/@headlessui-vue/src/components/combobox/combobox.ts, packages/@headlessui-vue/src/components/listbox/listbox.ts
This PR is a continuation to further improve the types of the `ListboxOption` and `ComboboxOption` components
=> Improve `ListboxOption` and `ComboboxOption` types

packages/@headlessui-react/src/components/tabs/tabs.test.tsx, packages/@headlessui-react/src/components/tabs/tabs.tsx, packages/@headlessui-vue/src/components/tabs/tabs.test.ts
=> Preserve default index when starting out with no tabs

packages/@headlessui-react/src/components/portal/portal.tsx
PR https://github.com/tailwindlabs/headlessui/pull/2456 created a new hook `useOnUnmount`. 
This PR is intended to make use of the hook for the cleanup process in the `Portal` component.
=> Change `Portal` cleanup process to use `useOnUnmount` hook

packages/playground-react/package.json, packages/playground-react/pages/menu/menu-with-floating-ui.tsx, packages/playground-vue/package.json, packages/playground-vue/src/components/menu/menu-with-floating-ui.vue, yarn.lock
This PR adds a Floating UI example for the Menu component
=> Add Floating UI examples in combination with the Menu component

package.json, packages/playground-react/next.config.js, packages/playground-react/pages/combobox/combobox-open-on-focus.tsx, packages/playground-react/pages/combobox/combobox-virtual-with-empty-states.tsx, packages/playground-react/pages/combobox/combobox-virtualized.tsx, yarn.lock
This PR is a first step in making the builds pass for the playgrounds again.
The first step is to disable type checking in the playgrounds for now. Once the builds pass, we can
continue to solving the actual type issues (if any).
=> Make playgrounds build again

jest/polyfills.ts, package-lock.json, package.json, packages/@headlessui-react/package.json, packages/@headlessui-react/src/components/combobox/combobox.test.tsx, packages/@headlessui-react/src/components/dialog/dialog.test.tsx, packages/@headlessui-react/src/components/listbox/listbox.test.tsx, packages/@headlessui-react/src/components/menu/menu.test.tsx, packages/@headlessui-react/src/components/popover/popover.test.tsx, packages/@headlessui-react/src/components/transition/transition.test.tsx, packages/@headlessui-react/src/test-utils/interactions.ts, packages/@headlessui-vue/src/components/combobox/combobox.test.ts, packages/@headlessui-vue/src/components/dialog/dialog.test.ts
This PR bumps the dependencies, mostly patch releases and a few bigger bumps such as `@tanstack/react-virtual`.
=> Bump dependencies

packages/@headlessui-react/src/test-utils/interactions.ts
Without the `act` you may see unrelated test failures in React 19.
=> Fix missing act warnings issued from `focus` and `blur` calls

package-lock.json, packages/@headlessui-react/package.json
=> Update @react-aria/focus and @react-aria/interactions dependencies to latest versions

package-lock.json, packages/@headlessui-react/CHANGELOG.md, packages/@headlessui-react/src/machine.ts, playgrounds/react/next-env.d.ts, playgrounds/react/package.json
This PR fixes an issue where setting up components on the server (SSR) could result in memory leaks because we only dispose state machines on the client, not on the server.
Fixes: #3747
=> Fix memory leak in SSR environment
